' TEST: check-fail
$CONSOLE:ONLY
' Calls of built-ins the old compiler rejects (verification\v20_x*, m2-core-builtins): the wrong number of arguments,
' a string where a number is needed and the reverse, empty parentheses, a built-in used as a statement
PRINT LEFT$("abc")
PRINT MID$("abc")
PRINT LEFT$(5, 1)
PRINT STR$("a")
PRINT _TOSTR$("a")
PRINT STRING$("a", "b")
PRINT SPACE$()
PRINT UCASE$(1)
LEFT$("a", 1)
PRINT LEN(5)
PRINT LEN(i + 1)
PRINT LEN()
PRINT ASC("a", 1, 1)
PRINT HEX$("a")
PRINT VAL(5)
PRINT VAL("1", STRING)
PRINT VAL("1", 2)
LEN("a")
PRINT SQR("4")
PRINT ABS("a")
PRINT SIN()
PRINT _PI(1, 2)
PRINT _PI()
PRINT CINT("1")
PRINT _ATAN2(1)
