//! The language's reserved words (design D1, D3 of `m2-procedures-and-errors`): the words the old compiler adds to
//! its name table as reserved before compiling (`qb64pe.bas`, "add reserved words to hashtable"). None of them can
//! name a variable or procedure (measured: each one as a variable name is rejected). A statement that starts with
//! one the parser does not handle gets a "not supported yet" error at parse time.
//!
//! Built-in SUB and function names (`CLS`, `LEN`) are not here: they come from the built-in table, which only
//! `sema` reads.

const KEYWORDS: &[&str] = &[
    // types
    "_UNSIGNED",
    "_BIT",
    "_BYTE",
    "INTEGER",
    "LONG",
    "_INTEGER64",
    "_OFFSET",
    "SINGLE",
    "DOUBLE",
    "_FLOAT",
    "STRING",
    "ANY",
    // operators
    "NOT",
    "IMP",
    "EQV",
    "AND",
    "OR",
    "XOR",
    "MOD",
    "_NEGATE",
    "_ANDALSO",
    "_ORELSE",
    // words inside statements
    "LIST",
    "BASE",
    "_EXPLICIT",
    "_EXPLICITARRAY",
    "AS",
    "IS",
    "OFF",
    "ON",
    "STOP",
    "TO",
    "USING",
    "_DYNAMIC",
    "_STATIC",
    "PRESET",
    "PSET",
    "FOR",
    "OUTPUT",
    "RANDOM",
    "BINARY",
    "APPEND",
    "SHARED",
    "ACCESS",
    "LOCK",
    "READ",
    "WRITE",
    "STEP",
    "LPRINT",
    "PRINT",
    // statements
    "COMMON",
    "CALL",
    "CASE",
    "COM",
    "CONST",
    "DATA",
    "DECLARE",
    "DEF",
    "DEFDBL",
    "DEFINT",
    "DEFLNG",
    "DEFSNG",
    "DEFSTR",
    "DIM",
    "DO",
    "ERROR",
    "ELSE",
    "ELSEIF",
    "ENDIF",
    "EXIT",
    "FIELD",
    "FUNCTION",
    "GOSUB",
    "GOTO",
    "INPUT",
    "IF",
    "KEY",
    "LET",
    "LOOP",
    "LEN",
    "NEXT",
    "PLAY",
    "PEN",
    "REDIM",
    "REM",
    "RESTORE",
    "RESUME",
    "RETURN",
    "RUN",
    "STATIC",
    "STRIG",
    "SEG",
    "SELECT",
    "SUB",
    "SCREEN",
    "THEN",
    "TIMER",
    "TYPE",
    "UNTIL",
    "UEVENT",
    "WEND",
    "WHILE",
];

/// Whether `name` (without a type suffix) is a reserved word, ASCII case ignored.
pub fn is_keyword(name: &[u8]) -> bool {
    KEYWORDS.iter().any(|k| k.as_bytes().eq_ignore_ascii_case(name))
}
