//! Generates the built-in table from `tools/builtins/builtins.json` (panel R9: extracted, not hand-written).

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let json_path = manifest.join("../../tools/builtins/builtins.json");
    println!("cargo:rerun-if-changed={}", json_path.display());
    #[expect(clippy::disallowed_methods, reason = "JSON, not BASIC source")]
    let text = std::fs::read_to_string(&json_path).expect("read tools/builtins/builtins.json");
    let doc: serde_json::Value = serde_json::from_str(&text).expect("parse builtins.json");
    let entries = doc["entries"].as_array().expect("entries array");

    let mut out = String::from("// Generated by build.rs from tools/builtins/builtins.json. Do not edit.\n");
    out.push_str("pub static BUILTINS: &[Builtin] = &[\n");
    for e in entries {
        let s = |k: &str| e.get(k).and_then(|v| v.as_str());
        let kind = match s("kind") {
            Some("function") => "Kind::Function",
            Some("sub") => "Kind::Sub",
            other => panic!("unknown kind {other:?}"),
        };
        let arg_types: Vec<String> = e
            .get("arg_types")
            .and_then(|v| v.as_array())
            .map(|a| a.iter().map(|t| format!("{:?}", t.as_str().unwrap())).collect())
            .unwrap_or_default();
        let format = s("specialformat");
        let slots = match format {
            Some(f) => slot_list(f),
            None => Some(vec![false; arg_types.len()]),
        };
        let slots = match slots {
            Some(v) => format!(
                "Some(&[{}])",
                v.iter().map(|o| o.to_string()).collect::<Vec<_>>().join(", ")
            ),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "    Builtin {{ name: {:?}, kind: {kind}, callname: {:?}, arg_types: &[{}], optional: {slots}, \
             specialformat: {:?}, ret: {:?}, musthave: {:?} }},",
            s("name").unwrap(),
            s("callname").unwrap_or(""),
            arg_types.join(", "),
            format,
            s("ret"),
            s("musthave"),
        )
        .unwrap();
    }
    out.push_str("];\n");
    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("builtins_table.rs");
    std::fs::write(dest, out).unwrap();
}

/// For a format made only of `?`, `,`, `[` and `]` (every function format): one entry per `?`, true when it is
/// inside brackets (optional). Formats with words or other symbols (statement syntaxes) give `None`.
fn slot_list(format: &str) -> Option<Vec<bool>> {
    let mut depth = 0i32;
    let mut slots = Vec::new();
    for c in format.chars() {
        match c {
            '[' => depth += 1,
            ']' => depth -= 1,
            '?' => slots.push(depth > 0),
            ',' => {}
            _ => return None,
        }
    }
    Some(slots)
}
