$CONSOLE:ONLY
' Differential program (m2-numeric-types, design D2): PRINT and STR$ of every numeric type's values, from variables and as literals.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
' Each _BIT * 40 has a _BIT * 32 pad DIMmed just before it, which the old compiler's overlap hits
' instead (DIVERGENCES.md D-009).
ON ERROR GOTO h
DIM vbyte_min AS _BYTE
DIM vbyte_max AS _BYTE
DIM vbyte_m1 AS _BYTE
DIM vbyte_zero AS _BYTE
DIM vbyte_one AS _BYTE
DIM vbyte_r1 AS _BYTE
DIM vbyte_r2 AS _BYTE
DIM vubyte_min AS _UNSIGNED _BYTE
DIM vubyte_max AS _UNSIGNED _BYTE
DIM vubyte_m1 AS _UNSIGNED _BYTE
DIM vubyte_zero AS _UNSIGNED _BYTE
DIM vubyte_one AS _UNSIGNED _BYTE
DIM vubyte_r1 AS _UNSIGNED _BYTE
DIM vubyte_r2 AS _UNSIGNED _BYTE
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vuinteger_min AS _UNSIGNED INTEGER
DIM vuinteger_max AS _UNSIGNED INTEGER
DIM vuinteger_m1 AS _UNSIGNED INTEGER
DIM vuinteger_zero AS _UNSIGNED INTEGER
DIM vuinteger_one AS _UNSIGNED INTEGER
DIM vuinteger_r1 AS _UNSIGNED INTEGER
DIM vuinteger_r2 AS _UNSIGNED INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vulong_min AS _UNSIGNED LONG
DIM vulong_max AS _UNSIGNED LONG
DIM vulong_m1 AS _UNSIGNED LONG
DIM vulong_zero AS _UNSIGNED LONG
DIM vulong_one AS _UNSIGNED LONG
DIM vulong_r1 AS _UNSIGNED LONG
DIM vulong_r2 AS _UNSIGNED LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vuint64_min AS _UNSIGNED _INTEGER64
DIM vuint64_max AS _UNSIGNED _INTEGER64
DIM vuint64_m1 AS _UNSIGNED _INTEGER64
DIM vuint64_zero AS _UNSIGNED _INTEGER64
DIM vuint64_one AS _UNSIGNED _INTEGER64
DIM vuint64_r1 AS _UNSIGNED _INTEGER64
DIM vuint64_r2 AS _UNSIGNED _INTEGER64
DIM voffset_min AS _OFFSET
DIM voffset_max AS _OFFSET
DIM voffset_m1 AS _OFFSET
DIM voffset_zero AS _OFFSET
DIM voffset_one AS _OFFSET
DIM voffset_r1 AS _OFFSET
DIM voffset_r2 AS _OFFSET
DIM vuoffset_min AS _UNSIGNED _OFFSET
DIM vuoffset_max AS _UNSIGNED _OFFSET
DIM vuoffset_m1 AS _UNSIGNED _OFFSET
DIM vuoffset_zero AS _UNSIGNED _OFFSET
DIM vuoffset_one AS _UNSIGNED _OFFSET
DIM vuoffset_r1 AS _UNSIGNED _OFFSET
DIM vuoffset_r2 AS _UNSIGNED _OFFSET
DIM vbit_min AS _BIT
DIM vbit_max AS _BIT
DIM vbit_m1 AS _BIT
DIM vbit_zero AS _BIT
DIM vbit_one AS _BIT
DIM vbit_r1 AS _BIT
DIM vbit_r2 AS _BIT
DIM vubit7_min AS _UNSIGNED _BIT * 7
DIM vubit7_max AS _UNSIGNED _BIT * 7
DIM vubit7_m1 AS _UNSIGNED _BIT * 7
DIM vubit7_zero AS _UNSIGNED _BIT * 7
DIM vubit7_one AS _UNSIGNED _BIT * 7
DIM vubit7_r1 AS _UNSIGNED _BIT * 7
DIM vubit7_r2 AS _UNSIGNED _BIT * 7
DIM vbit24_min AS _BIT * 24
DIM vbit24_max AS _BIT * 24
DIM vbit24_m1 AS _BIT * 24
DIM vbit24_zero AS _BIT * 24
DIM vbit24_one AS _BIT * 24
DIM vbit24_r1 AS _BIT * 24
DIM vbit24_r2 AS _BIT * 24
DIM pad_vubit40_min AS _BIT * 32
DIM vubit40_min AS _UNSIGNED _BIT * 40
DIM pad_vubit40_max AS _BIT * 32
DIM vubit40_max AS _UNSIGNED _BIT * 40
DIM pad_vubit40_m1 AS _BIT * 32
DIM vubit40_m1 AS _UNSIGNED _BIT * 40
DIM pad_vubit40_zero AS _BIT * 32
DIM vubit40_zero AS _UNSIGNED _BIT * 40
DIM pad_vubit40_one AS _BIT * 32
DIM vubit40_one AS _UNSIGNED _BIT * 40
DIM pad_vubit40_r1 AS _BIT * 32
DIM vubit40_r1 AS _UNSIGNED _BIT * 40
DIM pad_vubit40_r2 AS _BIT * 32
DIM vubit40_r2 AS _UNSIGNED _BIT * 40
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vbyte_min = -128%%
vbyte_max = 127%%
vbyte_m1 = -1%%
vbyte_zero = 0%%
vbyte_one = 1%%
vbyte_r1 = 103%%
vbyte_r2 = -56%%
vubyte_min = 0~%%
vubyte_max = 255~%%
vubyte_m1 = 255~%%
vubyte_zero = 0~%%
vubyte_one = 1~%%
vubyte_r1 = 32~%%
vubyte_r2 = 20~%%
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vuinteger_min = 0~%
vuinteger_max = 65535~%
vuinteger_m1 = 65535~%
vuinteger_zero = 0~%
vuinteger_one = 1~%
vuinteger_r1 = 36936~%
vuinteger_r2 = 38734~%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vulong_min = 0~&
vulong_max = 4294967295~&
vulong_m1 = 4294967295~&
vulong_zero = 0~&
vulong_one = 1~&
vulong_r1 = 3095748532~&
vulong_r2 = 2247239029~&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vuint64_min = 0~&&
vuint64_max = 18446744073709551615~&&
vuint64_m1 = 18446744073709551615~&&
vuint64_zero = 0~&&
vuint64_one = 1~&&
vuint64_r1 = 14721352250261409079~&&
vuint64_r2 = 1695248715451867090~&&
voffset_min = (-9223372036854775807&& - 1)
voffset_max = 9223372036854775807&&
voffset_m1 = -1&&
voffset_zero = 0&&
voffset_one = 1&&
voffset_r1 = 1887714948171717615&&
voffset_r2 = -4592622012093347915&&
vuoffset_min = 0~&&
vuoffset_max = 18446744073709551615~&&
vuoffset_m1 = 18446744073709551615~&&
vuoffset_zero = 0~&&
vuoffset_one = 1~&&
vuoffset_r1 = 15919602987562150171~&&
vuoffset_r2 = 16266618817563032314~&&
vbit_min = -1`
vbit_max = 0`
vbit_m1 = -1`
vbit_zero = 0`
vbit_one = 0`
vbit_r1 = 0`
vbit_r2 = -1`
vubit7_min = 0~`7
vubit7_max = 127~`7
vubit7_m1 = 127~`7
vubit7_zero = 0~`7
vubit7_one = 1~`7
vubit7_r1 = 25~`7
vubit7_r2 = 74~`7
vbit24_min = -8388608`24
vbit24_max = 8388607`24
vbit24_m1 = -1`24
vbit24_zero = 0`24
vbit24_one = 1`24
vbit24_r1 = 3148653`24
vbit24_r2 = -2716775`24
vubit40_min = 0~`40
vubit40_max = 1099511627775~`40
vubit40_m1 = 1099511627775~`40
vubit40_zero = 0~`40
vubit40_one = 1~`40
vubit40_r1 = 464297847704~`40
vubit40_r2 = 488476189167~`40
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "PRINT BYTE min:"; vbyte_min
PRINT "STR$ BYTE min:"; STR$(vbyte_min)
PRINT "PRINT BYTE max:"; vbyte_max
PRINT "STR$ BYTE max:"; STR$(vbyte_max)
PRINT "PRINT BYTE m1:"; vbyte_m1
PRINT "STR$ BYTE m1:"; STR$(vbyte_m1)
PRINT "PRINT BYTE zero:"; vbyte_zero
PRINT "STR$ BYTE zero:"; STR$(vbyte_zero)
PRINT "PRINT BYTE one:"; vbyte_one
PRINT "STR$ BYTE one:"; STR$(vbyte_one)
PRINT "PRINT BYTE r1:"; vbyte_r1
PRINT "STR$ BYTE r1:"; STR$(vbyte_r1)
PRINT "PRINT BYTE r2:"; vbyte_r2
PRINT "STR$ BYTE r2:"; STR$(vbyte_r2)
PRINT "PRINT UBYTE min:"; vubyte_min
PRINT "STR$ UBYTE min:"; STR$(vubyte_min)
PRINT "PRINT UBYTE max:"; vubyte_max
PRINT "STR$ UBYTE max:"; STR$(vubyte_max)
PRINT "PRINT UBYTE m1:"; vubyte_m1
PRINT "STR$ UBYTE m1:"; STR$(vubyte_m1)
PRINT "PRINT UBYTE zero:"; vubyte_zero
PRINT "STR$ UBYTE zero:"; STR$(vubyte_zero)
PRINT "PRINT UBYTE one:"; vubyte_one
PRINT "STR$ UBYTE one:"; STR$(vubyte_one)
PRINT "PRINT UBYTE r1:"; vubyte_r1
PRINT "STR$ UBYTE r1:"; STR$(vubyte_r1)
PRINT "PRINT UBYTE r2:"; vubyte_r2
PRINT "STR$ UBYTE r2:"; STR$(vubyte_r2)
PRINT "PRINT INTEGER min:"; vinteger_min
PRINT "STR$ INTEGER min:"; STR$(vinteger_min)
PRINT "PRINT INTEGER max:"; vinteger_max
PRINT "STR$ INTEGER max:"; STR$(vinteger_max)
PRINT "PRINT INTEGER m1:"; vinteger_m1
PRINT "STR$ INTEGER m1:"; STR$(vinteger_m1)
PRINT "PRINT INTEGER zero:"; vinteger_zero
PRINT "STR$ INTEGER zero:"; STR$(vinteger_zero)
PRINT "PRINT INTEGER one:"; vinteger_one
PRINT "STR$ INTEGER one:"; STR$(vinteger_one)
PRINT "PRINT INTEGER r1:"; vinteger_r1
PRINT "STR$ INTEGER r1:"; STR$(vinteger_r1)
PRINT "PRINT INTEGER r2:"; vinteger_r2
PRINT "STR$ INTEGER r2:"; STR$(vinteger_r2)
PRINT "PRINT UINTEGER min:"; vuinteger_min
PRINT "STR$ UINTEGER min:"; STR$(vuinteger_min)
PRINT "PRINT UINTEGER max:"; vuinteger_max
PRINT "STR$ UINTEGER max:"; STR$(vuinteger_max)
PRINT "PRINT UINTEGER m1:"; vuinteger_m1
PRINT "STR$ UINTEGER m1:"; STR$(vuinteger_m1)
PRINT "PRINT UINTEGER zero:"; vuinteger_zero
PRINT "STR$ UINTEGER zero:"; STR$(vuinteger_zero)
PRINT "PRINT UINTEGER one:"; vuinteger_one
PRINT "STR$ UINTEGER one:"; STR$(vuinteger_one)
PRINT "PRINT UINTEGER r1:"; vuinteger_r1
PRINT "STR$ UINTEGER r1:"; STR$(vuinteger_r1)
PRINT "PRINT UINTEGER r2:"; vuinteger_r2
PRINT "STR$ UINTEGER r2:"; STR$(vuinteger_r2)
PRINT "PRINT LONG min:"; vlong_min
PRINT "STR$ LONG min:"; STR$(vlong_min)
PRINT "PRINT LONG max:"; vlong_max
PRINT "STR$ LONG max:"; STR$(vlong_max)
PRINT "PRINT LONG m1:"; vlong_m1
PRINT "STR$ LONG m1:"; STR$(vlong_m1)
PRINT "PRINT LONG zero:"; vlong_zero
PRINT "STR$ LONG zero:"; STR$(vlong_zero)
PRINT "PRINT LONG one:"; vlong_one
PRINT "STR$ LONG one:"; STR$(vlong_one)
PRINT "PRINT LONG r1:"; vlong_r1
PRINT "STR$ LONG r1:"; STR$(vlong_r1)
PRINT "PRINT LONG r2:"; vlong_r2
PRINT "STR$ LONG r2:"; STR$(vlong_r2)
PRINT "PRINT ULONG min:"; vulong_min
PRINT "STR$ ULONG min:"; STR$(vulong_min)
PRINT "PRINT ULONG max:"; vulong_max
PRINT "STR$ ULONG max:"; STR$(vulong_max)
PRINT "PRINT ULONG m1:"; vulong_m1
PRINT "STR$ ULONG m1:"; STR$(vulong_m1)
PRINT "PRINT ULONG zero:"; vulong_zero
PRINT "STR$ ULONG zero:"; STR$(vulong_zero)
PRINT "PRINT ULONG one:"; vulong_one
PRINT "STR$ ULONG one:"; STR$(vulong_one)
PRINT "PRINT ULONG r1:"; vulong_r1
PRINT "STR$ ULONG r1:"; STR$(vulong_r1)
PRINT "PRINT ULONG r2:"; vulong_r2
PRINT "STR$ ULONG r2:"; STR$(vulong_r2)
PRINT "PRINT INT64 min:"; vint64_min
PRINT "STR$ INT64 min:"; STR$(vint64_min)
PRINT "PRINT INT64 max:"; vint64_max
PRINT "STR$ INT64 max:"; STR$(vint64_max)
PRINT "PRINT INT64 m1:"; vint64_m1
PRINT "STR$ INT64 m1:"; STR$(vint64_m1)
PRINT "PRINT INT64 zero:"; vint64_zero
PRINT "STR$ INT64 zero:"; STR$(vint64_zero)
PRINT "PRINT INT64 one:"; vint64_one
PRINT "STR$ INT64 one:"; STR$(vint64_one)
PRINT "PRINT INT64 r1:"; vint64_r1
PRINT "STR$ INT64 r1:"; STR$(vint64_r1)
PRINT "PRINT INT64 r2:"; vint64_r2
PRINT "STR$ INT64 r2:"; STR$(vint64_r2)
PRINT "PRINT UINT64 min:"; vuint64_min
PRINT "STR$ UINT64 min:"; STR$(vuint64_min)
PRINT "PRINT UINT64 max:"; vuint64_max
PRINT "STR$ UINT64 max:"; STR$(vuint64_max)
PRINT "PRINT UINT64 m1:"; vuint64_m1
PRINT "STR$ UINT64 m1:"; STR$(vuint64_m1)
PRINT "PRINT UINT64 zero:"; vuint64_zero
PRINT "STR$ UINT64 zero:"; STR$(vuint64_zero)
PRINT "PRINT UINT64 one:"; vuint64_one
PRINT "STR$ UINT64 one:"; STR$(vuint64_one)
PRINT "PRINT UINT64 r1:"; vuint64_r1
PRINT "STR$ UINT64 r1:"; STR$(vuint64_r1)
PRINT "PRINT UINT64 r2:"; vuint64_r2
PRINT "STR$ UINT64 r2:"; STR$(vuint64_r2)
PRINT "PRINT OFFSET min:"; voffset_min
PRINT "STR$ OFFSET min:"; STR$(voffset_min)
PRINT "PRINT OFFSET max:"; voffset_max
PRINT "STR$ OFFSET max:"; STR$(voffset_max)
PRINT "PRINT OFFSET m1:"; voffset_m1
PRINT "STR$ OFFSET m1:"; STR$(voffset_m1)
PRINT "PRINT OFFSET zero:"; voffset_zero
PRINT "STR$ OFFSET zero:"; STR$(voffset_zero)
PRINT "PRINT OFFSET one:"; voffset_one
PRINT "STR$ OFFSET one:"; STR$(voffset_one)
PRINT "PRINT OFFSET r1:"; voffset_r1
PRINT "STR$ OFFSET r1:"; STR$(voffset_r1)
PRINT "PRINT OFFSET r2:"; voffset_r2
PRINT "STR$ OFFSET r2:"; STR$(voffset_r2)
PRINT "PRINT UOFFSET min:"; vuoffset_min
PRINT "STR$ UOFFSET min:"; STR$(vuoffset_min)
PRINT "PRINT UOFFSET max:"; vuoffset_max
PRINT "STR$ UOFFSET max:"; STR$(vuoffset_max)
PRINT "PRINT UOFFSET m1:"; vuoffset_m1
PRINT "STR$ UOFFSET m1:"; STR$(vuoffset_m1)
PRINT "PRINT UOFFSET zero:"; vuoffset_zero
PRINT "STR$ UOFFSET zero:"; STR$(vuoffset_zero)
PRINT "PRINT UOFFSET one:"; vuoffset_one
PRINT "STR$ UOFFSET one:"; STR$(vuoffset_one)
PRINT "PRINT UOFFSET r1:"; vuoffset_r1
PRINT "STR$ UOFFSET r1:"; STR$(vuoffset_r1)
PRINT "PRINT UOFFSET r2:"; vuoffset_r2
PRINT "STR$ UOFFSET r2:"; STR$(vuoffset_r2)
PRINT "PRINT BIT min:"; vbit_min
PRINT "STR$ BIT min:"; STR$(vbit_min)
PRINT "PRINT BIT max:"; vbit_max
PRINT "STR$ BIT max:"; STR$(vbit_max)
PRINT "PRINT BIT m1:"; vbit_m1
PRINT "STR$ BIT m1:"; STR$(vbit_m1)
PRINT "PRINT BIT zero:"; vbit_zero
PRINT "STR$ BIT zero:"; STR$(vbit_zero)
PRINT "PRINT BIT one:"; vbit_one
PRINT "STR$ BIT one:"; STR$(vbit_one)
PRINT "PRINT BIT r1:"; vbit_r1
PRINT "STR$ BIT r1:"; STR$(vbit_r1)
PRINT "PRINT BIT r2:"; vbit_r2
PRINT "STR$ BIT r2:"; STR$(vbit_r2)
PRINT "PRINT UBIT7 min:"; vubit7_min
PRINT "STR$ UBIT7 min:"; STR$(vubit7_min)
PRINT "PRINT UBIT7 max:"; vubit7_max
PRINT "STR$ UBIT7 max:"; STR$(vubit7_max)
PRINT "PRINT UBIT7 m1:"; vubit7_m1
PRINT "STR$ UBIT7 m1:"; STR$(vubit7_m1)
PRINT "PRINT UBIT7 zero:"; vubit7_zero
PRINT "STR$ UBIT7 zero:"; STR$(vubit7_zero)
PRINT "PRINT UBIT7 one:"; vubit7_one
PRINT "STR$ UBIT7 one:"; STR$(vubit7_one)
PRINT "PRINT UBIT7 r1:"; vubit7_r1
PRINT "STR$ UBIT7 r1:"; STR$(vubit7_r1)
PRINT "PRINT UBIT7 r2:"; vubit7_r2
PRINT "STR$ UBIT7 r2:"; STR$(vubit7_r2)
PRINT "PRINT BIT24 min:"; vbit24_min
PRINT "STR$ BIT24 min:"; STR$(vbit24_min)
PRINT "PRINT BIT24 max:"; vbit24_max
PRINT "STR$ BIT24 max:"; STR$(vbit24_max)
PRINT "PRINT BIT24 m1:"; vbit24_m1
PRINT "STR$ BIT24 m1:"; STR$(vbit24_m1)
PRINT "PRINT BIT24 zero:"; vbit24_zero
PRINT "STR$ BIT24 zero:"; STR$(vbit24_zero)
PRINT "PRINT BIT24 one:"; vbit24_one
PRINT "STR$ BIT24 one:"; STR$(vbit24_one)
PRINT "PRINT BIT24 r1:"; vbit24_r1
PRINT "STR$ BIT24 r1:"; STR$(vbit24_r1)
PRINT "PRINT BIT24 r2:"; vbit24_r2
PRINT "STR$ BIT24 r2:"; STR$(vbit24_r2)
PRINT "PRINT UBIT40 min:"; vubit40_min
PRINT "STR$ UBIT40 min:"; STR$(vubit40_min)
PRINT "PRINT UBIT40 max:"; vubit40_max
PRINT "STR$ UBIT40 max:"; STR$(vubit40_max)
PRINT "PRINT UBIT40 m1:"; vubit40_m1
PRINT "STR$ UBIT40 m1:"; STR$(vubit40_m1)
PRINT "PRINT UBIT40 zero:"; vubit40_zero
PRINT "STR$ UBIT40 zero:"; STR$(vubit40_zero)
PRINT "PRINT UBIT40 one:"; vubit40_one
PRINT "STR$ UBIT40 one:"; STR$(vubit40_one)
PRINT "PRINT UBIT40 r1:"; vubit40_r1
PRINT "STR$ UBIT40 r1:"; STR$(vubit40_r1)
PRINT "PRINT UBIT40 r2:"; vubit40_r2
PRINT "STR$ UBIT40 r2:"; STR$(vubit40_r2)
PRINT "PRINT SINGLE min:"; vsingle_min
PRINT "STR$ SINGLE min:"; STR$(vsingle_min)
PRINT "PRINT SINGLE max:"; vsingle_max
PRINT "STR$ SINGLE max:"; STR$(vsingle_max)
PRINT "PRINT SINGLE m1:"; vsingle_m1
PRINT "STR$ SINGLE m1:"; STR$(vsingle_m1)
PRINT "PRINT SINGLE zero:"; vsingle_zero
PRINT "STR$ SINGLE zero:"; STR$(vsingle_zero)
PRINT "PRINT SINGLE one:"; vsingle_one
PRINT "STR$ SINGLE one:"; STR$(vsingle_one)
PRINT "PRINT SINGLE r1:"; vsingle_r1
PRINT "STR$ SINGLE r1:"; STR$(vsingle_r1)
PRINT "PRINT SINGLE r2:"; vsingle_r2
PRINT "STR$ SINGLE r2:"; STR$(vsingle_r2)
PRINT "PRINT DOUBLE min:"; vdouble_min
PRINT "STR$ DOUBLE min:"; STR$(vdouble_min)
PRINT "PRINT DOUBLE max:"; vdouble_max
PRINT "STR$ DOUBLE max:"; STR$(vdouble_max)
PRINT "PRINT DOUBLE m1:"; vdouble_m1
PRINT "STR$ DOUBLE m1:"; STR$(vdouble_m1)
PRINT "PRINT DOUBLE zero:"; vdouble_zero
PRINT "STR$ DOUBLE zero:"; STR$(vdouble_zero)
PRINT "PRINT DOUBLE one:"; vdouble_one
PRINT "STR$ DOUBLE one:"; STR$(vdouble_one)
PRINT "PRINT DOUBLE r1:"; vdouble_r1
PRINT "STR$ DOUBLE r1:"; STR$(vdouble_r1)
PRINT "PRINT DOUBLE r2:"; vdouble_r2
PRINT "STR$ DOUBLE r2:"; STR$(vdouble_r2)
PRINT "PRINT FLOAT min:"; vfloat_min
PRINT "STR$ FLOAT min:"; STR$(vfloat_min)
PRINT "PRINT FLOAT max:"; vfloat_max
PRINT "STR$ FLOAT max:"; STR$(vfloat_max)
PRINT "PRINT FLOAT m1:"; vfloat_m1
PRINT "STR$ FLOAT m1:"; STR$(vfloat_m1)
PRINT "PRINT FLOAT zero:"; vfloat_zero
PRINT "STR$ FLOAT zero:"; STR$(vfloat_zero)
PRINT "PRINT FLOAT one:"; vfloat_one
PRINT "STR$ FLOAT one:"; STR$(vfloat_one)
PRINT "PRINT FLOAT r1:"; vfloat_r1
PRINT "STR$ FLOAT r1:"; STR$(vfloat_r1)
PRINT "PRINT FLOAT r2:"; vfloat_r2
PRINT "STR$ FLOAT r2:"; STR$(vfloat_r2)
PRINT "PRINT literal BYTE min:"; -128%%
PRINT "STR$ literal BYTE min:"; STR$(-128%%)
PRINT "PRINT literal BYTE max:"; 127%%
PRINT "STR$ literal BYTE max:"; STR$(127%%)
PRINT "PRINT literal BYTE m1:"; -1%%
PRINT "STR$ literal BYTE m1:"; STR$(-1%%)
PRINT "PRINT literal BYTE zero:"; 0%%
PRINT "STR$ literal BYTE zero:"; STR$(0%%)
PRINT "PRINT literal BYTE one:"; 1%%
PRINT "STR$ literal BYTE one:"; STR$(1%%)
PRINT "PRINT literal BYTE r1:"; 103%%
PRINT "STR$ literal BYTE r1:"; STR$(103%%)
PRINT "PRINT literal BYTE r2:"; -56%%
PRINT "STR$ literal BYTE r2:"; STR$(-56%%)
PRINT "PRINT literal BYTE below:"; -129%%
PRINT "STR$ literal BYTE below:"; STR$(-129%%)
PRINT "PRINT literal BYTE above:"; 128%%
PRINT "STR$ literal BYTE above:"; STR$(128%%)
PRINT "PRINT literal UBYTE min:"; 0~%%
PRINT "STR$ literal UBYTE min:"; STR$(0~%%)
PRINT "PRINT literal UBYTE max:"; 255~%%
PRINT "STR$ literal UBYTE max:"; STR$(255~%%)
PRINT "PRINT literal UBYTE m1:"; 255~%%
PRINT "STR$ literal UBYTE m1:"; STR$(255~%%)
PRINT "PRINT literal UBYTE zero:"; 0~%%
PRINT "STR$ literal UBYTE zero:"; STR$(0~%%)
PRINT "PRINT literal UBYTE one:"; 1~%%
PRINT "STR$ literal UBYTE one:"; STR$(1~%%)
PRINT "PRINT literal UBYTE r1:"; 32~%%
PRINT "STR$ literal UBYTE r1:"; STR$(32~%%)
PRINT "PRINT literal UBYTE r2:"; 20~%%
PRINT "STR$ literal UBYTE r2:"; STR$(20~%%)
PRINT "PRINT literal UBYTE below:"; -1~%%
PRINT "STR$ literal UBYTE below:"; STR$(-1~%%)
PRINT "PRINT literal UBYTE above:"; 256~%%
PRINT "STR$ literal UBYTE above:"; STR$(256~%%)
PRINT "PRINT literal INTEGER min:"; -32768%
PRINT "STR$ literal INTEGER min:"; STR$(-32768%)
PRINT "PRINT literal INTEGER max:"; 32767%
PRINT "STR$ literal INTEGER max:"; STR$(32767%)
PRINT "PRINT literal INTEGER m1:"; -1%
PRINT "STR$ literal INTEGER m1:"; STR$(-1%)
PRINT "PRINT literal INTEGER zero:"; 0%
PRINT "STR$ literal INTEGER zero:"; STR$(0%)
PRINT "PRINT literal INTEGER one:"; 1%
PRINT "STR$ literal INTEGER one:"; STR$(1%)
PRINT "PRINT literal INTEGER r1:"; -2895%
PRINT "STR$ literal INTEGER r1:"; STR$(-2895%)
PRINT "PRINT literal INTEGER r2:"; 5580%
PRINT "STR$ literal INTEGER r2:"; STR$(5580%)
PRINT "PRINT literal INTEGER below:"; -32769%
PRINT "STR$ literal INTEGER below:"; STR$(-32769%)
PRINT "PRINT literal INTEGER above:"; 32768%
PRINT "STR$ literal INTEGER above:"; STR$(32768%)
PRINT "PRINT literal UINTEGER min:"; 0~%
PRINT "STR$ literal UINTEGER min:"; STR$(0~%)
PRINT "PRINT literal UINTEGER max:"; 65535~%
PRINT "STR$ literal UINTEGER max:"; STR$(65535~%)
PRINT "PRINT literal UINTEGER m1:"; 65535~%
PRINT "STR$ literal UINTEGER m1:"; STR$(65535~%)
PRINT "PRINT literal UINTEGER zero:"; 0~%
PRINT "STR$ literal UINTEGER zero:"; STR$(0~%)
PRINT "PRINT literal UINTEGER one:"; 1~%
PRINT "STR$ literal UINTEGER one:"; STR$(1~%)
PRINT "PRINT literal UINTEGER r1:"; 36936~%
PRINT "STR$ literal UINTEGER r1:"; STR$(36936~%)
PRINT "PRINT literal UINTEGER r2:"; 38734~%
PRINT "STR$ literal UINTEGER r2:"; STR$(38734~%)
PRINT "PRINT literal UINTEGER below:"; -1~%
PRINT "STR$ literal UINTEGER below:"; STR$(-1~%)
PRINT "PRINT literal UINTEGER above:"; 65536~%
PRINT "STR$ literal UINTEGER above:"; STR$(65536~%)
PRINT "PRINT literal LONG min:"; -2147483648&
PRINT "STR$ literal LONG min:"; STR$(-2147483648&)
PRINT "PRINT literal LONG max:"; 2147483647&
PRINT "STR$ literal LONG max:"; STR$(2147483647&)
PRINT "PRINT literal LONG m1:"; -1&
PRINT "STR$ literal LONG m1:"; STR$(-1&)
PRINT "PRINT literal LONG zero:"; 0&
PRINT "STR$ literal LONG zero:"; STR$(0&)
PRINT "PRINT literal LONG one:"; 1&
PRINT "STR$ literal LONG one:"; STR$(1&)
PRINT "PRINT literal LONG r1:"; -559627433&
PRINT "STR$ literal LONG r1:"; STR$(-559627433&)
PRINT "PRINT literal LONG r2:"; -709606431&
PRINT "STR$ literal LONG r2:"; STR$(-709606431&)
PRINT "PRINT literal LONG below:"; -2147483649&
PRINT "STR$ literal LONG below:"; STR$(-2147483649&)
PRINT "PRINT literal LONG above:"; 2147483648&
PRINT "STR$ literal LONG above:"; STR$(2147483648&)
PRINT "PRINT literal ULONG min:"; 0~&
PRINT "STR$ literal ULONG min:"; STR$(0~&)
PRINT "PRINT literal ULONG max:"; 4294967295~&
PRINT "STR$ literal ULONG max:"; STR$(4294967295~&)
PRINT "PRINT literal ULONG m1:"; 4294967295~&
PRINT "STR$ literal ULONG m1:"; STR$(4294967295~&)
PRINT "PRINT literal ULONG zero:"; 0~&
PRINT "STR$ literal ULONG zero:"; STR$(0~&)
PRINT "PRINT literal ULONG one:"; 1~&
PRINT "STR$ literal ULONG one:"; STR$(1~&)
PRINT "PRINT literal ULONG r1:"; 3095748532~&
PRINT "STR$ literal ULONG r1:"; STR$(3095748532~&)
PRINT "PRINT literal ULONG r2:"; 2247239029~&
PRINT "STR$ literal ULONG r2:"; STR$(2247239029~&)
PRINT "PRINT literal ULONG below:"; -1~&
PRINT "STR$ literal ULONG below:"; STR$(-1~&)
PRINT "PRINT literal ULONG above:"; 4294967296~&
PRINT "STR$ literal ULONG above:"; STR$(4294967296~&)
PRINT "PRINT literal INT64 min:"; (-9223372036854775807&& - 1)
PRINT "STR$ literal INT64 min:"; STR$((-9223372036854775807&& - 1))
PRINT "PRINT literal INT64 max:"; 9223372036854775807&&
PRINT "STR$ literal INT64 max:"; STR$(9223372036854775807&&)
PRINT "PRINT literal INT64 m1:"; -1&&
PRINT "STR$ literal INT64 m1:"; STR$(-1&&)
PRINT "PRINT literal INT64 zero:"; 0&&
PRINT "STR$ literal INT64 zero:"; STR$(0&&)
PRINT "PRINT literal INT64 one:"; 1&&
PRINT "STR$ literal INT64 one:"; STR$(1&&)
PRINT "PRINT literal INT64 r1:"; 5819978767338316436&&
PRINT "STR$ literal INT64 r1:"; STR$(5819978767338316436&&)
PRINT "PRINT literal INT64 r2:"; 7445081360591965601&&
PRINT "STR$ literal INT64 r2:"; STR$(7445081360591965601&&)
PRINT "PRINT literal UINT64 min:"; 0~&&
PRINT "STR$ literal UINT64 min:"; STR$(0~&&)
PRINT "PRINT literal UINT64 max:"; 18446744073709551615~&&
PRINT "STR$ literal UINT64 max:"; STR$(18446744073709551615~&&)
PRINT "PRINT literal UINT64 m1:"; 18446744073709551615~&&
PRINT "STR$ literal UINT64 m1:"; STR$(18446744073709551615~&&)
PRINT "PRINT literal UINT64 zero:"; 0~&&
PRINT "STR$ literal UINT64 zero:"; STR$(0~&&)
PRINT "PRINT literal UINT64 one:"; 1~&&
PRINT "STR$ literal UINT64 one:"; STR$(1~&&)
PRINT "PRINT literal UINT64 r1:"; 14721352250261409079~&&
PRINT "STR$ literal UINT64 r1:"; STR$(14721352250261409079~&&)
PRINT "PRINT literal UINT64 r2:"; 1695248715451867090~&&
PRINT "STR$ literal UINT64 r2:"; STR$(1695248715451867090~&&)
PRINT "PRINT literal BIT min:"; -1`
PRINT "STR$ literal BIT min:"; STR$(-1`)
PRINT "PRINT literal BIT max:"; 0`
PRINT "STR$ literal BIT max:"; STR$(0`)
PRINT "PRINT literal BIT m1:"; -1`
PRINT "STR$ literal BIT m1:"; STR$(-1`)
PRINT "PRINT literal BIT zero:"; 0`
PRINT "STR$ literal BIT zero:"; STR$(0`)
PRINT "PRINT literal BIT one:"; 0`
PRINT "STR$ literal BIT one:"; STR$(0`)
PRINT "PRINT literal BIT r1:"; 0`
PRINT "STR$ literal BIT r1:"; STR$(0`)
PRINT "PRINT literal BIT r2:"; -1`
PRINT "STR$ literal BIT r2:"; STR$(-1`)
PRINT "PRINT literal BIT below:"; -2`
PRINT "STR$ literal BIT below:"; STR$(-2`)
PRINT "PRINT literal BIT above:"; 1`
PRINT "STR$ literal BIT above:"; STR$(1`)
PRINT "PRINT literal UBIT7 min:"; 0~`7
PRINT "STR$ literal UBIT7 min:"; STR$(0~`7)
PRINT "PRINT literal UBIT7 max:"; 127~`7
PRINT "STR$ literal UBIT7 max:"; STR$(127~`7)
PRINT "PRINT literal UBIT7 m1:"; 127~`7
PRINT "STR$ literal UBIT7 m1:"; STR$(127~`7)
PRINT "PRINT literal UBIT7 zero:"; 0~`7
PRINT "STR$ literal UBIT7 zero:"; STR$(0~`7)
PRINT "PRINT literal UBIT7 one:"; 1~`7
PRINT "STR$ literal UBIT7 one:"; STR$(1~`7)
PRINT "PRINT literal UBIT7 r1:"; 25~`7
PRINT "STR$ literal UBIT7 r1:"; STR$(25~`7)
PRINT "PRINT literal UBIT7 r2:"; 74~`7
PRINT "STR$ literal UBIT7 r2:"; STR$(74~`7)
PRINT "PRINT literal UBIT7 below:"; -1~`7
PRINT "STR$ literal UBIT7 below:"; STR$(-1~`7)
PRINT "PRINT literal UBIT7 above:"; 128~`7
PRINT "STR$ literal UBIT7 above:"; STR$(128~`7)
PRINT "PRINT literal BIT24 min:"; -8388608`24
PRINT "STR$ literal BIT24 min:"; STR$(-8388608`24)
PRINT "PRINT literal BIT24 max:"; 8388607`24
PRINT "STR$ literal BIT24 max:"; STR$(8388607`24)
PRINT "PRINT literal BIT24 m1:"; -1`24
PRINT "STR$ literal BIT24 m1:"; STR$(-1`24)
PRINT "PRINT literal BIT24 zero:"; 0`24
PRINT "STR$ literal BIT24 zero:"; STR$(0`24)
PRINT "PRINT literal BIT24 one:"; 1`24
PRINT "STR$ literal BIT24 one:"; STR$(1`24)
PRINT "PRINT literal BIT24 r1:"; 3148653`24
PRINT "STR$ literal BIT24 r1:"; STR$(3148653`24)
PRINT "PRINT literal BIT24 r2:"; -2716775`24
PRINT "STR$ literal BIT24 r2:"; STR$(-2716775`24)
PRINT "PRINT literal BIT24 below:"; -8388609`24
PRINT "STR$ literal BIT24 below:"; STR$(-8388609`24)
PRINT "PRINT literal BIT24 above:"; 8388608`24
PRINT "STR$ literal BIT24 above:"; STR$(8388608`24)
PRINT "PRINT literal UBIT40 min:"; 0~`40
PRINT "STR$ literal UBIT40 min:"; STR$(0~`40)
PRINT "PRINT literal UBIT40 max:"; 1099511627775~`40
PRINT "STR$ literal UBIT40 max:"; STR$(1099511627775~`40)
PRINT "PRINT literal UBIT40 m1:"; 1099511627775~`40
PRINT "STR$ literal UBIT40 m1:"; STR$(1099511627775~`40)
PRINT "PRINT literal UBIT40 zero:"; 0~`40
PRINT "STR$ literal UBIT40 zero:"; STR$(0~`40)
PRINT "PRINT literal UBIT40 one:"; 1~`40
PRINT "STR$ literal UBIT40 one:"; STR$(1~`40)
PRINT "PRINT literal UBIT40 r1:"; 464297847704~`40
PRINT "STR$ literal UBIT40 r1:"; STR$(464297847704~`40)
PRINT "PRINT literal UBIT40 r2:"; 488476189167~`40
PRINT "STR$ literal UBIT40 r2:"; STR$(488476189167~`40)
PRINT "PRINT literal UBIT40 below:"; -1~`40
PRINT "STR$ literal UBIT40 below:"; STR$(-1~`40)
PRINT "PRINT literal UBIT40 above:"; 1099511627776~`40
PRINT "STR$ literal UBIT40 above:"; STR$(1099511627776~`40)
PRINT "PRINT literal SINGLE min:"; -3.402823E+38
PRINT "STR$ literal SINGLE min:"; STR$(-3.402823E+38)
PRINT "PRINT literal SINGLE max:"; 3.402823E+38
PRINT "STR$ literal SINGLE max:"; STR$(3.402823E+38)
PRINT "PRINT literal SINGLE m1:"; -1!
PRINT "STR$ literal SINGLE m1:"; STR$(-1!)
PRINT "PRINT literal SINGLE zero:"; 0!
PRINT "STR$ literal SINGLE zero:"; STR$(0!)
PRINT "PRINT literal SINGLE one:"; 1!
PRINT "STR$ literal SINGLE one:"; STR$(1!)
PRINT "PRINT literal SINGLE r1:"; 0.2!
PRINT "STR$ literal SINGLE r1:"; STR$(0.2!)
PRINT "PRINT literal SINGLE r2:"; -0.2253!
PRINT "STR$ literal SINGLE r2:"; STR$(-0.2253!)
PRINT "PRINT literal DOUBLE min:"; -1.797693134862315D+308
PRINT "STR$ literal DOUBLE min:"; STR$(-1.797693134862315D+308)
PRINT "PRINT literal DOUBLE max:"; 1.797693134862315D+308
PRINT "STR$ literal DOUBLE max:"; STR$(1.797693134862315D+308)
PRINT "PRINT literal DOUBLE m1:"; -1#
PRINT "STR$ literal DOUBLE m1:"; STR$(-1#)
PRINT "PRINT literal DOUBLE zero:"; 0#
PRINT "STR$ literal DOUBLE zero:"; STR$(0#)
PRINT "PRINT literal DOUBLE one:"; 1#
PRINT "STR$ literal DOUBLE one:"; STR$(1#)
PRINT "PRINT literal DOUBLE r1:"; -166203811.12578#
PRINT "STR$ literal DOUBLE r1:"; STR$(-166203811.12578#)
PRINT "PRINT literal DOUBLE r2:"; -12534.17#
PRINT "STR$ literal DOUBLE r2:"; STR$(-12534.17#)
PRINT "PRINT literal FLOAT min:"; -1.797693134862315F+308
PRINT "STR$ literal FLOAT min:"; STR$(-1.797693134862315F+308)
PRINT "PRINT literal FLOAT max:"; 1.797693134862315F+308
PRINT "STR$ literal FLOAT max:"; STR$(1.797693134862315F+308)
PRINT "PRINT literal FLOAT m1:"; -1##
PRINT "STR$ literal FLOAT m1:"; STR$(-1##)
PRINT "PRINT literal FLOAT zero:"; 0##
PRINT "STR$ literal FLOAT zero:"; STR$(0##)
PRINT "PRINT literal FLOAT one:"; 1##
PRINT "STR$ literal FLOAT one:"; STR$(1##)
PRINT "PRINT literal FLOAT r1:"; -0.90##
PRINT "STR$ literal FLOAT r1:"; STR$(-0.90##)
PRINT "PRINT literal FLOAT r2:"; 478.10157##
PRINT "STR$ literal FLOAT r2:"; STR$(478.10157##)
PRINT "PRINT literal FLOAT below:"; -1.18973149535723176F+4932
PRINT "STR$ literal FLOAT below:"; STR$(-1.18973149535723176F+4932)
PRINT "PRINT literal FLOAT above:"; 1.18973149535723176F+4932
PRINT "STR$ literal FLOAT above:"; STR$(1.18973149535723176F+4932)
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
