$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): IMP on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "IMP INTEGER INTEGER 1:"; vinteger_min IMP vinteger_min
PRINT "IMP INTEGER INTEGER 2:"; vinteger_max IMP vinteger_max
PRINT "IMP INTEGER INTEGER 3:"; vinteger_min IMP vinteger_max
PRINT "IMP INTEGER INTEGER 4:"; vinteger_max IMP vinteger_min
PRINT "IMP INTEGER INTEGER 5:"; vinteger_m1 IMP vinteger_one
PRINT "IMP INTEGER INTEGER 6:"; vinteger_zero IMP vinteger_one
PRINT "IMP INTEGER INTEGER 7:"; vinteger_r1 IMP vinteger_r2
PRINT "IMP INTEGER INTEGER 8:"; vinteger_r2 IMP vinteger_r1
PRINT "IMP INTEGER LONG 1:"; vinteger_min IMP vlong_min
PRINT "IMP INTEGER LONG 2:"; vinteger_max IMP vlong_max
PRINT "IMP INTEGER LONG 3:"; vinteger_min IMP vlong_max
PRINT "IMP INTEGER LONG 4:"; vinteger_max IMP vlong_min
PRINT "IMP INTEGER LONG 5:"; vinteger_m1 IMP vlong_one
PRINT "IMP INTEGER LONG 6:"; vinteger_zero IMP vlong_one
PRINT "IMP INTEGER LONG 7:"; vinteger_r1 IMP vlong_r2
PRINT "IMP INTEGER LONG 8:"; vinteger_r2 IMP vlong_r1
PRINT "IMP INTEGER INT64 1:"; vinteger_min IMP vint64_min
PRINT "IMP INTEGER INT64 2:"; vinteger_max IMP vint64_max
PRINT "IMP INTEGER INT64 3:"; vinteger_min IMP vint64_max
PRINT "IMP INTEGER INT64 4:"; vinteger_max IMP vint64_min
PRINT "IMP INTEGER INT64 5:"; vinteger_m1 IMP vint64_one
PRINT "IMP INTEGER INT64 6:"; vinteger_zero IMP vint64_one
PRINT "IMP INTEGER INT64 7:"; vinteger_r1 IMP vint64_r2
PRINT "IMP INTEGER INT64 8:"; vinteger_r2 IMP vint64_r1
PRINT "IMP INTEGER SINGLE 1:"; vinteger_min IMP vsingle_min
PRINT "IMP INTEGER SINGLE 2:"; vinteger_max IMP vsingle_max
PRINT "IMP INTEGER SINGLE 3:"; vinteger_min IMP vsingle_max
PRINT "IMP INTEGER SINGLE 4:"; vinteger_max IMP vsingle_min
PRINT "IMP INTEGER SINGLE 5:"; vinteger_m1 IMP vsingle_one
PRINT "IMP INTEGER SINGLE 6:"; vinteger_zero IMP vsingle_one
PRINT "IMP INTEGER SINGLE 7:"; vinteger_r1 IMP vsingle_r2
PRINT "IMP INTEGER SINGLE 8:"; vinteger_r2 IMP vsingle_r1
PRINT "IMP INTEGER DOUBLE 1:"; vinteger_min IMP vdouble_min
PRINT "IMP INTEGER DOUBLE 2:"; vinteger_max IMP vdouble_max
PRINT "IMP INTEGER DOUBLE 3:"; vinteger_min IMP vdouble_max
PRINT "IMP INTEGER DOUBLE 4:"; vinteger_max IMP vdouble_min
PRINT "IMP INTEGER DOUBLE 5:"; vinteger_m1 IMP vdouble_one
PRINT "IMP INTEGER DOUBLE 6:"; vinteger_zero IMP vdouble_one
PRINT "IMP INTEGER DOUBLE 7:"; vinteger_r1 IMP vdouble_r2
PRINT "IMP INTEGER DOUBLE 8:"; vinteger_r2 IMP vdouble_r1
PRINT "IMP INTEGER FLOAT 1:"; vinteger_min IMP vfloat_min
PRINT "IMP INTEGER FLOAT 2:"; vinteger_max IMP vfloat_max
PRINT "IMP INTEGER FLOAT 3:"; vinteger_min IMP vfloat_max
PRINT "IMP INTEGER FLOAT 4:"; vinteger_max IMP vfloat_min
PRINT "IMP INTEGER FLOAT 5:"; vinteger_m1 IMP vfloat_one
PRINT "IMP INTEGER FLOAT 6:"; vinteger_zero IMP vfloat_one
PRINT "IMP INTEGER FLOAT 7:"; vinteger_r1 IMP vfloat_r2
PRINT "IMP INTEGER FLOAT 8:"; vinteger_r2 IMP vfloat_r1
PRINT "IMP LONG INTEGER 1:"; vlong_min IMP vinteger_min
PRINT "IMP LONG INTEGER 2:"; vlong_max IMP vinteger_max
PRINT "IMP LONG INTEGER 3:"; vlong_min IMP vinteger_max
PRINT "IMP LONG INTEGER 4:"; vlong_max IMP vinteger_min
PRINT "IMP LONG INTEGER 5:"; vlong_m1 IMP vinteger_one
PRINT "IMP LONG INTEGER 6:"; vlong_zero IMP vinteger_one
PRINT "IMP LONG INTEGER 7:"; vlong_r1 IMP vinteger_r2
PRINT "IMP LONG INTEGER 8:"; vlong_r2 IMP vinteger_r1
PRINT "IMP LONG LONG 1:"; vlong_min IMP vlong_min
PRINT "IMP LONG LONG 2:"; vlong_max IMP vlong_max
PRINT "IMP LONG LONG 3:"; vlong_min IMP vlong_max
PRINT "IMP LONG LONG 4:"; vlong_max IMP vlong_min
PRINT "IMP LONG LONG 5:"; vlong_m1 IMP vlong_one
PRINT "IMP LONG LONG 6:"; vlong_zero IMP vlong_one
PRINT "IMP LONG LONG 7:"; vlong_r1 IMP vlong_r2
PRINT "IMP LONG LONG 8:"; vlong_r2 IMP vlong_r1
PRINT "IMP LONG INT64 1:"; vlong_min IMP vint64_min
PRINT "IMP LONG INT64 2:"; vlong_max IMP vint64_max
PRINT "IMP LONG INT64 3:"; vlong_min IMP vint64_max
PRINT "IMP LONG INT64 4:"; vlong_max IMP vint64_min
PRINT "IMP LONG INT64 5:"; vlong_m1 IMP vint64_one
PRINT "IMP LONG INT64 6:"; vlong_zero IMP vint64_one
PRINT "IMP LONG INT64 7:"; vlong_r1 IMP vint64_r2
PRINT "IMP LONG INT64 8:"; vlong_r2 IMP vint64_r1
PRINT "IMP LONG SINGLE 1:"; vlong_min IMP vsingle_min
PRINT "IMP LONG SINGLE 2:"; vlong_max IMP vsingle_max
PRINT "IMP LONG SINGLE 3:"; vlong_min IMP vsingle_max
PRINT "IMP LONG SINGLE 4:"; vlong_max IMP vsingle_min
PRINT "IMP LONG SINGLE 5:"; vlong_m1 IMP vsingle_one
PRINT "IMP LONG SINGLE 6:"; vlong_zero IMP vsingle_one
PRINT "IMP LONG SINGLE 7:"; vlong_r1 IMP vsingle_r2
PRINT "IMP LONG SINGLE 8:"; vlong_r2 IMP vsingle_r1
PRINT "IMP LONG DOUBLE 1:"; vlong_min IMP vdouble_min
PRINT "IMP LONG DOUBLE 2:"; vlong_max IMP vdouble_max
PRINT "IMP LONG DOUBLE 3:"; vlong_min IMP vdouble_max
PRINT "IMP LONG DOUBLE 4:"; vlong_max IMP vdouble_min
PRINT "IMP LONG DOUBLE 5:"; vlong_m1 IMP vdouble_one
PRINT "IMP LONG DOUBLE 6:"; vlong_zero IMP vdouble_one
PRINT "IMP LONG DOUBLE 7:"; vlong_r1 IMP vdouble_r2
PRINT "IMP LONG DOUBLE 8:"; vlong_r2 IMP vdouble_r1
PRINT "IMP LONG FLOAT 1:"; vlong_min IMP vfloat_min
PRINT "IMP LONG FLOAT 2:"; vlong_max IMP vfloat_max
PRINT "IMP LONG FLOAT 3:"; vlong_min IMP vfloat_max
PRINT "IMP LONG FLOAT 4:"; vlong_max IMP vfloat_min
PRINT "IMP LONG FLOAT 5:"; vlong_m1 IMP vfloat_one
PRINT "IMP LONG FLOAT 6:"; vlong_zero IMP vfloat_one
PRINT "IMP LONG FLOAT 7:"; vlong_r1 IMP vfloat_r2
PRINT "IMP LONG FLOAT 8:"; vlong_r2 IMP vfloat_r1
PRINT "IMP INT64 INTEGER 1:"; vint64_min IMP vinteger_min
PRINT "IMP INT64 INTEGER 2:"; vint64_max IMP vinteger_max
PRINT "IMP INT64 INTEGER 3:"; vint64_min IMP vinteger_max
PRINT "IMP INT64 INTEGER 4:"; vint64_max IMP vinteger_min
PRINT "IMP INT64 INTEGER 5:"; vint64_m1 IMP vinteger_one
PRINT "IMP INT64 INTEGER 6:"; vint64_zero IMP vinteger_one
PRINT "IMP INT64 INTEGER 7:"; vint64_r1 IMP vinteger_r2
PRINT "IMP INT64 INTEGER 8:"; vint64_r2 IMP vinteger_r1
PRINT "IMP INT64 LONG 1:"; vint64_min IMP vlong_min
PRINT "IMP INT64 LONG 2:"; vint64_max IMP vlong_max
PRINT "IMP INT64 LONG 3:"; vint64_min IMP vlong_max
PRINT "IMP INT64 LONG 4:"; vint64_max IMP vlong_min
PRINT "IMP INT64 LONG 5:"; vint64_m1 IMP vlong_one
PRINT "IMP INT64 LONG 6:"; vint64_zero IMP vlong_one
PRINT "IMP INT64 LONG 7:"; vint64_r1 IMP vlong_r2
PRINT "IMP INT64 LONG 8:"; vint64_r2 IMP vlong_r1
PRINT "IMP INT64 INT64 1:"; vint64_min IMP vint64_min
PRINT "IMP INT64 INT64 2:"; vint64_max IMP vint64_max
PRINT "IMP INT64 INT64 3:"; vint64_min IMP vint64_max
PRINT "IMP INT64 INT64 4:"; vint64_max IMP vint64_min
PRINT "IMP INT64 INT64 5:"; vint64_m1 IMP vint64_one
PRINT "IMP INT64 INT64 6:"; vint64_zero IMP vint64_one
PRINT "IMP INT64 INT64 7:"; vint64_r1 IMP vint64_r2
PRINT "IMP INT64 INT64 8:"; vint64_r2 IMP vint64_r1
PRINT "IMP INT64 SINGLE 1:"; vint64_min IMP vsingle_min
PRINT "IMP INT64 SINGLE 2:"; vint64_max IMP vsingle_max
PRINT "IMP INT64 SINGLE 3:"; vint64_min IMP vsingle_max
PRINT "IMP INT64 SINGLE 4:"; vint64_max IMP vsingle_min
PRINT "IMP INT64 SINGLE 5:"; vint64_m1 IMP vsingle_one
PRINT "IMP INT64 SINGLE 6:"; vint64_zero IMP vsingle_one
PRINT "IMP INT64 SINGLE 7:"; vint64_r1 IMP vsingle_r2
PRINT "IMP INT64 SINGLE 8:"; vint64_r2 IMP vsingle_r1
PRINT "IMP INT64 DOUBLE 1:"; vint64_min IMP vdouble_min
PRINT "IMP INT64 DOUBLE 2:"; vint64_max IMP vdouble_max
PRINT "IMP INT64 DOUBLE 3:"; vint64_min IMP vdouble_max
PRINT "IMP INT64 DOUBLE 4:"; vint64_max IMP vdouble_min
PRINT "IMP INT64 DOUBLE 5:"; vint64_m1 IMP vdouble_one
PRINT "IMP INT64 DOUBLE 6:"; vint64_zero IMP vdouble_one
PRINT "IMP INT64 DOUBLE 7:"; vint64_r1 IMP vdouble_r2
PRINT "IMP INT64 DOUBLE 8:"; vint64_r2 IMP vdouble_r1
PRINT "IMP INT64 FLOAT 1:"; vint64_min IMP vfloat_min
PRINT "IMP INT64 FLOAT 2:"; vint64_max IMP vfloat_max
PRINT "IMP INT64 FLOAT 3:"; vint64_min IMP vfloat_max
PRINT "IMP INT64 FLOAT 4:"; vint64_max IMP vfloat_min
PRINT "IMP INT64 FLOAT 5:"; vint64_m1 IMP vfloat_one
PRINT "IMP INT64 FLOAT 6:"; vint64_zero IMP vfloat_one
PRINT "IMP INT64 FLOAT 7:"; vint64_r1 IMP vfloat_r2
PRINT "IMP INT64 FLOAT 8:"; vint64_r2 IMP vfloat_r1
PRINT "IMP SINGLE INTEGER 1:"; vsingle_min IMP vinteger_min
PRINT "IMP SINGLE INTEGER 2:"; vsingle_max IMP vinteger_max
PRINT "IMP SINGLE INTEGER 3:"; vsingle_min IMP vinteger_max
PRINT "IMP SINGLE INTEGER 4:"; vsingle_max IMP vinteger_min
PRINT "IMP SINGLE INTEGER 5:"; vsingle_m1 IMP vinteger_one
PRINT "IMP SINGLE INTEGER 6:"; vsingle_zero IMP vinteger_one
PRINT "IMP SINGLE INTEGER 7:"; vsingle_r1 IMP vinteger_r2
PRINT "IMP SINGLE INTEGER 8:"; vsingle_r2 IMP vinteger_r1
PRINT "IMP SINGLE LONG 1:"; vsingle_min IMP vlong_min
PRINT "IMP SINGLE LONG 2:"; vsingle_max IMP vlong_max
PRINT "IMP SINGLE LONG 3:"; vsingle_min IMP vlong_max
PRINT "IMP SINGLE LONG 4:"; vsingle_max IMP vlong_min
PRINT "IMP SINGLE LONG 5:"; vsingle_m1 IMP vlong_one
PRINT "IMP SINGLE LONG 6:"; vsingle_zero IMP vlong_one
PRINT "IMP SINGLE LONG 7:"; vsingle_r1 IMP vlong_r2
PRINT "IMP SINGLE LONG 8:"; vsingle_r2 IMP vlong_r1
PRINT "IMP SINGLE INT64 1:"; vsingle_min IMP vint64_min
PRINT "IMP SINGLE INT64 2:"; vsingle_max IMP vint64_max
PRINT "IMP SINGLE INT64 3:"; vsingle_min IMP vint64_max
PRINT "IMP SINGLE INT64 4:"; vsingle_max IMP vint64_min
PRINT "IMP SINGLE INT64 5:"; vsingle_m1 IMP vint64_one
PRINT "IMP SINGLE INT64 6:"; vsingle_zero IMP vint64_one
PRINT "IMP SINGLE INT64 7:"; vsingle_r1 IMP vint64_r2
PRINT "IMP SINGLE INT64 8:"; vsingle_r2 IMP vint64_r1
PRINT "IMP SINGLE SINGLE 1:"; vsingle_min IMP vsingle_min
PRINT "IMP SINGLE SINGLE 2:"; vsingle_max IMP vsingle_max
PRINT "IMP SINGLE SINGLE 3:"; vsingle_min IMP vsingle_max
PRINT "IMP SINGLE SINGLE 4:"; vsingle_max IMP vsingle_min
PRINT "IMP SINGLE SINGLE 5:"; vsingle_m1 IMP vsingle_one
PRINT "IMP SINGLE SINGLE 6:"; vsingle_zero IMP vsingle_one
PRINT "IMP SINGLE SINGLE 7:"; vsingle_r1 IMP vsingle_r2
PRINT "IMP SINGLE SINGLE 8:"; vsingle_r2 IMP vsingle_r1
PRINT "IMP SINGLE DOUBLE 1:"; vsingle_min IMP vdouble_min
PRINT "IMP SINGLE DOUBLE 2:"; vsingle_max IMP vdouble_max
PRINT "IMP SINGLE DOUBLE 3:"; vsingle_min IMP vdouble_max
PRINT "IMP SINGLE DOUBLE 4:"; vsingle_max IMP vdouble_min
PRINT "IMP SINGLE DOUBLE 5:"; vsingle_m1 IMP vdouble_one
PRINT "IMP SINGLE DOUBLE 6:"; vsingle_zero IMP vdouble_one
PRINT "IMP SINGLE DOUBLE 7:"; vsingle_r1 IMP vdouble_r2
PRINT "IMP SINGLE DOUBLE 8:"; vsingle_r2 IMP vdouble_r1
PRINT "IMP SINGLE FLOAT 1:"; vsingle_min IMP vfloat_min
PRINT "IMP SINGLE FLOAT 2:"; vsingle_max IMP vfloat_max
PRINT "IMP SINGLE FLOAT 3:"; vsingle_min IMP vfloat_max
PRINT "IMP SINGLE FLOAT 4:"; vsingle_max IMP vfloat_min
PRINT "IMP SINGLE FLOAT 5:"; vsingle_m1 IMP vfloat_one
PRINT "IMP SINGLE FLOAT 6:"; vsingle_zero IMP vfloat_one
PRINT "IMP SINGLE FLOAT 7:"; vsingle_r1 IMP vfloat_r2
PRINT "IMP SINGLE FLOAT 8:"; vsingle_r2 IMP vfloat_r1
PRINT "IMP DOUBLE INTEGER 1:"; vdouble_min IMP vinteger_min
PRINT "IMP DOUBLE INTEGER 2:"; vdouble_max IMP vinteger_max
PRINT "IMP DOUBLE INTEGER 3:"; vdouble_min IMP vinteger_max
PRINT "IMP DOUBLE INTEGER 4:"; vdouble_max IMP vinteger_min
PRINT "IMP DOUBLE INTEGER 5:"; vdouble_m1 IMP vinteger_one
PRINT "IMP DOUBLE INTEGER 6:"; vdouble_zero IMP vinteger_one
PRINT "IMP DOUBLE INTEGER 7:"; vdouble_r1 IMP vinteger_r2
PRINT "IMP DOUBLE INTEGER 8:"; vdouble_r2 IMP vinteger_r1
PRINT "IMP DOUBLE LONG 1:"; vdouble_min IMP vlong_min
PRINT "IMP DOUBLE LONG 2:"; vdouble_max IMP vlong_max
PRINT "IMP DOUBLE LONG 3:"; vdouble_min IMP vlong_max
PRINT "IMP DOUBLE LONG 4:"; vdouble_max IMP vlong_min
PRINT "IMP DOUBLE LONG 5:"; vdouble_m1 IMP vlong_one
PRINT "IMP DOUBLE LONG 6:"; vdouble_zero IMP vlong_one
PRINT "IMP DOUBLE LONG 7:"; vdouble_r1 IMP vlong_r2
PRINT "IMP DOUBLE LONG 8:"; vdouble_r2 IMP vlong_r1
PRINT "IMP DOUBLE INT64 1:"; vdouble_min IMP vint64_min
PRINT "IMP DOUBLE INT64 2:"; vdouble_max IMP vint64_max
PRINT "IMP DOUBLE INT64 3:"; vdouble_min IMP vint64_max
PRINT "IMP DOUBLE INT64 4:"; vdouble_max IMP vint64_min
PRINT "IMP DOUBLE INT64 5:"; vdouble_m1 IMP vint64_one
PRINT "IMP DOUBLE INT64 6:"; vdouble_zero IMP vint64_one
PRINT "IMP DOUBLE INT64 7:"; vdouble_r1 IMP vint64_r2
PRINT "IMP DOUBLE INT64 8:"; vdouble_r2 IMP vint64_r1
PRINT "IMP DOUBLE SINGLE 1:"; vdouble_min IMP vsingle_min
PRINT "IMP DOUBLE SINGLE 2:"; vdouble_max IMP vsingle_max
PRINT "IMP DOUBLE SINGLE 3:"; vdouble_min IMP vsingle_max
PRINT "IMP DOUBLE SINGLE 4:"; vdouble_max IMP vsingle_min
PRINT "IMP DOUBLE SINGLE 5:"; vdouble_m1 IMP vsingle_one
PRINT "IMP DOUBLE SINGLE 6:"; vdouble_zero IMP vsingle_one
PRINT "IMP DOUBLE SINGLE 7:"; vdouble_r1 IMP vsingle_r2
PRINT "IMP DOUBLE SINGLE 8:"; vdouble_r2 IMP vsingle_r1
PRINT "IMP DOUBLE DOUBLE 1:"; vdouble_min IMP vdouble_min
PRINT "IMP DOUBLE DOUBLE 2:"; vdouble_max IMP vdouble_max
PRINT "IMP DOUBLE DOUBLE 3:"; vdouble_min IMP vdouble_max
PRINT "IMP DOUBLE DOUBLE 4:"; vdouble_max IMP vdouble_min
PRINT "IMP DOUBLE DOUBLE 5:"; vdouble_m1 IMP vdouble_one
PRINT "IMP DOUBLE DOUBLE 6:"; vdouble_zero IMP vdouble_one
PRINT "IMP DOUBLE DOUBLE 7:"; vdouble_r1 IMP vdouble_r2
PRINT "IMP DOUBLE DOUBLE 8:"; vdouble_r2 IMP vdouble_r1
PRINT "IMP DOUBLE FLOAT 1:"; vdouble_min IMP vfloat_min
PRINT "IMP DOUBLE FLOAT 2:"; vdouble_max IMP vfloat_max
PRINT "IMP DOUBLE FLOAT 3:"; vdouble_min IMP vfloat_max
PRINT "IMP DOUBLE FLOAT 4:"; vdouble_max IMP vfloat_min
PRINT "IMP DOUBLE FLOAT 5:"; vdouble_m1 IMP vfloat_one
PRINT "IMP DOUBLE FLOAT 6:"; vdouble_zero IMP vfloat_one
PRINT "IMP DOUBLE FLOAT 7:"; vdouble_r1 IMP vfloat_r2
PRINT "IMP DOUBLE FLOAT 8:"; vdouble_r2 IMP vfloat_r1
PRINT "IMP FLOAT INTEGER 1:"; vfloat_min IMP vinteger_min
PRINT "IMP FLOAT INTEGER 2:"; vfloat_max IMP vinteger_max
PRINT "IMP FLOAT INTEGER 3:"; vfloat_min IMP vinteger_max
PRINT "IMP FLOAT INTEGER 4:"; vfloat_max IMP vinteger_min
PRINT "IMP FLOAT INTEGER 5:"; vfloat_m1 IMP vinteger_one
PRINT "IMP FLOAT INTEGER 6:"; vfloat_zero IMP vinteger_one
PRINT "IMP FLOAT INTEGER 7:"; vfloat_r1 IMP vinteger_r2
PRINT "IMP FLOAT INTEGER 8:"; vfloat_r2 IMP vinteger_r1
PRINT "IMP FLOAT LONG 1:"; vfloat_min IMP vlong_min
PRINT "IMP FLOAT LONG 2:"; vfloat_max IMP vlong_max
PRINT "IMP FLOAT LONG 3:"; vfloat_min IMP vlong_max
PRINT "IMP FLOAT LONG 4:"; vfloat_max IMP vlong_min
PRINT "IMP FLOAT LONG 5:"; vfloat_m1 IMP vlong_one
PRINT "IMP FLOAT LONG 6:"; vfloat_zero IMP vlong_one
PRINT "IMP FLOAT LONG 7:"; vfloat_r1 IMP vlong_r2
PRINT "IMP FLOAT LONG 8:"; vfloat_r2 IMP vlong_r1
PRINT "IMP FLOAT INT64 1:"; vfloat_min IMP vint64_min
PRINT "IMP FLOAT INT64 2:"; vfloat_max IMP vint64_max
PRINT "IMP FLOAT INT64 3:"; vfloat_min IMP vint64_max
PRINT "IMP FLOAT INT64 4:"; vfloat_max IMP vint64_min
PRINT "IMP FLOAT INT64 5:"; vfloat_m1 IMP vint64_one
PRINT "IMP FLOAT INT64 6:"; vfloat_zero IMP vint64_one
PRINT "IMP FLOAT INT64 7:"; vfloat_r1 IMP vint64_r2
PRINT "IMP FLOAT INT64 8:"; vfloat_r2 IMP vint64_r1
PRINT "IMP FLOAT SINGLE 1:"; vfloat_min IMP vsingle_min
PRINT "IMP FLOAT SINGLE 2:"; vfloat_max IMP vsingle_max
PRINT "IMP FLOAT SINGLE 3:"; vfloat_min IMP vsingle_max
PRINT "IMP FLOAT SINGLE 4:"; vfloat_max IMP vsingle_min
PRINT "IMP FLOAT SINGLE 5:"; vfloat_m1 IMP vsingle_one
PRINT "IMP FLOAT SINGLE 6:"; vfloat_zero IMP vsingle_one
PRINT "IMP FLOAT SINGLE 7:"; vfloat_r1 IMP vsingle_r2
PRINT "IMP FLOAT SINGLE 8:"; vfloat_r2 IMP vsingle_r1
PRINT "IMP FLOAT DOUBLE 1:"; vfloat_min IMP vdouble_min
PRINT "IMP FLOAT DOUBLE 2:"; vfloat_max IMP vdouble_max
PRINT "IMP FLOAT DOUBLE 3:"; vfloat_min IMP vdouble_max
PRINT "IMP FLOAT DOUBLE 4:"; vfloat_max IMP vdouble_min
PRINT "IMP FLOAT DOUBLE 5:"; vfloat_m1 IMP vdouble_one
PRINT "IMP FLOAT DOUBLE 6:"; vfloat_zero IMP vdouble_one
PRINT "IMP FLOAT DOUBLE 7:"; vfloat_r1 IMP vdouble_r2
PRINT "IMP FLOAT DOUBLE 8:"; vfloat_r2 IMP vdouble_r1
PRINT "IMP FLOAT FLOAT 1:"; vfloat_min IMP vfloat_min
PRINT "IMP FLOAT FLOAT 2:"; vfloat_max IMP vfloat_max
PRINT "IMP FLOAT FLOAT 3:"; vfloat_min IMP vfloat_max
PRINT "IMP FLOAT FLOAT 4:"; vfloat_max IMP vfloat_min
PRINT "IMP FLOAT FLOAT 5:"; vfloat_m1 IMP vfloat_one
PRINT "IMP FLOAT FLOAT 6:"; vfloat_zero IMP vfloat_one
PRINT "IMP FLOAT FLOAT 7:"; vfloat_r1 IMP vfloat_r2
PRINT "IMP FLOAT FLOAT 8:"; vfloat_r2 IMP vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
