$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): XOR on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "XOR INTEGER INTEGER 1:"; vinteger_min XOR vinteger_min
PRINT "XOR INTEGER INTEGER 2:"; vinteger_max XOR vinteger_max
PRINT "XOR INTEGER INTEGER 3:"; vinteger_min XOR vinteger_max
PRINT "XOR INTEGER INTEGER 4:"; vinteger_max XOR vinteger_min
PRINT "XOR INTEGER INTEGER 5:"; vinteger_m1 XOR vinteger_one
PRINT "XOR INTEGER INTEGER 6:"; vinteger_zero XOR vinteger_one
PRINT "XOR INTEGER INTEGER 7:"; vinteger_r1 XOR vinteger_r2
PRINT "XOR INTEGER INTEGER 8:"; vinteger_r2 XOR vinteger_r1
PRINT "XOR INTEGER LONG 1:"; vinteger_min XOR vlong_min
PRINT "XOR INTEGER LONG 2:"; vinteger_max XOR vlong_max
PRINT "XOR INTEGER LONG 3:"; vinteger_min XOR vlong_max
PRINT "XOR INTEGER LONG 4:"; vinteger_max XOR vlong_min
PRINT "XOR INTEGER LONG 5:"; vinteger_m1 XOR vlong_one
PRINT "XOR INTEGER LONG 6:"; vinteger_zero XOR vlong_one
PRINT "XOR INTEGER LONG 7:"; vinteger_r1 XOR vlong_r2
PRINT "XOR INTEGER LONG 8:"; vinteger_r2 XOR vlong_r1
PRINT "XOR INTEGER INT64 1:"; vinteger_min XOR vint64_min
PRINT "XOR INTEGER INT64 2:"; vinteger_max XOR vint64_max
PRINT "XOR INTEGER INT64 3:"; vinteger_min XOR vint64_max
PRINT "XOR INTEGER INT64 4:"; vinteger_max XOR vint64_min
PRINT "XOR INTEGER INT64 5:"; vinteger_m1 XOR vint64_one
PRINT "XOR INTEGER INT64 6:"; vinteger_zero XOR vint64_one
PRINT "XOR INTEGER INT64 7:"; vinteger_r1 XOR vint64_r2
PRINT "XOR INTEGER INT64 8:"; vinteger_r2 XOR vint64_r1
PRINT "XOR INTEGER SINGLE 1:"; vinteger_min XOR vsingle_min
PRINT "XOR INTEGER SINGLE 2:"; vinteger_max XOR vsingle_max
PRINT "XOR INTEGER SINGLE 3:"; vinteger_min XOR vsingle_max
PRINT "XOR INTEGER SINGLE 4:"; vinteger_max XOR vsingle_min
PRINT "XOR INTEGER SINGLE 5:"; vinteger_m1 XOR vsingle_one
PRINT "XOR INTEGER SINGLE 6:"; vinteger_zero XOR vsingle_one
PRINT "XOR INTEGER SINGLE 7:"; vinteger_r1 XOR vsingle_r2
PRINT "XOR INTEGER SINGLE 8:"; vinteger_r2 XOR vsingle_r1
PRINT "XOR INTEGER DOUBLE 1:"; vinteger_min XOR vdouble_min
PRINT "XOR INTEGER DOUBLE 2:"; vinteger_max XOR vdouble_max
PRINT "XOR INTEGER DOUBLE 3:"; vinteger_min XOR vdouble_max
PRINT "XOR INTEGER DOUBLE 4:"; vinteger_max XOR vdouble_min
PRINT "XOR INTEGER DOUBLE 5:"; vinteger_m1 XOR vdouble_one
PRINT "XOR INTEGER DOUBLE 6:"; vinteger_zero XOR vdouble_one
PRINT "XOR INTEGER DOUBLE 7:"; vinteger_r1 XOR vdouble_r2
PRINT "XOR INTEGER DOUBLE 8:"; vinteger_r2 XOR vdouble_r1
PRINT "XOR INTEGER FLOAT 1:"; vinteger_min XOR vfloat_min
PRINT "XOR INTEGER FLOAT 2:"; vinteger_max XOR vfloat_max
PRINT "XOR INTEGER FLOAT 3:"; vinteger_min XOR vfloat_max
PRINT "XOR INTEGER FLOAT 4:"; vinteger_max XOR vfloat_min
PRINT "XOR INTEGER FLOAT 5:"; vinteger_m1 XOR vfloat_one
PRINT "XOR INTEGER FLOAT 6:"; vinteger_zero XOR vfloat_one
PRINT "XOR INTEGER FLOAT 7:"; vinteger_r1 XOR vfloat_r2
PRINT "XOR INTEGER FLOAT 8:"; vinteger_r2 XOR vfloat_r1
PRINT "XOR LONG INTEGER 1:"; vlong_min XOR vinteger_min
PRINT "XOR LONG INTEGER 2:"; vlong_max XOR vinteger_max
PRINT "XOR LONG INTEGER 3:"; vlong_min XOR vinteger_max
PRINT "XOR LONG INTEGER 4:"; vlong_max XOR vinteger_min
PRINT "XOR LONG INTEGER 5:"; vlong_m1 XOR vinteger_one
PRINT "XOR LONG INTEGER 6:"; vlong_zero XOR vinteger_one
PRINT "XOR LONG INTEGER 7:"; vlong_r1 XOR vinteger_r2
PRINT "XOR LONG INTEGER 8:"; vlong_r2 XOR vinteger_r1
PRINT "XOR LONG LONG 1:"; vlong_min XOR vlong_min
PRINT "XOR LONG LONG 2:"; vlong_max XOR vlong_max
PRINT "XOR LONG LONG 3:"; vlong_min XOR vlong_max
PRINT "XOR LONG LONG 4:"; vlong_max XOR vlong_min
PRINT "XOR LONG LONG 5:"; vlong_m1 XOR vlong_one
PRINT "XOR LONG LONG 6:"; vlong_zero XOR vlong_one
PRINT "XOR LONG LONG 7:"; vlong_r1 XOR vlong_r2
PRINT "XOR LONG LONG 8:"; vlong_r2 XOR vlong_r1
PRINT "XOR LONG INT64 1:"; vlong_min XOR vint64_min
PRINT "XOR LONG INT64 2:"; vlong_max XOR vint64_max
PRINT "XOR LONG INT64 3:"; vlong_min XOR vint64_max
PRINT "XOR LONG INT64 4:"; vlong_max XOR vint64_min
PRINT "XOR LONG INT64 5:"; vlong_m1 XOR vint64_one
PRINT "XOR LONG INT64 6:"; vlong_zero XOR vint64_one
PRINT "XOR LONG INT64 7:"; vlong_r1 XOR vint64_r2
PRINT "XOR LONG INT64 8:"; vlong_r2 XOR vint64_r1
PRINT "XOR LONG SINGLE 1:"; vlong_min XOR vsingle_min
PRINT "XOR LONG SINGLE 2:"; vlong_max XOR vsingle_max
PRINT "XOR LONG SINGLE 3:"; vlong_min XOR vsingle_max
PRINT "XOR LONG SINGLE 4:"; vlong_max XOR vsingle_min
PRINT "XOR LONG SINGLE 5:"; vlong_m1 XOR vsingle_one
PRINT "XOR LONG SINGLE 6:"; vlong_zero XOR vsingle_one
PRINT "XOR LONG SINGLE 7:"; vlong_r1 XOR vsingle_r2
PRINT "XOR LONG SINGLE 8:"; vlong_r2 XOR vsingle_r1
PRINT "XOR LONG DOUBLE 1:"; vlong_min XOR vdouble_min
PRINT "XOR LONG DOUBLE 2:"; vlong_max XOR vdouble_max
PRINT "XOR LONG DOUBLE 3:"; vlong_min XOR vdouble_max
PRINT "XOR LONG DOUBLE 4:"; vlong_max XOR vdouble_min
PRINT "XOR LONG DOUBLE 5:"; vlong_m1 XOR vdouble_one
PRINT "XOR LONG DOUBLE 6:"; vlong_zero XOR vdouble_one
PRINT "XOR LONG DOUBLE 7:"; vlong_r1 XOR vdouble_r2
PRINT "XOR LONG DOUBLE 8:"; vlong_r2 XOR vdouble_r1
PRINT "XOR LONG FLOAT 1:"; vlong_min XOR vfloat_min
PRINT "XOR LONG FLOAT 2:"; vlong_max XOR vfloat_max
PRINT "XOR LONG FLOAT 3:"; vlong_min XOR vfloat_max
PRINT "XOR LONG FLOAT 4:"; vlong_max XOR vfloat_min
PRINT "XOR LONG FLOAT 5:"; vlong_m1 XOR vfloat_one
PRINT "XOR LONG FLOAT 6:"; vlong_zero XOR vfloat_one
PRINT "XOR LONG FLOAT 7:"; vlong_r1 XOR vfloat_r2
PRINT "XOR LONG FLOAT 8:"; vlong_r2 XOR vfloat_r1
PRINT "XOR INT64 INTEGER 1:"; vint64_min XOR vinteger_min
PRINT "XOR INT64 INTEGER 2:"; vint64_max XOR vinteger_max
PRINT "XOR INT64 INTEGER 3:"; vint64_min XOR vinteger_max
PRINT "XOR INT64 INTEGER 4:"; vint64_max XOR vinteger_min
PRINT "XOR INT64 INTEGER 5:"; vint64_m1 XOR vinteger_one
PRINT "XOR INT64 INTEGER 6:"; vint64_zero XOR vinteger_one
PRINT "XOR INT64 INTEGER 7:"; vint64_r1 XOR vinteger_r2
PRINT "XOR INT64 INTEGER 8:"; vint64_r2 XOR vinteger_r1
PRINT "XOR INT64 LONG 1:"; vint64_min XOR vlong_min
PRINT "XOR INT64 LONG 2:"; vint64_max XOR vlong_max
PRINT "XOR INT64 LONG 3:"; vint64_min XOR vlong_max
PRINT "XOR INT64 LONG 4:"; vint64_max XOR vlong_min
PRINT "XOR INT64 LONG 5:"; vint64_m1 XOR vlong_one
PRINT "XOR INT64 LONG 6:"; vint64_zero XOR vlong_one
PRINT "XOR INT64 LONG 7:"; vint64_r1 XOR vlong_r2
PRINT "XOR INT64 LONG 8:"; vint64_r2 XOR vlong_r1
PRINT "XOR INT64 INT64 1:"; vint64_min XOR vint64_min
PRINT "XOR INT64 INT64 2:"; vint64_max XOR vint64_max
PRINT "XOR INT64 INT64 3:"; vint64_min XOR vint64_max
PRINT "XOR INT64 INT64 4:"; vint64_max XOR vint64_min
PRINT "XOR INT64 INT64 5:"; vint64_m1 XOR vint64_one
PRINT "XOR INT64 INT64 6:"; vint64_zero XOR vint64_one
PRINT "XOR INT64 INT64 7:"; vint64_r1 XOR vint64_r2
PRINT "XOR INT64 INT64 8:"; vint64_r2 XOR vint64_r1
PRINT "XOR INT64 SINGLE 1:"; vint64_min XOR vsingle_min
PRINT "XOR INT64 SINGLE 2:"; vint64_max XOR vsingle_max
PRINT "XOR INT64 SINGLE 3:"; vint64_min XOR vsingle_max
PRINT "XOR INT64 SINGLE 4:"; vint64_max XOR vsingle_min
PRINT "XOR INT64 SINGLE 5:"; vint64_m1 XOR vsingle_one
PRINT "XOR INT64 SINGLE 6:"; vint64_zero XOR vsingle_one
PRINT "XOR INT64 SINGLE 7:"; vint64_r1 XOR vsingle_r2
PRINT "XOR INT64 SINGLE 8:"; vint64_r2 XOR vsingle_r1
PRINT "XOR INT64 DOUBLE 1:"; vint64_min XOR vdouble_min
PRINT "XOR INT64 DOUBLE 2:"; vint64_max XOR vdouble_max
PRINT "XOR INT64 DOUBLE 3:"; vint64_min XOR vdouble_max
PRINT "XOR INT64 DOUBLE 4:"; vint64_max XOR vdouble_min
PRINT "XOR INT64 DOUBLE 5:"; vint64_m1 XOR vdouble_one
PRINT "XOR INT64 DOUBLE 6:"; vint64_zero XOR vdouble_one
PRINT "XOR INT64 DOUBLE 7:"; vint64_r1 XOR vdouble_r2
PRINT "XOR INT64 DOUBLE 8:"; vint64_r2 XOR vdouble_r1
PRINT "XOR INT64 FLOAT 1:"; vint64_min XOR vfloat_min
PRINT "XOR INT64 FLOAT 2:"; vint64_max XOR vfloat_max
PRINT "XOR INT64 FLOAT 3:"; vint64_min XOR vfloat_max
PRINT "XOR INT64 FLOAT 4:"; vint64_max XOR vfloat_min
PRINT "XOR INT64 FLOAT 5:"; vint64_m1 XOR vfloat_one
PRINT "XOR INT64 FLOAT 6:"; vint64_zero XOR vfloat_one
PRINT "XOR INT64 FLOAT 7:"; vint64_r1 XOR vfloat_r2
PRINT "XOR INT64 FLOAT 8:"; vint64_r2 XOR vfloat_r1
PRINT "XOR SINGLE INTEGER 1:"; vsingle_min XOR vinteger_min
PRINT "XOR SINGLE INTEGER 2:"; vsingle_max XOR vinteger_max
PRINT "XOR SINGLE INTEGER 3:"; vsingle_min XOR vinteger_max
PRINT "XOR SINGLE INTEGER 4:"; vsingle_max XOR vinteger_min
PRINT "XOR SINGLE INTEGER 5:"; vsingle_m1 XOR vinteger_one
PRINT "XOR SINGLE INTEGER 6:"; vsingle_zero XOR vinteger_one
PRINT "XOR SINGLE INTEGER 7:"; vsingle_r1 XOR vinteger_r2
PRINT "XOR SINGLE INTEGER 8:"; vsingle_r2 XOR vinteger_r1
PRINT "XOR SINGLE LONG 1:"; vsingle_min XOR vlong_min
PRINT "XOR SINGLE LONG 2:"; vsingle_max XOR vlong_max
PRINT "XOR SINGLE LONG 3:"; vsingle_min XOR vlong_max
PRINT "XOR SINGLE LONG 4:"; vsingle_max XOR vlong_min
PRINT "XOR SINGLE LONG 5:"; vsingle_m1 XOR vlong_one
PRINT "XOR SINGLE LONG 6:"; vsingle_zero XOR vlong_one
PRINT "XOR SINGLE LONG 7:"; vsingle_r1 XOR vlong_r2
PRINT "XOR SINGLE LONG 8:"; vsingle_r2 XOR vlong_r1
PRINT "XOR SINGLE INT64 1:"; vsingle_min XOR vint64_min
PRINT "XOR SINGLE INT64 2:"; vsingle_max XOR vint64_max
PRINT "XOR SINGLE INT64 3:"; vsingle_min XOR vint64_max
PRINT "XOR SINGLE INT64 4:"; vsingle_max XOR vint64_min
PRINT "XOR SINGLE INT64 5:"; vsingle_m1 XOR vint64_one
PRINT "XOR SINGLE INT64 6:"; vsingle_zero XOR vint64_one
PRINT "XOR SINGLE INT64 7:"; vsingle_r1 XOR vint64_r2
PRINT "XOR SINGLE INT64 8:"; vsingle_r2 XOR vint64_r1
PRINT "XOR SINGLE SINGLE 1:"; vsingle_min XOR vsingle_min
PRINT "XOR SINGLE SINGLE 2:"; vsingle_max XOR vsingle_max
PRINT "XOR SINGLE SINGLE 3:"; vsingle_min XOR vsingle_max
PRINT "XOR SINGLE SINGLE 4:"; vsingle_max XOR vsingle_min
PRINT "XOR SINGLE SINGLE 5:"; vsingle_m1 XOR vsingle_one
PRINT "XOR SINGLE SINGLE 6:"; vsingle_zero XOR vsingle_one
PRINT "XOR SINGLE SINGLE 7:"; vsingle_r1 XOR vsingle_r2
PRINT "XOR SINGLE SINGLE 8:"; vsingle_r2 XOR vsingle_r1
PRINT "XOR SINGLE DOUBLE 1:"; vsingle_min XOR vdouble_min
PRINT "XOR SINGLE DOUBLE 2:"; vsingle_max XOR vdouble_max
PRINT "XOR SINGLE DOUBLE 3:"; vsingle_min XOR vdouble_max
PRINT "XOR SINGLE DOUBLE 4:"; vsingle_max XOR vdouble_min
PRINT "XOR SINGLE DOUBLE 5:"; vsingle_m1 XOR vdouble_one
PRINT "XOR SINGLE DOUBLE 6:"; vsingle_zero XOR vdouble_one
PRINT "XOR SINGLE DOUBLE 7:"; vsingle_r1 XOR vdouble_r2
PRINT "XOR SINGLE DOUBLE 8:"; vsingle_r2 XOR vdouble_r1
PRINT "XOR SINGLE FLOAT 1:"; vsingle_min XOR vfloat_min
PRINT "XOR SINGLE FLOAT 2:"; vsingle_max XOR vfloat_max
PRINT "XOR SINGLE FLOAT 3:"; vsingle_min XOR vfloat_max
PRINT "XOR SINGLE FLOAT 4:"; vsingle_max XOR vfloat_min
PRINT "XOR SINGLE FLOAT 5:"; vsingle_m1 XOR vfloat_one
PRINT "XOR SINGLE FLOAT 6:"; vsingle_zero XOR vfloat_one
PRINT "XOR SINGLE FLOAT 7:"; vsingle_r1 XOR vfloat_r2
PRINT "XOR SINGLE FLOAT 8:"; vsingle_r2 XOR vfloat_r1
PRINT "XOR DOUBLE INTEGER 1:"; vdouble_min XOR vinteger_min
PRINT "XOR DOUBLE INTEGER 2:"; vdouble_max XOR vinteger_max
PRINT "XOR DOUBLE INTEGER 3:"; vdouble_min XOR vinteger_max
PRINT "XOR DOUBLE INTEGER 4:"; vdouble_max XOR vinteger_min
PRINT "XOR DOUBLE INTEGER 5:"; vdouble_m1 XOR vinteger_one
PRINT "XOR DOUBLE INTEGER 6:"; vdouble_zero XOR vinteger_one
PRINT "XOR DOUBLE INTEGER 7:"; vdouble_r1 XOR vinteger_r2
PRINT "XOR DOUBLE INTEGER 8:"; vdouble_r2 XOR vinteger_r1
PRINT "XOR DOUBLE LONG 1:"; vdouble_min XOR vlong_min
PRINT "XOR DOUBLE LONG 2:"; vdouble_max XOR vlong_max
PRINT "XOR DOUBLE LONG 3:"; vdouble_min XOR vlong_max
PRINT "XOR DOUBLE LONG 4:"; vdouble_max XOR vlong_min
PRINT "XOR DOUBLE LONG 5:"; vdouble_m1 XOR vlong_one
PRINT "XOR DOUBLE LONG 6:"; vdouble_zero XOR vlong_one
PRINT "XOR DOUBLE LONG 7:"; vdouble_r1 XOR vlong_r2
PRINT "XOR DOUBLE LONG 8:"; vdouble_r2 XOR vlong_r1
PRINT "XOR DOUBLE INT64 1:"; vdouble_min XOR vint64_min
PRINT "XOR DOUBLE INT64 2:"; vdouble_max XOR vint64_max
PRINT "XOR DOUBLE INT64 3:"; vdouble_min XOR vint64_max
PRINT "XOR DOUBLE INT64 4:"; vdouble_max XOR vint64_min
PRINT "XOR DOUBLE INT64 5:"; vdouble_m1 XOR vint64_one
PRINT "XOR DOUBLE INT64 6:"; vdouble_zero XOR vint64_one
PRINT "XOR DOUBLE INT64 7:"; vdouble_r1 XOR vint64_r2
PRINT "XOR DOUBLE INT64 8:"; vdouble_r2 XOR vint64_r1
PRINT "XOR DOUBLE SINGLE 1:"; vdouble_min XOR vsingle_min
PRINT "XOR DOUBLE SINGLE 2:"; vdouble_max XOR vsingle_max
PRINT "XOR DOUBLE SINGLE 3:"; vdouble_min XOR vsingle_max
PRINT "XOR DOUBLE SINGLE 4:"; vdouble_max XOR vsingle_min
PRINT "XOR DOUBLE SINGLE 5:"; vdouble_m1 XOR vsingle_one
PRINT "XOR DOUBLE SINGLE 6:"; vdouble_zero XOR vsingle_one
PRINT "XOR DOUBLE SINGLE 7:"; vdouble_r1 XOR vsingle_r2
PRINT "XOR DOUBLE SINGLE 8:"; vdouble_r2 XOR vsingle_r1
PRINT "XOR DOUBLE DOUBLE 1:"; vdouble_min XOR vdouble_min
PRINT "XOR DOUBLE DOUBLE 2:"; vdouble_max XOR vdouble_max
PRINT "XOR DOUBLE DOUBLE 3:"; vdouble_min XOR vdouble_max
PRINT "XOR DOUBLE DOUBLE 4:"; vdouble_max XOR vdouble_min
PRINT "XOR DOUBLE DOUBLE 5:"; vdouble_m1 XOR vdouble_one
PRINT "XOR DOUBLE DOUBLE 6:"; vdouble_zero XOR vdouble_one
PRINT "XOR DOUBLE DOUBLE 7:"; vdouble_r1 XOR vdouble_r2
PRINT "XOR DOUBLE DOUBLE 8:"; vdouble_r2 XOR vdouble_r1
PRINT "XOR DOUBLE FLOAT 1:"; vdouble_min XOR vfloat_min
PRINT "XOR DOUBLE FLOAT 2:"; vdouble_max XOR vfloat_max
PRINT "XOR DOUBLE FLOAT 3:"; vdouble_min XOR vfloat_max
PRINT "XOR DOUBLE FLOAT 4:"; vdouble_max XOR vfloat_min
PRINT "XOR DOUBLE FLOAT 5:"; vdouble_m1 XOR vfloat_one
PRINT "XOR DOUBLE FLOAT 6:"; vdouble_zero XOR vfloat_one
PRINT "XOR DOUBLE FLOAT 7:"; vdouble_r1 XOR vfloat_r2
PRINT "XOR DOUBLE FLOAT 8:"; vdouble_r2 XOR vfloat_r1
PRINT "XOR FLOAT INTEGER 1:"; vfloat_min XOR vinteger_min
PRINT "XOR FLOAT INTEGER 2:"; vfloat_max XOR vinteger_max
PRINT "XOR FLOAT INTEGER 3:"; vfloat_min XOR vinteger_max
PRINT "XOR FLOAT INTEGER 4:"; vfloat_max XOR vinteger_min
PRINT "XOR FLOAT INTEGER 5:"; vfloat_m1 XOR vinteger_one
PRINT "XOR FLOAT INTEGER 6:"; vfloat_zero XOR vinteger_one
PRINT "XOR FLOAT INTEGER 7:"; vfloat_r1 XOR vinteger_r2
PRINT "XOR FLOAT INTEGER 8:"; vfloat_r2 XOR vinteger_r1
PRINT "XOR FLOAT LONG 1:"; vfloat_min XOR vlong_min
PRINT "XOR FLOAT LONG 2:"; vfloat_max XOR vlong_max
PRINT "XOR FLOAT LONG 3:"; vfloat_min XOR vlong_max
PRINT "XOR FLOAT LONG 4:"; vfloat_max XOR vlong_min
PRINT "XOR FLOAT LONG 5:"; vfloat_m1 XOR vlong_one
PRINT "XOR FLOAT LONG 6:"; vfloat_zero XOR vlong_one
PRINT "XOR FLOAT LONG 7:"; vfloat_r1 XOR vlong_r2
PRINT "XOR FLOAT LONG 8:"; vfloat_r2 XOR vlong_r1
PRINT "XOR FLOAT INT64 1:"; vfloat_min XOR vint64_min
PRINT "XOR FLOAT INT64 2:"; vfloat_max XOR vint64_max
PRINT "XOR FLOAT INT64 3:"; vfloat_min XOR vint64_max
PRINT "XOR FLOAT INT64 4:"; vfloat_max XOR vint64_min
PRINT "XOR FLOAT INT64 5:"; vfloat_m1 XOR vint64_one
PRINT "XOR FLOAT INT64 6:"; vfloat_zero XOR vint64_one
PRINT "XOR FLOAT INT64 7:"; vfloat_r1 XOR vint64_r2
PRINT "XOR FLOAT INT64 8:"; vfloat_r2 XOR vint64_r1
PRINT "XOR FLOAT SINGLE 1:"; vfloat_min XOR vsingle_min
PRINT "XOR FLOAT SINGLE 2:"; vfloat_max XOR vsingle_max
PRINT "XOR FLOAT SINGLE 3:"; vfloat_min XOR vsingle_max
PRINT "XOR FLOAT SINGLE 4:"; vfloat_max XOR vsingle_min
PRINT "XOR FLOAT SINGLE 5:"; vfloat_m1 XOR vsingle_one
PRINT "XOR FLOAT SINGLE 6:"; vfloat_zero XOR vsingle_one
PRINT "XOR FLOAT SINGLE 7:"; vfloat_r1 XOR vsingle_r2
PRINT "XOR FLOAT SINGLE 8:"; vfloat_r2 XOR vsingle_r1
PRINT "XOR FLOAT DOUBLE 1:"; vfloat_min XOR vdouble_min
PRINT "XOR FLOAT DOUBLE 2:"; vfloat_max XOR vdouble_max
PRINT "XOR FLOAT DOUBLE 3:"; vfloat_min XOR vdouble_max
PRINT "XOR FLOAT DOUBLE 4:"; vfloat_max XOR vdouble_min
PRINT "XOR FLOAT DOUBLE 5:"; vfloat_m1 XOR vdouble_one
PRINT "XOR FLOAT DOUBLE 6:"; vfloat_zero XOR vdouble_one
PRINT "XOR FLOAT DOUBLE 7:"; vfloat_r1 XOR vdouble_r2
PRINT "XOR FLOAT DOUBLE 8:"; vfloat_r2 XOR vdouble_r1
PRINT "XOR FLOAT FLOAT 1:"; vfloat_min XOR vfloat_min
PRINT "XOR FLOAT FLOAT 2:"; vfloat_max XOR vfloat_max
PRINT "XOR FLOAT FLOAT 3:"; vfloat_min XOR vfloat_max
PRINT "XOR FLOAT FLOAT 4:"; vfloat_max XOR vfloat_min
PRINT "XOR FLOAT FLOAT 5:"; vfloat_m1 XOR vfloat_one
PRINT "XOR FLOAT FLOAT 6:"; vfloat_zero XOR vfloat_one
PRINT "XOR FLOAT FLOAT 7:"; vfloat_r1 XOR vfloat_r2
PRINT "XOR FLOAT FLOAT 8:"; vfloat_r2 XOR vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
