$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): AND on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "AND INTEGER INTEGER 1:"; vinteger_min AND vinteger_min
PRINT "AND INTEGER INTEGER 2:"; vinteger_max AND vinteger_max
PRINT "AND INTEGER INTEGER 3:"; vinteger_min AND vinteger_max
PRINT "AND INTEGER INTEGER 4:"; vinteger_max AND vinteger_min
PRINT "AND INTEGER INTEGER 5:"; vinteger_m1 AND vinteger_one
PRINT "AND INTEGER INTEGER 6:"; vinteger_zero AND vinteger_one
PRINT "AND INTEGER INTEGER 7:"; vinteger_r1 AND vinteger_r2
PRINT "AND INTEGER INTEGER 8:"; vinteger_r2 AND vinteger_r1
PRINT "AND INTEGER LONG 1:"; vinteger_min AND vlong_min
PRINT "AND INTEGER LONG 2:"; vinteger_max AND vlong_max
PRINT "AND INTEGER LONG 3:"; vinteger_min AND vlong_max
PRINT "AND INTEGER LONG 4:"; vinteger_max AND vlong_min
PRINT "AND INTEGER LONG 5:"; vinteger_m1 AND vlong_one
PRINT "AND INTEGER LONG 6:"; vinteger_zero AND vlong_one
PRINT "AND INTEGER LONG 7:"; vinteger_r1 AND vlong_r2
PRINT "AND INTEGER LONG 8:"; vinteger_r2 AND vlong_r1
PRINT "AND INTEGER INT64 1:"; vinteger_min AND vint64_min
PRINT "AND INTEGER INT64 2:"; vinteger_max AND vint64_max
PRINT "AND INTEGER INT64 3:"; vinteger_min AND vint64_max
PRINT "AND INTEGER INT64 4:"; vinteger_max AND vint64_min
PRINT "AND INTEGER INT64 5:"; vinteger_m1 AND vint64_one
PRINT "AND INTEGER INT64 6:"; vinteger_zero AND vint64_one
PRINT "AND INTEGER INT64 7:"; vinteger_r1 AND vint64_r2
PRINT "AND INTEGER INT64 8:"; vinteger_r2 AND vint64_r1
PRINT "AND INTEGER SINGLE 1:"; vinteger_min AND vsingle_min
PRINT "AND INTEGER SINGLE 2:"; vinteger_max AND vsingle_max
PRINT "AND INTEGER SINGLE 3:"; vinteger_min AND vsingle_max
PRINT "AND INTEGER SINGLE 4:"; vinteger_max AND vsingle_min
PRINT "AND INTEGER SINGLE 5:"; vinteger_m1 AND vsingle_one
PRINT "AND INTEGER SINGLE 6:"; vinteger_zero AND vsingle_one
PRINT "AND INTEGER SINGLE 7:"; vinteger_r1 AND vsingle_r2
PRINT "AND INTEGER SINGLE 8:"; vinteger_r2 AND vsingle_r1
PRINT "AND INTEGER DOUBLE 1:"; vinteger_min AND vdouble_min
PRINT "AND INTEGER DOUBLE 2:"; vinteger_max AND vdouble_max
PRINT "AND INTEGER DOUBLE 3:"; vinteger_min AND vdouble_max
PRINT "AND INTEGER DOUBLE 4:"; vinteger_max AND vdouble_min
PRINT "AND INTEGER DOUBLE 5:"; vinteger_m1 AND vdouble_one
PRINT "AND INTEGER DOUBLE 6:"; vinteger_zero AND vdouble_one
PRINT "AND INTEGER DOUBLE 7:"; vinteger_r1 AND vdouble_r2
PRINT "AND INTEGER DOUBLE 8:"; vinteger_r2 AND vdouble_r1
PRINT "AND INTEGER FLOAT 1:"; vinteger_min AND vfloat_min
PRINT "AND INTEGER FLOAT 2:"; vinteger_max AND vfloat_max
PRINT "AND INTEGER FLOAT 3:"; vinteger_min AND vfloat_max
PRINT "AND INTEGER FLOAT 4:"; vinteger_max AND vfloat_min
PRINT "AND INTEGER FLOAT 5:"; vinteger_m1 AND vfloat_one
PRINT "AND INTEGER FLOAT 6:"; vinteger_zero AND vfloat_one
PRINT "AND INTEGER FLOAT 7:"; vinteger_r1 AND vfloat_r2
PRINT "AND INTEGER FLOAT 8:"; vinteger_r2 AND vfloat_r1
PRINT "AND LONG INTEGER 1:"; vlong_min AND vinteger_min
PRINT "AND LONG INTEGER 2:"; vlong_max AND vinteger_max
PRINT "AND LONG INTEGER 3:"; vlong_min AND vinteger_max
PRINT "AND LONG INTEGER 4:"; vlong_max AND vinteger_min
PRINT "AND LONG INTEGER 5:"; vlong_m1 AND vinteger_one
PRINT "AND LONG INTEGER 6:"; vlong_zero AND vinteger_one
PRINT "AND LONG INTEGER 7:"; vlong_r1 AND vinteger_r2
PRINT "AND LONG INTEGER 8:"; vlong_r2 AND vinteger_r1
PRINT "AND LONG LONG 1:"; vlong_min AND vlong_min
PRINT "AND LONG LONG 2:"; vlong_max AND vlong_max
PRINT "AND LONG LONG 3:"; vlong_min AND vlong_max
PRINT "AND LONG LONG 4:"; vlong_max AND vlong_min
PRINT "AND LONG LONG 5:"; vlong_m1 AND vlong_one
PRINT "AND LONG LONG 6:"; vlong_zero AND vlong_one
PRINT "AND LONG LONG 7:"; vlong_r1 AND vlong_r2
PRINT "AND LONG LONG 8:"; vlong_r2 AND vlong_r1
PRINT "AND LONG INT64 1:"; vlong_min AND vint64_min
PRINT "AND LONG INT64 2:"; vlong_max AND vint64_max
PRINT "AND LONG INT64 3:"; vlong_min AND vint64_max
PRINT "AND LONG INT64 4:"; vlong_max AND vint64_min
PRINT "AND LONG INT64 5:"; vlong_m1 AND vint64_one
PRINT "AND LONG INT64 6:"; vlong_zero AND vint64_one
PRINT "AND LONG INT64 7:"; vlong_r1 AND vint64_r2
PRINT "AND LONG INT64 8:"; vlong_r2 AND vint64_r1
PRINT "AND LONG SINGLE 1:"; vlong_min AND vsingle_min
PRINT "AND LONG SINGLE 2:"; vlong_max AND vsingle_max
PRINT "AND LONG SINGLE 3:"; vlong_min AND vsingle_max
PRINT "AND LONG SINGLE 4:"; vlong_max AND vsingle_min
PRINT "AND LONG SINGLE 5:"; vlong_m1 AND vsingle_one
PRINT "AND LONG SINGLE 6:"; vlong_zero AND vsingle_one
PRINT "AND LONG SINGLE 7:"; vlong_r1 AND vsingle_r2
PRINT "AND LONG SINGLE 8:"; vlong_r2 AND vsingle_r1
PRINT "AND LONG DOUBLE 1:"; vlong_min AND vdouble_min
PRINT "AND LONG DOUBLE 2:"; vlong_max AND vdouble_max
PRINT "AND LONG DOUBLE 3:"; vlong_min AND vdouble_max
PRINT "AND LONG DOUBLE 4:"; vlong_max AND vdouble_min
PRINT "AND LONG DOUBLE 5:"; vlong_m1 AND vdouble_one
PRINT "AND LONG DOUBLE 6:"; vlong_zero AND vdouble_one
PRINT "AND LONG DOUBLE 7:"; vlong_r1 AND vdouble_r2
PRINT "AND LONG DOUBLE 8:"; vlong_r2 AND vdouble_r1
PRINT "AND LONG FLOAT 1:"; vlong_min AND vfloat_min
PRINT "AND LONG FLOAT 2:"; vlong_max AND vfloat_max
PRINT "AND LONG FLOAT 3:"; vlong_min AND vfloat_max
PRINT "AND LONG FLOAT 4:"; vlong_max AND vfloat_min
PRINT "AND LONG FLOAT 5:"; vlong_m1 AND vfloat_one
PRINT "AND LONG FLOAT 6:"; vlong_zero AND vfloat_one
PRINT "AND LONG FLOAT 7:"; vlong_r1 AND vfloat_r2
PRINT "AND LONG FLOAT 8:"; vlong_r2 AND vfloat_r1
PRINT "AND INT64 INTEGER 1:"; vint64_min AND vinteger_min
PRINT "AND INT64 INTEGER 2:"; vint64_max AND vinteger_max
PRINT "AND INT64 INTEGER 3:"; vint64_min AND vinteger_max
PRINT "AND INT64 INTEGER 4:"; vint64_max AND vinteger_min
PRINT "AND INT64 INTEGER 5:"; vint64_m1 AND vinteger_one
PRINT "AND INT64 INTEGER 6:"; vint64_zero AND vinteger_one
PRINT "AND INT64 INTEGER 7:"; vint64_r1 AND vinteger_r2
PRINT "AND INT64 INTEGER 8:"; vint64_r2 AND vinteger_r1
PRINT "AND INT64 LONG 1:"; vint64_min AND vlong_min
PRINT "AND INT64 LONG 2:"; vint64_max AND vlong_max
PRINT "AND INT64 LONG 3:"; vint64_min AND vlong_max
PRINT "AND INT64 LONG 4:"; vint64_max AND vlong_min
PRINT "AND INT64 LONG 5:"; vint64_m1 AND vlong_one
PRINT "AND INT64 LONG 6:"; vint64_zero AND vlong_one
PRINT "AND INT64 LONG 7:"; vint64_r1 AND vlong_r2
PRINT "AND INT64 LONG 8:"; vint64_r2 AND vlong_r1
PRINT "AND INT64 INT64 1:"; vint64_min AND vint64_min
PRINT "AND INT64 INT64 2:"; vint64_max AND vint64_max
PRINT "AND INT64 INT64 3:"; vint64_min AND vint64_max
PRINT "AND INT64 INT64 4:"; vint64_max AND vint64_min
PRINT "AND INT64 INT64 5:"; vint64_m1 AND vint64_one
PRINT "AND INT64 INT64 6:"; vint64_zero AND vint64_one
PRINT "AND INT64 INT64 7:"; vint64_r1 AND vint64_r2
PRINT "AND INT64 INT64 8:"; vint64_r2 AND vint64_r1
PRINT "AND INT64 SINGLE 1:"; vint64_min AND vsingle_min
PRINT "AND INT64 SINGLE 2:"; vint64_max AND vsingle_max
PRINT "AND INT64 SINGLE 3:"; vint64_min AND vsingle_max
PRINT "AND INT64 SINGLE 4:"; vint64_max AND vsingle_min
PRINT "AND INT64 SINGLE 5:"; vint64_m1 AND vsingle_one
PRINT "AND INT64 SINGLE 6:"; vint64_zero AND vsingle_one
PRINT "AND INT64 SINGLE 7:"; vint64_r1 AND vsingle_r2
PRINT "AND INT64 SINGLE 8:"; vint64_r2 AND vsingle_r1
PRINT "AND INT64 DOUBLE 1:"; vint64_min AND vdouble_min
PRINT "AND INT64 DOUBLE 2:"; vint64_max AND vdouble_max
PRINT "AND INT64 DOUBLE 3:"; vint64_min AND vdouble_max
PRINT "AND INT64 DOUBLE 4:"; vint64_max AND vdouble_min
PRINT "AND INT64 DOUBLE 5:"; vint64_m1 AND vdouble_one
PRINT "AND INT64 DOUBLE 6:"; vint64_zero AND vdouble_one
PRINT "AND INT64 DOUBLE 7:"; vint64_r1 AND vdouble_r2
PRINT "AND INT64 DOUBLE 8:"; vint64_r2 AND vdouble_r1
PRINT "AND INT64 FLOAT 1:"; vint64_min AND vfloat_min
PRINT "AND INT64 FLOAT 2:"; vint64_max AND vfloat_max
PRINT "AND INT64 FLOAT 3:"; vint64_min AND vfloat_max
PRINT "AND INT64 FLOAT 4:"; vint64_max AND vfloat_min
PRINT "AND INT64 FLOAT 5:"; vint64_m1 AND vfloat_one
PRINT "AND INT64 FLOAT 6:"; vint64_zero AND vfloat_one
PRINT "AND INT64 FLOAT 7:"; vint64_r1 AND vfloat_r2
PRINT "AND INT64 FLOAT 8:"; vint64_r2 AND vfloat_r1
PRINT "AND SINGLE INTEGER 1:"; vsingle_min AND vinteger_min
PRINT "AND SINGLE INTEGER 2:"; vsingle_max AND vinteger_max
PRINT "AND SINGLE INTEGER 3:"; vsingle_min AND vinteger_max
PRINT "AND SINGLE INTEGER 4:"; vsingle_max AND vinteger_min
PRINT "AND SINGLE INTEGER 5:"; vsingle_m1 AND vinteger_one
PRINT "AND SINGLE INTEGER 6:"; vsingle_zero AND vinteger_one
PRINT "AND SINGLE INTEGER 7:"; vsingle_r1 AND vinteger_r2
PRINT "AND SINGLE INTEGER 8:"; vsingle_r2 AND vinteger_r1
PRINT "AND SINGLE LONG 1:"; vsingle_min AND vlong_min
PRINT "AND SINGLE LONG 2:"; vsingle_max AND vlong_max
PRINT "AND SINGLE LONG 3:"; vsingle_min AND vlong_max
PRINT "AND SINGLE LONG 4:"; vsingle_max AND vlong_min
PRINT "AND SINGLE LONG 5:"; vsingle_m1 AND vlong_one
PRINT "AND SINGLE LONG 6:"; vsingle_zero AND vlong_one
PRINT "AND SINGLE LONG 7:"; vsingle_r1 AND vlong_r2
PRINT "AND SINGLE LONG 8:"; vsingle_r2 AND vlong_r1
PRINT "AND SINGLE INT64 1:"; vsingle_min AND vint64_min
PRINT "AND SINGLE INT64 2:"; vsingle_max AND vint64_max
PRINT "AND SINGLE INT64 3:"; vsingle_min AND vint64_max
PRINT "AND SINGLE INT64 4:"; vsingle_max AND vint64_min
PRINT "AND SINGLE INT64 5:"; vsingle_m1 AND vint64_one
PRINT "AND SINGLE INT64 6:"; vsingle_zero AND vint64_one
PRINT "AND SINGLE INT64 7:"; vsingle_r1 AND vint64_r2
PRINT "AND SINGLE INT64 8:"; vsingle_r2 AND vint64_r1
PRINT "AND SINGLE SINGLE 1:"; vsingle_min AND vsingle_min
PRINT "AND SINGLE SINGLE 2:"; vsingle_max AND vsingle_max
PRINT "AND SINGLE SINGLE 3:"; vsingle_min AND vsingle_max
PRINT "AND SINGLE SINGLE 4:"; vsingle_max AND vsingle_min
PRINT "AND SINGLE SINGLE 5:"; vsingle_m1 AND vsingle_one
PRINT "AND SINGLE SINGLE 6:"; vsingle_zero AND vsingle_one
PRINT "AND SINGLE SINGLE 7:"; vsingle_r1 AND vsingle_r2
PRINT "AND SINGLE SINGLE 8:"; vsingle_r2 AND vsingle_r1
PRINT "AND SINGLE DOUBLE 1:"; vsingle_min AND vdouble_min
PRINT "AND SINGLE DOUBLE 2:"; vsingle_max AND vdouble_max
PRINT "AND SINGLE DOUBLE 3:"; vsingle_min AND vdouble_max
PRINT "AND SINGLE DOUBLE 4:"; vsingle_max AND vdouble_min
PRINT "AND SINGLE DOUBLE 5:"; vsingle_m1 AND vdouble_one
PRINT "AND SINGLE DOUBLE 6:"; vsingle_zero AND vdouble_one
PRINT "AND SINGLE DOUBLE 7:"; vsingle_r1 AND vdouble_r2
PRINT "AND SINGLE DOUBLE 8:"; vsingle_r2 AND vdouble_r1
PRINT "AND SINGLE FLOAT 1:"; vsingle_min AND vfloat_min
PRINT "AND SINGLE FLOAT 2:"; vsingle_max AND vfloat_max
PRINT "AND SINGLE FLOAT 3:"; vsingle_min AND vfloat_max
PRINT "AND SINGLE FLOAT 4:"; vsingle_max AND vfloat_min
PRINT "AND SINGLE FLOAT 5:"; vsingle_m1 AND vfloat_one
PRINT "AND SINGLE FLOAT 6:"; vsingle_zero AND vfloat_one
PRINT "AND SINGLE FLOAT 7:"; vsingle_r1 AND vfloat_r2
PRINT "AND SINGLE FLOAT 8:"; vsingle_r2 AND vfloat_r1
PRINT "AND DOUBLE INTEGER 1:"; vdouble_min AND vinteger_min
PRINT "AND DOUBLE INTEGER 2:"; vdouble_max AND vinteger_max
PRINT "AND DOUBLE INTEGER 3:"; vdouble_min AND vinteger_max
PRINT "AND DOUBLE INTEGER 4:"; vdouble_max AND vinteger_min
PRINT "AND DOUBLE INTEGER 5:"; vdouble_m1 AND vinteger_one
PRINT "AND DOUBLE INTEGER 6:"; vdouble_zero AND vinteger_one
PRINT "AND DOUBLE INTEGER 7:"; vdouble_r1 AND vinteger_r2
PRINT "AND DOUBLE INTEGER 8:"; vdouble_r2 AND vinteger_r1
PRINT "AND DOUBLE LONG 1:"; vdouble_min AND vlong_min
PRINT "AND DOUBLE LONG 2:"; vdouble_max AND vlong_max
PRINT "AND DOUBLE LONG 3:"; vdouble_min AND vlong_max
PRINT "AND DOUBLE LONG 4:"; vdouble_max AND vlong_min
PRINT "AND DOUBLE LONG 5:"; vdouble_m1 AND vlong_one
PRINT "AND DOUBLE LONG 6:"; vdouble_zero AND vlong_one
PRINT "AND DOUBLE LONG 7:"; vdouble_r1 AND vlong_r2
PRINT "AND DOUBLE LONG 8:"; vdouble_r2 AND vlong_r1
PRINT "AND DOUBLE INT64 1:"; vdouble_min AND vint64_min
PRINT "AND DOUBLE INT64 2:"; vdouble_max AND vint64_max
PRINT "AND DOUBLE INT64 3:"; vdouble_min AND vint64_max
PRINT "AND DOUBLE INT64 4:"; vdouble_max AND vint64_min
PRINT "AND DOUBLE INT64 5:"; vdouble_m1 AND vint64_one
PRINT "AND DOUBLE INT64 6:"; vdouble_zero AND vint64_one
PRINT "AND DOUBLE INT64 7:"; vdouble_r1 AND vint64_r2
PRINT "AND DOUBLE INT64 8:"; vdouble_r2 AND vint64_r1
PRINT "AND DOUBLE SINGLE 1:"; vdouble_min AND vsingle_min
PRINT "AND DOUBLE SINGLE 2:"; vdouble_max AND vsingle_max
PRINT "AND DOUBLE SINGLE 3:"; vdouble_min AND vsingle_max
PRINT "AND DOUBLE SINGLE 4:"; vdouble_max AND vsingle_min
PRINT "AND DOUBLE SINGLE 5:"; vdouble_m1 AND vsingle_one
PRINT "AND DOUBLE SINGLE 6:"; vdouble_zero AND vsingle_one
PRINT "AND DOUBLE SINGLE 7:"; vdouble_r1 AND vsingle_r2
PRINT "AND DOUBLE SINGLE 8:"; vdouble_r2 AND vsingle_r1
PRINT "AND DOUBLE DOUBLE 1:"; vdouble_min AND vdouble_min
PRINT "AND DOUBLE DOUBLE 2:"; vdouble_max AND vdouble_max
PRINT "AND DOUBLE DOUBLE 3:"; vdouble_min AND vdouble_max
PRINT "AND DOUBLE DOUBLE 4:"; vdouble_max AND vdouble_min
PRINT "AND DOUBLE DOUBLE 5:"; vdouble_m1 AND vdouble_one
PRINT "AND DOUBLE DOUBLE 6:"; vdouble_zero AND vdouble_one
PRINT "AND DOUBLE DOUBLE 7:"; vdouble_r1 AND vdouble_r2
PRINT "AND DOUBLE DOUBLE 8:"; vdouble_r2 AND vdouble_r1
PRINT "AND DOUBLE FLOAT 1:"; vdouble_min AND vfloat_min
PRINT "AND DOUBLE FLOAT 2:"; vdouble_max AND vfloat_max
PRINT "AND DOUBLE FLOAT 3:"; vdouble_min AND vfloat_max
PRINT "AND DOUBLE FLOAT 4:"; vdouble_max AND vfloat_min
PRINT "AND DOUBLE FLOAT 5:"; vdouble_m1 AND vfloat_one
PRINT "AND DOUBLE FLOAT 6:"; vdouble_zero AND vfloat_one
PRINT "AND DOUBLE FLOAT 7:"; vdouble_r1 AND vfloat_r2
PRINT "AND DOUBLE FLOAT 8:"; vdouble_r2 AND vfloat_r1
PRINT "AND FLOAT INTEGER 1:"; vfloat_min AND vinteger_min
PRINT "AND FLOAT INTEGER 2:"; vfloat_max AND vinteger_max
PRINT "AND FLOAT INTEGER 3:"; vfloat_min AND vinteger_max
PRINT "AND FLOAT INTEGER 4:"; vfloat_max AND vinteger_min
PRINT "AND FLOAT INTEGER 5:"; vfloat_m1 AND vinteger_one
PRINT "AND FLOAT INTEGER 6:"; vfloat_zero AND vinteger_one
PRINT "AND FLOAT INTEGER 7:"; vfloat_r1 AND vinteger_r2
PRINT "AND FLOAT INTEGER 8:"; vfloat_r2 AND vinteger_r1
PRINT "AND FLOAT LONG 1:"; vfloat_min AND vlong_min
PRINT "AND FLOAT LONG 2:"; vfloat_max AND vlong_max
PRINT "AND FLOAT LONG 3:"; vfloat_min AND vlong_max
PRINT "AND FLOAT LONG 4:"; vfloat_max AND vlong_min
PRINT "AND FLOAT LONG 5:"; vfloat_m1 AND vlong_one
PRINT "AND FLOAT LONG 6:"; vfloat_zero AND vlong_one
PRINT "AND FLOAT LONG 7:"; vfloat_r1 AND vlong_r2
PRINT "AND FLOAT LONG 8:"; vfloat_r2 AND vlong_r1
PRINT "AND FLOAT INT64 1:"; vfloat_min AND vint64_min
PRINT "AND FLOAT INT64 2:"; vfloat_max AND vint64_max
PRINT "AND FLOAT INT64 3:"; vfloat_min AND vint64_max
PRINT "AND FLOAT INT64 4:"; vfloat_max AND vint64_min
PRINT "AND FLOAT INT64 5:"; vfloat_m1 AND vint64_one
PRINT "AND FLOAT INT64 6:"; vfloat_zero AND vint64_one
PRINT "AND FLOAT INT64 7:"; vfloat_r1 AND vint64_r2
PRINT "AND FLOAT INT64 8:"; vfloat_r2 AND vint64_r1
PRINT "AND FLOAT SINGLE 1:"; vfloat_min AND vsingle_min
PRINT "AND FLOAT SINGLE 2:"; vfloat_max AND vsingle_max
PRINT "AND FLOAT SINGLE 3:"; vfloat_min AND vsingle_max
PRINT "AND FLOAT SINGLE 4:"; vfloat_max AND vsingle_min
PRINT "AND FLOAT SINGLE 5:"; vfloat_m1 AND vsingle_one
PRINT "AND FLOAT SINGLE 6:"; vfloat_zero AND vsingle_one
PRINT "AND FLOAT SINGLE 7:"; vfloat_r1 AND vsingle_r2
PRINT "AND FLOAT SINGLE 8:"; vfloat_r2 AND vsingle_r1
PRINT "AND FLOAT DOUBLE 1:"; vfloat_min AND vdouble_min
PRINT "AND FLOAT DOUBLE 2:"; vfloat_max AND vdouble_max
PRINT "AND FLOAT DOUBLE 3:"; vfloat_min AND vdouble_max
PRINT "AND FLOAT DOUBLE 4:"; vfloat_max AND vdouble_min
PRINT "AND FLOAT DOUBLE 5:"; vfloat_m1 AND vdouble_one
PRINT "AND FLOAT DOUBLE 6:"; vfloat_zero AND vdouble_one
PRINT "AND FLOAT DOUBLE 7:"; vfloat_r1 AND vdouble_r2
PRINT "AND FLOAT DOUBLE 8:"; vfloat_r2 AND vdouble_r1
PRINT "AND FLOAT FLOAT 1:"; vfloat_min AND vfloat_min
PRINT "AND FLOAT FLOAT 2:"; vfloat_max AND vfloat_max
PRINT "AND FLOAT FLOAT 3:"; vfloat_min AND vfloat_max
PRINT "AND FLOAT FLOAT 4:"; vfloat_max AND vfloat_min
PRINT "AND FLOAT FLOAT 5:"; vfloat_m1 AND vfloat_one
PRINT "AND FLOAT FLOAT 6:"; vfloat_zero AND vfloat_one
PRINT "AND FLOAT FLOAT 7:"; vfloat_r1 AND vfloat_r2
PRINT "AND FLOAT FLOAT 8:"; vfloat_r2 AND vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
