$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): MOD on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
' Left out: 12 value pairs whose divisor rounds to 0 (fatal in the old compiler, design D2).
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "MOD INTEGER INTEGER 1:"; vinteger_min MOD vinteger_min
PRINT "MOD INTEGER INTEGER 2:"; vinteger_max MOD vinteger_max
PRINT "MOD INTEGER INTEGER 3:"; vinteger_min MOD vinteger_max
PRINT "MOD INTEGER INTEGER 4:"; vinteger_max MOD vinteger_min
PRINT "MOD INTEGER INTEGER 5:"; vinteger_m1 MOD vinteger_one
PRINT "MOD INTEGER INTEGER 6:"; vinteger_zero MOD vinteger_one
PRINT "MOD INTEGER INTEGER 7:"; vinteger_r1 MOD vinteger_r2
PRINT "MOD INTEGER INTEGER 8:"; vinteger_r2 MOD vinteger_r1
PRINT "MOD INTEGER LONG 1:"; vinteger_min MOD vlong_min
PRINT "MOD INTEGER LONG 2:"; vinteger_max MOD vlong_max
PRINT "MOD INTEGER LONG 3:"; vinteger_min MOD vlong_max
PRINT "MOD INTEGER LONG 4:"; vinteger_max MOD vlong_min
PRINT "MOD INTEGER LONG 5:"; vinteger_m1 MOD vlong_one
PRINT "MOD INTEGER LONG 6:"; vinteger_zero MOD vlong_one
PRINT "MOD INTEGER LONG 7:"; vinteger_r1 MOD vlong_r2
PRINT "MOD INTEGER LONG 8:"; vinteger_r2 MOD vlong_r1
PRINT "MOD INTEGER INT64 1:"; vinteger_min MOD vint64_min
PRINT "MOD INTEGER INT64 2:"; vinteger_max MOD vint64_max
PRINT "MOD INTEGER INT64 3:"; vinteger_min MOD vint64_max
PRINT "MOD INTEGER INT64 4:"; vinteger_max MOD vint64_min
PRINT "MOD INTEGER INT64 5:"; vinteger_m1 MOD vint64_one
PRINT "MOD INTEGER INT64 6:"; vinteger_zero MOD vint64_one
PRINT "MOD INTEGER INT64 7:"; vinteger_r1 MOD vint64_r2
PRINT "MOD INTEGER INT64 8:"; vinteger_r2 MOD vint64_r1
PRINT "MOD INTEGER SINGLE 1:"; vinteger_min MOD vsingle_min
PRINT "MOD INTEGER SINGLE 2:"; vinteger_max MOD vsingle_max
PRINT "MOD INTEGER SINGLE 3:"; vinteger_min MOD vsingle_max
PRINT "MOD INTEGER SINGLE 4:"; vinteger_max MOD vsingle_min
PRINT "MOD INTEGER SINGLE 5:"; vinteger_m1 MOD vsingle_one
PRINT "MOD INTEGER SINGLE 6:"; vinteger_zero MOD vsingle_one
PRINT "MOD INTEGER DOUBLE 1:"; vinteger_min MOD vdouble_min
PRINT "MOD INTEGER DOUBLE 2:"; vinteger_max MOD vdouble_max
PRINT "MOD INTEGER DOUBLE 3:"; vinteger_min MOD vdouble_max
PRINT "MOD INTEGER DOUBLE 4:"; vinteger_max MOD vdouble_min
PRINT "MOD INTEGER DOUBLE 5:"; vinteger_m1 MOD vdouble_one
PRINT "MOD INTEGER DOUBLE 6:"; vinteger_zero MOD vdouble_one
PRINT "MOD INTEGER DOUBLE 7:"; vinteger_r1 MOD vdouble_r2
PRINT "MOD INTEGER DOUBLE 8:"; vinteger_r2 MOD vdouble_r1
PRINT "MOD INTEGER FLOAT 1:"; vinteger_min MOD vfloat_min
PRINT "MOD INTEGER FLOAT 2:"; vinteger_max MOD vfloat_max
PRINT "MOD INTEGER FLOAT 3:"; vinteger_min MOD vfloat_max
PRINT "MOD INTEGER FLOAT 4:"; vinteger_max MOD vfloat_min
PRINT "MOD INTEGER FLOAT 5:"; vinteger_m1 MOD vfloat_one
PRINT "MOD INTEGER FLOAT 6:"; vinteger_zero MOD vfloat_one
PRINT "MOD INTEGER FLOAT 7:"; vinteger_r1 MOD vfloat_r2
PRINT "MOD INTEGER FLOAT 8:"; vinteger_r2 MOD vfloat_r1
PRINT "MOD LONG INTEGER 1:"; vlong_min MOD vinteger_min
PRINT "MOD LONG INTEGER 2:"; vlong_max MOD vinteger_max
PRINT "MOD LONG INTEGER 3:"; vlong_min MOD vinteger_max
PRINT "MOD LONG INTEGER 4:"; vlong_max MOD vinteger_min
PRINT "MOD LONG INTEGER 5:"; vlong_m1 MOD vinteger_one
PRINT "MOD LONG INTEGER 6:"; vlong_zero MOD vinteger_one
PRINT "MOD LONG INTEGER 7:"; vlong_r1 MOD vinteger_r2
PRINT "MOD LONG INTEGER 8:"; vlong_r2 MOD vinteger_r1
PRINT "MOD LONG LONG 1:"; vlong_min MOD vlong_min
PRINT "MOD LONG LONG 2:"; vlong_max MOD vlong_max
PRINT "MOD LONG LONG 3:"; vlong_min MOD vlong_max
PRINT "MOD LONG LONG 4:"; vlong_max MOD vlong_min
PRINT "MOD LONG LONG 5:"; vlong_m1 MOD vlong_one
PRINT "MOD LONG LONG 6:"; vlong_zero MOD vlong_one
PRINT "MOD LONG LONG 7:"; vlong_r1 MOD vlong_r2
PRINT "MOD LONG LONG 8:"; vlong_r2 MOD vlong_r1
PRINT "MOD LONG INT64 1:"; vlong_min MOD vint64_min
PRINT "MOD LONG INT64 2:"; vlong_max MOD vint64_max
PRINT "MOD LONG INT64 3:"; vlong_min MOD vint64_max
PRINT "MOD LONG INT64 4:"; vlong_max MOD vint64_min
PRINT "MOD LONG INT64 5:"; vlong_m1 MOD vint64_one
PRINT "MOD LONG INT64 6:"; vlong_zero MOD vint64_one
PRINT "MOD LONG INT64 7:"; vlong_r1 MOD vint64_r2
PRINT "MOD LONG INT64 8:"; vlong_r2 MOD vint64_r1
PRINT "MOD LONG SINGLE 1:"; vlong_min MOD vsingle_min
PRINT "MOD LONG SINGLE 2:"; vlong_max MOD vsingle_max
PRINT "MOD LONG SINGLE 3:"; vlong_min MOD vsingle_max
PRINT "MOD LONG SINGLE 4:"; vlong_max MOD vsingle_min
PRINT "MOD LONG SINGLE 5:"; vlong_m1 MOD vsingle_one
PRINT "MOD LONG SINGLE 6:"; vlong_zero MOD vsingle_one
PRINT "MOD LONG DOUBLE 1:"; vlong_min MOD vdouble_min
PRINT "MOD LONG DOUBLE 2:"; vlong_max MOD vdouble_max
PRINT "MOD LONG DOUBLE 3:"; vlong_min MOD vdouble_max
PRINT "MOD LONG DOUBLE 4:"; vlong_max MOD vdouble_min
PRINT "MOD LONG DOUBLE 5:"; vlong_m1 MOD vdouble_one
PRINT "MOD LONG DOUBLE 6:"; vlong_zero MOD vdouble_one
PRINT "MOD LONG DOUBLE 7:"; vlong_r1 MOD vdouble_r2
PRINT "MOD LONG DOUBLE 8:"; vlong_r2 MOD vdouble_r1
PRINT "MOD LONG FLOAT 1:"; vlong_min MOD vfloat_min
PRINT "MOD LONG FLOAT 2:"; vlong_max MOD vfloat_max
PRINT "MOD LONG FLOAT 3:"; vlong_min MOD vfloat_max
PRINT "MOD LONG FLOAT 4:"; vlong_max MOD vfloat_min
PRINT "MOD LONG FLOAT 5:"; vlong_m1 MOD vfloat_one
PRINT "MOD LONG FLOAT 6:"; vlong_zero MOD vfloat_one
PRINT "MOD LONG FLOAT 7:"; vlong_r1 MOD vfloat_r2
PRINT "MOD LONG FLOAT 8:"; vlong_r2 MOD vfloat_r1
PRINT "MOD INT64 INTEGER 1:"; vint64_min MOD vinteger_min
PRINT "MOD INT64 INTEGER 2:"; vint64_max MOD vinteger_max
PRINT "MOD INT64 INTEGER 3:"; vint64_min MOD vinteger_max
PRINT "MOD INT64 INTEGER 4:"; vint64_max MOD vinteger_min
PRINT "MOD INT64 INTEGER 5:"; vint64_m1 MOD vinteger_one
PRINT "MOD INT64 INTEGER 6:"; vint64_zero MOD vinteger_one
PRINT "MOD INT64 INTEGER 7:"; vint64_r1 MOD vinteger_r2
PRINT "MOD INT64 INTEGER 8:"; vint64_r2 MOD vinteger_r1
PRINT "MOD INT64 LONG 1:"; vint64_min MOD vlong_min
PRINT "MOD INT64 LONG 2:"; vint64_max MOD vlong_max
PRINT "MOD INT64 LONG 3:"; vint64_min MOD vlong_max
PRINT "MOD INT64 LONG 4:"; vint64_max MOD vlong_min
PRINT "MOD INT64 LONG 5:"; vint64_m1 MOD vlong_one
PRINT "MOD INT64 LONG 6:"; vint64_zero MOD vlong_one
PRINT "MOD INT64 LONG 7:"; vint64_r1 MOD vlong_r2
PRINT "MOD INT64 LONG 8:"; vint64_r2 MOD vlong_r1
PRINT "MOD INT64 INT64 1:"; vint64_min MOD vint64_min
PRINT "MOD INT64 INT64 2:"; vint64_max MOD vint64_max
PRINT "MOD INT64 INT64 3:"; vint64_min MOD vint64_max
PRINT "MOD INT64 INT64 4:"; vint64_max MOD vint64_min
PRINT "MOD INT64 INT64 5:"; vint64_m1 MOD vint64_one
PRINT "MOD INT64 INT64 6:"; vint64_zero MOD vint64_one
PRINT "MOD INT64 INT64 7:"; vint64_r1 MOD vint64_r2
PRINT "MOD INT64 INT64 8:"; vint64_r2 MOD vint64_r1
PRINT "MOD INT64 SINGLE 1:"; vint64_min MOD vsingle_min
PRINT "MOD INT64 SINGLE 2:"; vint64_max MOD vsingle_max
PRINT "MOD INT64 SINGLE 3:"; vint64_min MOD vsingle_max
PRINT "MOD INT64 SINGLE 4:"; vint64_max MOD vsingle_min
PRINT "MOD INT64 SINGLE 5:"; vint64_m1 MOD vsingle_one
PRINT "MOD INT64 SINGLE 6:"; vint64_zero MOD vsingle_one
PRINT "MOD INT64 DOUBLE 1:"; vint64_min MOD vdouble_min
PRINT "MOD INT64 DOUBLE 2:"; vint64_max MOD vdouble_max
PRINT "MOD INT64 DOUBLE 3:"; vint64_min MOD vdouble_max
PRINT "MOD INT64 DOUBLE 4:"; vint64_max MOD vdouble_min
PRINT "MOD INT64 DOUBLE 5:"; vint64_m1 MOD vdouble_one
PRINT "MOD INT64 DOUBLE 6:"; vint64_zero MOD vdouble_one
PRINT "MOD INT64 DOUBLE 7:"; vint64_r1 MOD vdouble_r2
PRINT "MOD INT64 DOUBLE 8:"; vint64_r2 MOD vdouble_r1
PRINT "MOD INT64 FLOAT 1:"; vint64_min MOD vfloat_min
PRINT "MOD INT64 FLOAT 2:"; vint64_max MOD vfloat_max
PRINT "MOD INT64 FLOAT 3:"; vint64_min MOD vfloat_max
PRINT "MOD INT64 FLOAT 4:"; vint64_max MOD vfloat_min
PRINT "MOD INT64 FLOAT 5:"; vint64_m1 MOD vfloat_one
PRINT "MOD INT64 FLOAT 6:"; vint64_zero MOD vfloat_one
PRINT "MOD INT64 FLOAT 7:"; vint64_r1 MOD vfloat_r2
PRINT "MOD INT64 FLOAT 8:"; vint64_r2 MOD vfloat_r1
PRINT "MOD SINGLE INTEGER 1:"; vsingle_min MOD vinteger_min
PRINT "MOD SINGLE INTEGER 2:"; vsingle_max MOD vinteger_max
PRINT "MOD SINGLE INTEGER 3:"; vsingle_min MOD vinteger_max
PRINT "MOD SINGLE INTEGER 4:"; vsingle_max MOD vinteger_min
PRINT "MOD SINGLE INTEGER 5:"; vsingle_m1 MOD vinteger_one
PRINT "MOD SINGLE INTEGER 6:"; vsingle_zero MOD vinteger_one
PRINT "MOD SINGLE INTEGER 7:"; vsingle_r1 MOD vinteger_r2
PRINT "MOD SINGLE INTEGER 8:"; vsingle_r2 MOD vinteger_r1
PRINT "MOD SINGLE LONG 1:"; vsingle_min MOD vlong_min
PRINT "MOD SINGLE LONG 2:"; vsingle_max MOD vlong_max
PRINT "MOD SINGLE LONG 3:"; vsingle_min MOD vlong_max
PRINT "MOD SINGLE LONG 4:"; vsingle_max MOD vlong_min
PRINT "MOD SINGLE LONG 5:"; vsingle_m1 MOD vlong_one
PRINT "MOD SINGLE LONG 6:"; vsingle_zero MOD vlong_one
PRINT "MOD SINGLE LONG 7:"; vsingle_r1 MOD vlong_r2
PRINT "MOD SINGLE LONG 8:"; vsingle_r2 MOD vlong_r1
PRINT "MOD SINGLE INT64 1:"; vsingle_min MOD vint64_min
PRINT "MOD SINGLE INT64 2:"; vsingle_max MOD vint64_max
PRINT "MOD SINGLE INT64 3:"; vsingle_min MOD vint64_max
PRINT "MOD SINGLE INT64 4:"; vsingle_max MOD vint64_min
PRINT "MOD SINGLE INT64 5:"; vsingle_m1 MOD vint64_one
PRINT "MOD SINGLE INT64 6:"; vsingle_zero MOD vint64_one
PRINT "MOD SINGLE INT64 7:"; vsingle_r1 MOD vint64_r2
PRINT "MOD SINGLE INT64 8:"; vsingle_r2 MOD vint64_r1
PRINT "MOD SINGLE SINGLE 1:"; vsingle_min MOD vsingle_min
PRINT "MOD SINGLE SINGLE 2:"; vsingle_max MOD vsingle_max
PRINT "MOD SINGLE SINGLE 3:"; vsingle_min MOD vsingle_max
PRINT "MOD SINGLE SINGLE 4:"; vsingle_max MOD vsingle_min
PRINT "MOD SINGLE SINGLE 5:"; vsingle_m1 MOD vsingle_one
PRINT "MOD SINGLE SINGLE 6:"; vsingle_zero MOD vsingle_one
PRINT "MOD SINGLE DOUBLE 1:"; vsingle_min MOD vdouble_min
PRINT "MOD SINGLE DOUBLE 2:"; vsingle_max MOD vdouble_max
PRINT "MOD SINGLE DOUBLE 3:"; vsingle_min MOD vdouble_max
PRINT "MOD SINGLE DOUBLE 4:"; vsingle_max MOD vdouble_min
PRINT "MOD SINGLE DOUBLE 5:"; vsingle_m1 MOD vdouble_one
PRINT "MOD SINGLE DOUBLE 6:"; vsingle_zero MOD vdouble_one
PRINT "MOD SINGLE DOUBLE 7:"; vsingle_r1 MOD vdouble_r2
PRINT "MOD SINGLE DOUBLE 8:"; vsingle_r2 MOD vdouble_r1
PRINT "MOD SINGLE FLOAT 1:"; vsingle_min MOD vfloat_min
PRINT "MOD SINGLE FLOAT 2:"; vsingle_max MOD vfloat_max
PRINT "MOD SINGLE FLOAT 3:"; vsingle_min MOD vfloat_max
PRINT "MOD SINGLE FLOAT 4:"; vsingle_max MOD vfloat_min
PRINT "MOD SINGLE FLOAT 5:"; vsingle_m1 MOD vfloat_one
PRINT "MOD SINGLE FLOAT 6:"; vsingle_zero MOD vfloat_one
PRINT "MOD SINGLE FLOAT 7:"; vsingle_r1 MOD vfloat_r2
PRINT "MOD SINGLE FLOAT 8:"; vsingle_r2 MOD vfloat_r1
PRINT "MOD DOUBLE INTEGER 1:"; vdouble_min MOD vinteger_min
PRINT "MOD DOUBLE INTEGER 2:"; vdouble_max MOD vinteger_max
PRINT "MOD DOUBLE INTEGER 3:"; vdouble_min MOD vinteger_max
PRINT "MOD DOUBLE INTEGER 4:"; vdouble_max MOD vinteger_min
PRINT "MOD DOUBLE INTEGER 5:"; vdouble_m1 MOD vinteger_one
PRINT "MOD DOUBLE INTEGER 6:"; vdouble_zero MOD vinteger_one
PRINT "MOD DOUBLE INTEGER 7:"; vdouble_r1 MOD vinteger_r2
PRINT "MOD DOUBLE INTEGER 8:"; vdouble_r2 MOD vinteger_r1
PRINT "MOD DOUBLE LONG 1:"; vdouble_min MOD vlong_min
PRINT "MOD DOUBLE LONG 2:"; vdouble_max MOD vlong_max
PRINT "MOD DOUBLE LONG 3:"; vdouble_min MOD vlong_max
PRINT "MOD DOUBLE LONG 4:"; vdouble_max MOD vlong_min
PRINT "MOD DOUBLE LONG 5:"; vdouble_m1 MOD vlong_one
PRINT "MOD DOUBLE LONG 6:"; vdouble_zero MOD vlong_one
PRINT "MOD DOUBLE LONG 7:"; vdouble_r1 MOD vlong_r2
PRINT "MOD DOUBLE LONG 8:"; vdouble_r2 MOD vlong_r1
PRINT "MOD DOUBLE INT64 1:"; vdouble_min MOD vint64_min
PRINT "MOD DOUBLE INT64 2:"; vdouble_max MOD vint64_max
PRINT "MOD DOUBLE INT64 3:"; vdouble_min MOD vint64_max
PRINT "MOD DOUBLE INT64 4:"; vdouble_max MOD vint64_min
PRINT "MOD DOUBLE INT64 5:"; vdouble_m1 MOD vint64_one
PRINT "MOD DOUBLE INT64 6:"; vdouble_zero MOD vint64_one
PRINT "MOD DOUBLE INT64 7:"; vdouble_r1 MOD vint64_r2
PRINT "MOD DOUBLE INT64 8:"; vdouble_r2 MOD vint64_r1
PRINT "MOD DOUBLE SINGLE 1:"; vdouble_min MOD vsingle_min
PRINT "MOD DOUBLE SINGLE 2:"; vdouble_max MOD vsingle_max
PRINT "MOD DOUBLE SINGLE 3:"; vdouble_min MOD vsingle_max
PRINT "MOD DOUBLE SINGLE 4:"; vdouble_max MOD vsingle_min
PRINT "MOD DOUBLE SINGLE 5:"; vdouble_m1 MOD vsingle_one
PRINT "MOD DOUBLE SINGLE 6:"; vdouble_zero MOD vsingle_one
PRINT "MOD DOUBLE DOUBLE 1:"; vdouble_min MOD vdouble_min
PRINT "MOD DOUBLE DOUBLE 2:"; vdouble_max MOD vdouble_max
PRINT "MOD DOUBLE DOUBLE 3:"; vdouble_min MOD vdouble_max
PRINT "MOD DOUBLE DOUBLE 4:"; vdouble_max MOD vdouble_min
PRINT "MOD DOUBLE DOUBLE 5:"; vdouble_m1 MOD vdouble_one
PRINT "MOD DOUBLE DOUBLE 6:"; vdouble_zero MOD vdouble_one
PRINT "MOD DOUBLE DOUBLE 7:"; vdouble_r1 MOD vdouble_r2
PRINT "MOD DOUBLE DOUBLE 8:"; vdouble_r2 MOD vdouble_r1
PRINT "MOD DOUBLE FLOAT 1:"; vdouble_min MOD vfloat_min
PRINT "MOD DOUBLE FLOAT 2:"; vdouble_max MOD vfloat_max
PRINT "MOD DOUBLE FLOAT 3:"; vdouble_min MOD vfloat_max
PRINT "MOD DOUBLE FLOAT 4:"; vdouble_max MOD vfloat_min
PRINT "MOD DOUBLE FLOAT 5:"; vdouble_m1 MOD vfloat_one
PRINT "MOD DOUBLE FLOAT 6:"; vdouble_zero MOD vfloat_one
PRINT "MOD DOUBLE FLOAT 7:"; vdouble_r1 MOD vfloat_r2
PRINT "MOD DOUBLE FLOAT 8:"; vdouble_r2 MOD vfloat_r1
PRINT "MOD FLOAT INTEGER 1:"; vfloat_min MOD vinteger_min
PRINT "MOD FLOAT INTEGER 2:"; vfloat_max MOD vinteger_max
PRINT "MOD FLOAT INTEGER 3:"; vfloat_min MOD vinteger_max
PRINT "MOD FLOAT INTEGER 4:"; vfloat_max MOD vinteger_min
PRINT "MOD FLOAT INTEGER 5:"; vfloat_m1 MOD vinteger_one
PRINT "MOD FLOAT INTEGER 6:"; vfloat_zero MOD vinteger_one
PRINT "MOD FLOAT INTEGER 7:"; vfloat_r1 MOD vinteger_r2
PRINT "MOD FLOAT INTEGER 8:"; vfloat_r2 MOD vinteger_r1
PRINT "MOD FLOAT LONG 1:"; vfloat_min MOD vlong_min
PRINT "MOD FLOAT LONG 2:"; vfloat_max MOD vlong_max
PRINT "MOD FLOAT LONG 3:"; vfloat_min MOD vlong_max
PRINT "MOD FLOAT LONG 4:"; vfloat_max MOD vlong_min
PRINT "MOD FLOAT LONG 5:"; vfloat_m1 MOD vlong_one
PRINT "MOD FLOAT LONG 6:"; vfloat_zero MOD vlong_one
PRINT "MOD FLOAT LONG 7:"; vfloat_r1 MOD vlong_r2
PRINT "MOD FLOAT LONG 8:"; vfloat_r2 MOD vlong_r1
PRINT "MOD FLOAT INT64 1:"; vfloat_min MOD vint64_min
PRINT "MOD FLOAT INT64 2:"; vfloat_max MOD vint64_max
PRINT "MOD FLOAT INT64 3:"; vfloat_min MOD vint64_max
PRINT "MOD FLOAT INT64 4:"; vfloat_max MOD vint64_min
PRINT "MOD FLOAT INT64 5:"; vfloat_m1 MOD vint64_one
PRINT "MOD FLOAT INT64 6:"; vfloat_zero MOD vint64_one
PRINT "MOD FLOAT INT64 7:"; vfloat_r1 MOD vint64_r2
PRINT "MOD FLOAT INT64 8:"; vfloat_r2 MOD vint64_r1
PRINT "MOD FLOAT SINGLE 1:"; vfloat_min MOD vsingle_min
PRINT "MOD FLOAT SINGLE 2:"; vfloat_max MOD vsingle_max
PRINT "MOD FLOAT SINGLE 3:"; vfloat_min MOD vsingle_max
PRINT "MOD FLOAT SINGLE 4:"; vfloat_max MOD vsingle_min
PRINT "MOD FLOAT SINGLE 5:"; vfloat_m1 MOD vsingle_one
PRINT "MOD FLOAT SINGLE 6:"; vfloat_zero MOD vsingle_one
PRINT "MOD FLOAT DOUBLE 1:"; vfloat_min MOD vdouble_min
PRINT "MOD FLOAT DOUBLE 2:"; vfloat_max MOD vdouble_max
PRINT "MOD FLOAT DOUBLE 3:"; vfloat_min MOD vdouble_max
PRINT "MOD FLOAT DOUBLE 4:"; vfloat_max MOD vdouble_min
PRINT "MOD FLOAT DOUBLE 5:"; vfloat_m1 MOD vdouble_one
PRINT "MOD FLOAT DOUBLE 6:"; vfloat_zero MOD vdouble_one
PRINT "MOD FLOAT DOUBLE 7:"; vfloat_r1 MOD vdouble_r2
PRINT "MOD FLOAT DOUBLE 8:"; vfloat_r2 MOD vdouble_r1
PRINT "MOD FLOAT FLOAT 1:"; vfloat_min MOD vfloat_min
PRINT "MOD FLOAT FLOAT 2:"; vfloat_max MOD vfloat_max
PRINT "MOD FLOAT FLOAT 3:"; vfloat_min MOD vfloat_max
PRINT "MOD FLOAT FLOAT 4:"; vfloat_max MOD vfloat_min
PRINT "MOD FLOAT FLOAT 5:"; vfloat_m1 MOD vfloat_one
PRINT "MOD FLOAT FLOAT 6:"; vfloat_zero MOD vfloat_one
PRINT "MOD FLOAT FLOAT 7:"; vfloat_r1 MOD vfloat_r2
PRINT "MOD FLOAT FLOAT 8:"; vfloat_r2 MOD vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
