$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): _ANDALSO on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "_ANDALSO INTEGER INTEGER 1:"; vinteger_min _ANDALSO vinteger_min
PRINT "_ANDALSO INTEGER INTEGER 2:"; vinteger_max _ANDALSO vinteger_max
PRINT "_ANDALSO INTEGER INTEGER 3:"; vinteger_min _ANDALSO vinteger_max
PRINT "_ANDALSO INTEGER INTEGER 4:"; vinteger_max _ANDALSO vinteger_min
PRINT "_ANDALSO INTEGER INTEGER 5:"; vinteger_m1 _ANDALSO vinteger_one
PRINT "_ANDALSO INTEGER INTEGER 6:"; vinteger_zero _ANDALSO vinteger_one
PRINT "_ANDALSO INTEGER INTEGER 7:"; vinteger_r1 _ANDALSO vinteger_r2
PRINT "_ANDALSO INTEGER INTEGER 8:"; vinteger_r2 _ANDALSO vinteger_r1
PRINT "_ANDALSO INTEGER LONG 1:"; vinteger_min _ANDALSO vlong_min
PRINT "_ANDALSO INTEGER LONG 2:"; vinteger_max _ANDALSO vlong_max
PRINT "_ANDALSO INTEGER LONG 3:"; vinteger_min _ANDALSO vlong_max
PRINT "_ANDALSO INTEGER LONG 4:"; vinteger_max _ANDALSO vlong_min
PRINT "_ANDALSO INTEGER LONG 5:"; vinteger_m1 _ANDALSO vlong_one
PRINT "_ANDALSO INTEGER LONG 6:"; vinteger_zero _ANDALSO vlong_one
PRINT "_ANDALSO INTEGER LONG 7:"; vinteger_r1 _ANDALSO vlong_r2
PRINT "_ANDALSO INTEGER LONG 8:"; vinteger_r2 _ANDALSO vlong_r1
PRINT "_ANDALSO INTEGER INT64 1:"; vinteger_min _ANDALSO vint64_min
PRINT "_ANDALSO INTEGER INT64 2:"; vinteger_max _ANDALSO vint64_max
PRINT "_ANDALSO INTEGER INT64 3:"; vinteger_min _ANDALSO vint64_max
PRINT "_ANDALSO INTEGER INT64 4:"; vinteger_max _ANDALSO vint64_min
PRINT "_ANDALSO INTEGER INT64 5:"; vinteger_m1 _ANDALSO vint64_one
PRINT "_ANDALSO INTEGER INT64 6:"; vinteger_zero _ANDALSO vint64_one
PRINT "_ANDALSO INTEGER INT64 7:"; vinteger_r1 _ANDALSO vint64_r2
PRINT "_ANDALSO INTEGER INT64 8:"; vinteger_r2 _ANDALSO vint64_r1
PRINT "_ANDALSO INTEGER SINGLE 1:"; vinteger_min _ANDALSO vsingle_min
PRINT "_ANDALSO INTEGER SINGLE 2:"; vinteger_max _ANDALSO vsingle_max
PRINT "_ANDALSO INTEGER SINGLE 3:"; vinteger_min _ANDALSO vsingle_max
PRINT "_ANDALSO INTEGER SINGLE 4:"; vinteger_max _ANDALSO vsingle_min
PRINT "_ANDALSO INTEGER SINGLE 5:"; vinteger_m1 _ANDALSO vsingle_one
PRINT "_ANDALSO INTEGER SINGLE 6:"; vinteger_zero _ANDALSO vsingle_one
PRINT "_ANDALSO INTEGER SINGLE 7:"; vinteger_r1 _ANDALSO vsingle_r2
PRINT "_ANDALSO INTEGER SINGLE 8:"; vinteger_r2 _ANDALSO vsingle_r1
PRINT "_ANDALSO INTEGER DOUBLE 1:"; vinteger_min _ANDALSO vdouble_min
PRINT "_ANDALSO INTEGER DOUBLE 2:"; vinteger_max _ANDALSO vdouble_max
PRINT "_ANDALSO INTEGER DOUBLE 3:"; vinteger_min _ANDALSO vdouble_max
PRINT "_ANDALSO INTEGER DOUBLE 4:"; vinteger_max _ANDALSO vdouble_min
PRINT "_ANDALSO INTEGER DOUBLE 5:"; vinteger_m1 _ANDALSO vdouble_one
PRINT "_ANDALSO INTEGER DOUBLE 6:"; vinteger_zero _ANDALSO vdouble_one
PRINT "_ANDALSO INTEGER DOUBLE 7:"; vinteger_r1 _ANDALSO vdouble_r2
PRINT "_ANDALSO INTEGER DOUBLE 8:"; vinteger_r2 _ANDALSO vdouble_r1
PRINT "_ANDALSO INTEGER FLOAT 1:"; vinteger_min _ANDALSO vfloat_min
PRINT "_ANDALSO INTEGER FLOAT 2:"; vinteger_max _ANDALSO vfloat_max
PRINT "_ANDALSO INTEGER FLOAT 3:"; vinteger_min _ANDALSO vfloat_max
PRINT "_ANDALSO INTEGER FLOAT 4:"; vinteger_max _ANDALSO vfloat_min
PRINT "_ANDALSO INTEGER FLOAT 5:"; vinteger_m1 _ANDALSO vfloat_one
PRINT "_ANDALSO INTEGER FLOAT 6:"; vinteger_zero _ANDALSO vfloat_one
PRINT "_ANDALSO INTEGER FLOAT 7:"; vinteger_r1 _ANDALSO vfloat_r2
PRINT "_ANDALSO INTEGER FLOAT 8:"; vinteger_r2 _ANDALSO vfloat_r1
PRINT "_ANDALSO LONG INTEGER 1:"; vlong_min _ANDALSO vinteger_min
PRINT "_ANDALSO LONG INTEGER 2:"; vlong_max _ANDALSO vinteger_max
PRINT "_ANDALSO LONG INTEGER 3:"; vlong_min _ANDALSO vinteger_max
PRINT "_ANDALSO LONG INTEGER 4:"; vlong_max _ANDALSO vinteger_min
PRINT "_ANDALSO LONG INTEGER 5:"; vlong_m1 _ANDALSO vinteger_one
PRINT "_ANDALSO LONG INTEGER 6:"; vlong_zero _ANDALSO vinteger_one
PRINT "_ANDALSO LONG INTEGER 7:"; vlong_r1 _ANDALSO vinteger_r2
PRINT "_ANDALSO LONG INTEGER 8:"; vlong_r2 _ANDALSO vinteger_r1
PRINT "_ANDALSO LONG LONG 1:"; vlong_min _ANDALSO vlong_min
PRINT "_ANDALSO LONG LONG 2:"; vlong_max _ANDALSO vlong_max
PRINT "_ANDALSO LONG LONG 3:"; vlong_min _ANDALSO vlong_max
PRINT "_ANDALSO LONG LONG 4:"; vlong_max _ANDALSO vlong_min
PRINT "_ANDALSO LONG LONG 5:"; vlong_m1 _ANDALSO vlong_one
PRINT "_ANDALSO LONG LONG 6:"; vlong_zero _ANDALSO vlong_one
PRINT "_ANDALSO LONG LONG 7:"; vlong_r1 _ANDALSO vlong_r2
PRINT "_ANDALSO LONG LONG 8:"; vlong_r2 _ANDALSO vlong_r1
PRINT "_ANDALSO LONG INT64 1:"; vlong_min _ANDALSO vint64_min
PRINT "_ANDALSO LONG INT64 2:"; vlong_max _ANDALSO vint64_max
PRINT "_ANDALSO LONG INT64 3:"; vlong_min _ANDALSO vint64_max
PRINT "_ANDALSO LONG INT64 4:"; vlong_max _ANDALSO vint64_min
PRINT "_ANDALSO LONG INT64 5:"; vlong_m1 _ANDALSO vint64_one
PRINT "_ANDALSO LONG INT64 6:"; vlong_zero _ANDALSO vint64_one
PRINT "_ANDALSO LONG INT64 7:"; vlong_r1 _ANDALSO vint64_r2
PRINT "_ANDALSO LONG INT64 8:"; vlong_r2 _ANDALSO vint64_r1
PRINT "_ANDALSO LONG SINGLE 1:"; vlong_min _ANDALSO vsingle_min
PRINT "_ANDALSO LONG SINGLE 2:"; vlong_max _ANDALSO vsingle_max
PRINT "_ANDALSO LONG SINGLE 3:"; vlong_min _ANDALSO vsingle_max
PRINT "_ANDALSO LONG SINGLE 4:"; vlong_max _ANDALSO vsingle_min
PRINT "_ANDALSO LONG SINGLE 5:"; vlong_m1 _ANDALSO vsingle_one
PRINT "_ANDALSO LONG SINGLE 6:"; vlong_zero _ANDALSO vsingle_one
PRINT "_ANDALSO LONG SINGLE 7:"; vlong_r1 _ANDALSO vsingle_r2
PRINT "_ANDALSO LONG SINGLE 8:"; vlong_r2 _ANDALSO vsingle_r1
PRINT "_ANDALSO LONG DOUBLE 1:"; vlong_min _ANDALSO vdouble_min
PRINT "_ANDALSO LONG DOUBLE 2:"; vlong_max _ANDALSO vdouble_max
PRINT "_ANDALSO LONG DOUBLE 3:"; vlong_min _ANDALSO vdouble_max
PRINT "_ANDALSO LONG DOUBLE 4:"; vlong_max _ANDALSO vdouble_min
PRINT "_ANDALSO LONG DOUBLE 5:"; vlong_m1 _ANDALSO vdouble_one
PRINT "_ANDALSO LONG DOUBLE 6:"; vlong_zero _ANDALSO vdouble_one
PRINT "_ANDALSO LONG DOUBLE 7:"; vlong_r1 _ANDALSO vdouble_r2
PRINT "_ANDALSO LONG DOUBLE 8:"; vlong_r2 _ANDALSO vdouble_r1
PRINT "_ANDALSO LONG FLOAT 1:"; vlong_min _ANDALSO vfloat_min
PRINT "_ANDALSO LONG FLOAT 2:"; vlong_max _ANDALSO vfloat_max
PRINT "_ANDALSO LONG FLOAT 3:"; vlong_min _ANDALSO vfloat_max
PRINT "_ANDALSO LONG FLOAT 4:"; vlong_max _ANDALSO vfloat_min
PRINT "_ANDALSO LONG FLOAT 5:"; vlong_m1 _ANDALSO vfloat_one
PRINT "_ANDALSO LONG FLOAT 6:"; vlong_zero _ANDALSO vfloat_one
PRINT "_ANDALSO LONG FLOAT 7:"; vlong_r1 _ANDALSO vfloat_r2
PRINT "_ANDALSO LONG FLOAT 8:"; vlong_r2 _ANDALSO vfloat_r1
PRINT "_ANDALSO INT64 INTEGER 1:"; vint64_min _ANDALSO vinteger_min
PRINT "_ANDALSO INT64 INTEGER 2:"; vint64_max _ANDALSO vinteger_max
PRINT "_ANDALSO INT64 INTEGER 3:"; vint64_min _ANDALSO vinteger_max
PRINT "_ANDALSO INT64 INTEGER 4:"; vint64_max _ANDALSO vinteger_min
PRINT "_ANDALSO INT64 INTEGER 5:"; vint64_m1 _ANDALSO vinteger_one
PRINT "_ANDALSO INT64 INTEGER 6:"; vint64_zero _ANDALSO vinteger_one
PRINT "_ANDALSO INT64 INTEGER 7:"; vint64_r1 _ANDALSO vinteger_r2
PRINT "_ANDALSO INT64 INTEGER 8:"; vint64_r2 _ANDALSO vinteger_r1
PRINT "_ANDALSO INT64 LONG 1:"; vint64_min _ANDALSO vlong_min
PRINT "_ANDALSO INT64 LONG 2:"; vint64_max _ANDALSO vlong_max
PRINT "_ANDALSO INT64 LONG 3:"; vint64_min _ANDALSO vlong_max
PRINT "_ANDALSO INT64 LONG 4:"; vint64_max _ANDALSO vlong_min
PRINT "_ANDALSO INT64 LONG 5:"; vint64_m1 _ANDALSO vlong_one
PRINT "_ANDALSO INT64 LONG 6:"; vint64_zero _ANDALSO vlong_one
PRINT "_ANDALSO INT64 LONG 7:"; vint64_r1 _ANDALSO vlong_r2
PRINT "_ANDALSO INT64 LONG 8:"; vint64_r2 _ANDALSO vlong_r1
PRINT "_ANDALSO INT64 INT64 1:"; vint64_min _ANDALSO vint64_min
PRINT "_ANDALSO INT64 INT64 2:"; vint64_max _ANDALSO vint64_max
PRINT "_ANDALSO INT64 INT64 3:"; vint64_min _ANDALSO vint64_max
PRINT "_ANDALSO INT64 INT64 4:"; vint64_max _ANDALSO vint64_min
PRINT "_ANDALSO INT64 INT64 5:"; vint64_m1 _ANDALSO vint64_one
PRINT "_ANDALSO INT64 INT64 6:"; vint64_zero _ANDALSO vint64_one
PRINT "_ANDALSO INT64 INT64 7:"; vint64_r1 _ANDALSO vint64_r2
PRINT "_ANDALSO INT64 INT64 8:"; vint64_r2 _ANDALSO vint64_r1
PRINT "_ANDALSO INT64 SINGLE 1:"; vint64_min _ANDALSO vsingle_min
PRINT "_ANDALSO INT64 SINGLE 2:"; vint64_max _ANDALSO vsingle_max
PRINT "_ANDALSO INT64 SINGLE 3:"; vint64_min _ANDALSO vsingle_max
PRINT "_ANDALSO INT64 SINGLE 4:"; vint64_max _ANDALSO vsingle_min
PRINT "_ANDALSO INT64 SINGLE 5:"; vint64_m1 _ANDALSO vsingle_one
PRINT "_ANDALSO INT64 SINGLE 6:"; vint64_zero _ANDALSO vsingle_one
PRINT "_ANDALSO INT64 SINGLE 7:"; vint64_r1 _ANDALSO vsingle_r2
PRINT "_ANDALSO INT64 SINGLE 8:"; vint64_r2 _ANDALSO vsingle_r1
PRINT "_ANDALSO INT64 DOUBLE 1:"; vint64_min _ANDALSO vdouble_min
PRINT "_ANDALSO INT64 DOUBLE 2:"; vint64_max _ANDALSO vdouble_max
PRINT "_ANDALSO INT64 DOUBLE 3:"; vint64_min _ANDALSO vdouble_max
PRINT "_ANDALSO INT64 DOUBLE 4:"; vint64_max _ANDALSO vdouble_min
PRINT "_ANDALSO INT64 DOUBLE 5:"; vint64_m1 _ANDALSO vdouble_one
PRINT "_ANDALSO INT64 DOUBLE 6:"; vint64_zero _ANDALSO vdouble_one
PRINT "_ANDALSO INT64 DOUBLE 7:"; vint64_r1 _ANDALSO vdouble_r2
PRINT "_ANDALSO INT64 DOUBLE 8:"; vint64_r2 _ANDALSO vdouble_r1
PRINT "_ANDALSO INT64 FLOAT 1:"; vint64_min _ANDALSO vfloat_min
PRINT "_ANDALSO INT64 FLOAT 2:"; vint64_max _ANDALSO vfloat_max
PRINT "_ANDALSO INT64 FLOAT 3:"; vint64_min _ANDALSO vfloat_max
PRINT "_ANDALSO INT64 FLOAT 4:"; vint64_max _ANDALSO vfloat_min
PRINT "_ANDALSO INT64 FLOAT 5:"; vint64_m1 _ANDALSO vfloat_one
PRINT "_ANDALSO INT64 FLOAT 6:"; vint64_zero _ANDALSO vfloat_one
PRINT "_ANDALSO INT64 FLOAT 7:"; vint64_r1 _ANDALSO vfloat_r2
PRINT "_ANDALSO INT64 FLOAT 8:"; vint64_r2 _ANDALSO vfloat_r1
PRINT "_ANDALSO SINGLE INTEGER 1:"; vsingle_min _ANDALSO vinteger_min
PRINT "_ANDALSO SINGLE INTEGER 2:"; vsingle_max _ANDALSO vinteger_max
PRINT "_ANDALSO SINGLE INTEGER 3:"; vsingle_min _ANDALSO vinteger_max
PRINT "_ANDALSO SINGLE INTEGER 4:"; vsingle_max _ANDALSO vinteger_min
PRINT "_ANDALSO SINGLE INTEGER 5:"; vsingle_m1 _ANDALSO vinteger_one
PRINT "_ANDALSO SINGLE INTEGER 6:"; vsingle_zero _ANDALSO vinteger_one
PRINT "_ANDALSO SINGLE INTEGER 7:"; vsingle_r1 _ANDALSO vinteger_r2
PRINT "_ANDALSO SINGLE INTEGER 8:"; vsingle_r2 _ANDALSO vinteger_r1
PRINT "_ANDALSO SINGLE LONG 1:"; vsingle_min _ANDALSO vlong_min
PRINT "_ANDALSO SINGLE LONG 2:"; vsingle_max _ANDALSO vlong_max
PRINT "_ANDALSO SINGLE LONG 3:"; vsingle_min _ANDALSO vlong_max
PRINT "_ANDALSO SINGLE LONG 4:"; vsingle_max _ANDALSO vlong_min
PRINT "_ANDALSO SINGLE LONG 5:"; vsingle_m1 _ANDALSO vlong_one
PRINT "_ANDALSO SINGLE LONG 6:"; vsingle_zero _ANDALSO vlong_one
PRINT "_ANDALSO SINGLE LONG 7:"; vsingle_r1 _ANDALSO vlong_r2
PRINT "_ANDALSO SINGLE LONG 8:"; vsingle_r2 _ANDALSO vlong_r1
PRINT "_ANDALSO SINGLE INT64 1:"; vsingle_min _ANDALSO vint64_min
PRINT "_ANDALSO SINGLE INT64 2:"; vsingle_max _ANDALSO vint64_max
PRINT "_ANDALSO SINGLE INT64 3:"; vsingle_min _ANDALSO vint64_max
PRINT "_ANDALSO SINGLE INT64 4:"; vsingle_max _ANDALSO vint64_min
PRINT "_ANDALSO SINGLE INT64 5:"; vsingle_m1 _ANDALSO vint64_one
PRINT "_ANDALSO SINGLE INT64 6:"; vsingle_zero _ANDALSO vint64_one
PRINT "_ANDALSO SINGLE INT64 7:"; vsingle_r1 _ANDALSO vint64_r2
PRINT "_ANDALSO SINGLE INT64 8:"; vsingle_r2 _ANDALSO vint64_r1
PRINT "_ANDALSO SINGLE SINGLE 1:"; vsingle_min _ANDALSO vsingle_min
PRINT "_ANDALSO SINGLE SINGLE 2:"; vsingle_max _ANDALSO vsingle_max
PRINT "_ANDALSO SINGLE SINGLE 3:"; vsingle_min _ANDALSO vsingle_max
PRINT "_ANDALSO SINGLE SINGLE 4:"; vsingle_max _ANDALSO vsingle_min
PRINT "_ANDALSO SINGLE SINGLE 5:"; vsingle_m1 _ANDALSO vsingle_one
PRINT "_ANDALSO SINGLE SINGLE 6:"; vsingle_zero _ANDALSO vsingle_one
PRINT "_ANDALSO SINGLE SINGLE 7:"; vsingle_r1 _ANDALSO vsingle_r2
PRINT "_ANDALSO SINGLE SINGLE 8:"; vsingle_r2 _ANDALSO vsingle_r1
PRINT "_ANDALSO SINGLE DOUBLE 1:"; vsingle_min _ANDALSO vdouble_min
PRINT "_ANDALSO SINGLE DOUBLE 2:"; vsingle_max _ANDALSO vdouble_max
PRINT "_ANDALSO SINGLE DOUBLE 3:"; vsingle_min _ANDALSO vdouble_max
PRINT "_ANDALSO SINGLE DOUBLE 4:"; vsingle_max _ANDALSO vdouble_min
PRINT "_ANDALSO SINGLE DOUBLE 5:"; vsingle_m1 _ANDALSO vdouble_one
PRINT "_ANDALSO SINGLE DOUBLE 6:"; vsingle_zero _ANDALSO vdouble_one
PRINT "_ANDALSO SINGLE DOUBLE 7:"; vsingle_r1 _ANDALSO vdouble_r2
PRINT "_ANDALSO SINGLE DOUBLE 8:"; vsingle_r2 _ANDALSO vdouble_r1
PRINT "_ANDALSO SINGLE FLOAT 1:"; vsingle_min _ANDALSO vfloat_min
PRINT "_ANDALSO SINGLE FLOAT 2:"; vsingle_max _ANDALSO vfloat_max
PRINT "_ANDALSO SINGLE FLOAT 3:"; vsingle_min _ANDALSO vfloat_max
PRINT "_ANDALSO SINGLE FLOAT 4:"; vsingle_max _ANDALSO vfloat_min
PRINT "_ANDALSO SINGLE FLOAT 5:"; vsingle_m1 _ANDALSO vfloat_one
PRINT "_ANDALSO SINGLE FLOAT 6:"; vsingle_zero _ANDALSO vfloat_one
PRINT "_ANDALSO SINGLE FLOAT 7:"; vsingle_r1 _ANDALSO vfloat_r2
PRINT "_ANDALSO SINGLE FLOAT 8:"; vsingle_r2 _ANDALSO vfloat_r1
PRINT "_ANDALSO DOUBLE INTEGER 1:"; vdouble_min _ANDALSO vinteger_min
PRINT "_ANDALSO DOUBLE INTEGER 2:"; vdouble_max _ANDALSO vinteger_max
PRINT "_ANDALSO DOUBLE INTEGER 3:"; vdouble_min _ANDALSO vinteger_max
PRINT "_ANDALSO DOUBLE INTEGER 4:"; vdouble_max _ANDALSO vinteger_min
PRINT "_ANDALSO DOUBLE INTEGER 5:"; vdouble_m1 _ANDALSO vinteger_one
PRINT "_ANDALSO DOUBLE INTEGER 6:"; vdouble_zero _ANDALSO vinteger_one
PRINT "_ANDALSO DOUBLE INTEGER 7:"; vdouble_r1 _ANDALSO vinteger_r2
PRINT "_ANDALSO DOUBLE INTEGER 8:"; vdouble_r2 _ANDALSO vinteger_r1
PRINT "_ANDALSO DOUBLE LONG 1:"; vdouble_min _ANDALSO vlong_min
PRINT "_ANDALSO DOUBLE LONG 2:"; vdouble_max _ANDALSO vlong_max
PRINT "_ANDALSO DOUBLE LONG 3:"; vdouble_min _ANDALSO vlong_max
PRINT "_ANDALSO DOUBLE LONG 4:"; vdouble_max _ANDALSO vlong_min
PRINT "_ANDALSO DOUBLE LONG 5:"; vdouble_m1 _ANDALSO vlong_one
PRINT "_ANDALSO DOUBLE LONG 6:"; vdouble_zero _ANDALSO vlong_one
PRINT "_ANDALSO DOUBLE LONG 7:"; vdouble_r1 _ANDALSO vlong_r2
PRINT "_ANDALSO DOUBLE LONG 8:"; vdouble_r2 _ANDALSO vlong_r1
PRINT "_ANDALSO DOUBLE INT64 1:"; vdouble_min _ANDALSO vint64_min
PRINT "_ANDALSO DOUBLE INT64 2:"; vdouble_max _ANDALSO vint64_max
PRINT "_ANDALSO DOUBLE INT64 3:"; vdouble_min _ANDALSO vint64_max
PRINT "_ANDALSO DOUBLE INT64 4:"; vdouble_max _ANDALSO vint64_min
PRINT "_ANDALSO DOUBLE INT64 5:"; vdouble_m1 _ANDALSO vint64_one
PRINT "_ANDALSO DOUBLE INT64 6:"; vdouble_zero _ANDALSO vint64_one
PRINT "_ANDALSO DOUBLE INT64 7:"; vdouble_r1 _ANDALSO vint64_r2
PRINT "_ANDALSO DOUBLE INT64 8:"; vdouble_r2 _ANDALSO vint64_r1
PRINT "_ANDALSO DOUBLE SINGLE 1:"; vdouble_min _ANDALSO vsingle_min
PRINT "_ANDALSO DOUBLE SINGLE 2:"; vdouble_max _ANDALSO vsingle_max
PRINT "_ANDALSO DOUBLE SINGLE 3:"; vdouble_min _ANDALSO vsingle_max
PRINT "_ANDALSO DOUBLE SINGLE 4:"; vdouble_max _ANDALSO vsingle_min
PRINT "_ANDALSO DOUBLE SINGLE 5:"; vdouble_m1 _ANDALSO vsingle_one
PRINT "_ANDALSO DOUBLE SINGLE 6:"; vdouble_zero _ANDALSO vsingle_one
PRINT "_ANDALSO DOUBLE SINGLE 7:"; vdouble_r1 _ANDALSO vsingle_r2
PRINT "_ANDALSO DOUBLE SINGLE 8:"; vdouble_r2 _ANDALSO vsingle_r1
PRINT "_ANDALSO DOUBLE DOUBLE 1:"; vdouble_min _ANDALSO vdouble_min
PRINT "_ANDALSO DOUBLE DOUBLE 2:"; vdouble_max _ANDALSO vdouble_max
PRINT "_ANDALSO DOUBLE DOUBLE 3:"; vdouble_min _ANDALSO vdouble_max
PRINT "_ANDALSO DOUBLE DOUBLE 4:"; vdouble_max _ANDALSO vdouble_min
PRINT "_ANDALSO DOUBLE DOUBLE 5:"; vdouble_m1 _ANDALSO vdouble_one
PRINT "_ANDALSO DOUBLE DOUBLE 6:"; vdouble_zero _ANDALSO vdouble_one
PRINT "_ANDALSO DOUBLE DOUBLE 7:"; vdouble_r1 _ANDALSO vdouble_r2
PRINT "_ANDALSO DOUBLE DOUBLE 8:"; vdouble_r2 _ANDALSO vdouble_r1
PRINT "_ANDALSO DOUBLE FLOAT 1:"; vdouble_min _ANDALSO vfloat_min
PRINT "_ANDALSO DOUBLE FLOAT 2:"; vdouble_max _ANDALSO vfloat_max
PRINT "_ANDALSO DOUBLE FLOAT 3:"; vdouble_min _ANDALSO vfloat_max
PRINT "_ANDALSO DOUBLE FLOAT 4:"; vdouble_max _ANDALSO vfloat_min
PRINT "_ANDALSO DOUBLE FLOAT 5:"; vdouble_m1 _ANDALSO vfloat_one
PRINT "_ANDALSO DOUBLE FLOAT 6:"; vdouble_zero _ANDALSO vfloat_one
PRINT "_ANDALSO DOUBLE FLOAT 7:"; vdouble_r1 _ANDALSO vfloat_r2
PRINT "_ANDALSO DOUBLE FLOAT 8:"; vdouble_r2 _ANDALSO vfloat_r1
PRINT "_ANDALSO FLOAT INTEGER 1:"; vfloat_min _ANDALSO vinteger_min
PRINT "_ANDALSO FLOAT INTEGER 2:"; vfloat_max _ANDALSO vinteger_max
PRINT "_ANDALSO FLOAT INTEGER 3:"; vfloat_min _ANDALSO vinteger_max
PRINT "_ANDALSO FLOAT INTEGER 4:"; vfloat_max _ANDALSO vinteger_min
PRINT "_ANDALSO FLOAT INTEGER 5:"; vfloat_m1 _ANDALSO vinteger_one
PRINT "_ANDALSO FLOAT INTEGER 6:"; vfloat_zero _ANDALSO vinteger_one
PRINT "_ANDALSO FLOAT INTEGER 7:"; vfloat_r1 _ANDALSO vinteger_r2
PRINT "_ANDALSO FLOAT INTEGER 8:"; vfloat_r2 _ANDALSO vinteger_r1
PRINT "_ANDALSO FLOAT LONG 1:"; vfloat_min _ANDALSO vlong_min
PRINT "_ANDALSO FLOAT LONG 2:"; vfloat_max _ANDALSO vlong_max
PRINT "_ANDALSO FLOAT LONG 3:"; vfloat_min _ANDALSO vlong_max
PRINT "_ANDALSO FLOAT LONG 4:"; vfloat_max _ANDALSO vlong_min
PRINT "_ANDALSO FLOAT LONG 5:"; vfloat_m1 _ANDALSO vlong_one
PRINT "_ANDALSO FLOAT LONG 6:"; vfloat_zero _ANDALSO vlong_one
PRINT "_ANDALSO FLOAT LONG 7:"; vfloat_r1 _ANDALSO vlong_r2
PRINT "_ANDALSO FLOAT LONG 8:"; vfloat_r2 _ANDALSO vlong_r1
PRINT "_ANDALSO FLOAT INT64 1:"; vfloat_min _ANDALSO vint64_min
PRINT "_ANDALSO FLOAT INT64 2:"; vfloat_max _ANDALSO vint64_max
PRINT "_ANDALSO FLOAT INT64 3:"; vfloat_min _ANDALSO vint64_max
PRINT "_ANDALSO FLOAT INT64 4:"; vfloat_max _ANDALSO vint64_min
PRINT "_ANDALSO FLOAT INT64 5:"; vfloat_m1 _ANDALSO vint64_one
PRINT "_ANDALSO FLOAT INT64 6:"; vfloat_zero _ANDALSO vint64_one
PRINT "_ANDALSO FLOAT INT64 7:"; vfloat_r1 _ANDALSO vint64_r2
PRINT "_ANDALSO FLOAT INT64 8:"; vfloat_r2 _ANDALSO vint64_r1
PRINT "_ANDALSO FLOAT SINGLE 1:"; vfloat_min _ANDALSO vsingle_min
PRINT "_ANDALSO FLOAT SINGLE 2:"; vfloat_max _ANDALSO vsingle_max
PRINT "_ANDALSO FLOAT SINGLE 3:"; vfloat_min _ANDALSO vsingle_max
PRINT "_ANDALSO FLOAT SINGLE 4:"; vfloat_max _ANDALSO vsingle_min
PRINT "_ANDALSO FLOAT SINGLE 5:"; vfloat_m1 _ANDALSO vsingle_one
PRINT "_ANDALSO FLOAT SINGLE 6:"; vfloat_zero _ANDALSO vsingle_one
PRINT "_ANDALSO FLOAT SINGLE 7:"; vfloat_r1 _ANDALSO vsingle_r2
PRINT "_ANDALSO FLOAT SINGLE 8:"; vfloat_r2 _ANDALSO vsingle_r1
PRINT "_ANDALSO FLOAT DOUBLE 1:"; vfloat_min _ANDALSO vdouble_min
PRINT "_ANDALSO FLOAT DOUBLE 2:"; vfloat_max _ANDALSO vdouble_max
PRINT "_ANDALSO FLOAT DOUBLE 3:"; vfloat_min _ANDALSO vdouble_max
PRINT "_ANDALSO FLOAT DOUBLE 4:"; vfloat_max _ANDALSO vdouble_min
PRINT "_ANDALSO FLOAT DOUBLE 5:"; vfloat_m1 _ANDALSO vdouble_one
PRINT "_ANDALSO FLOAT DOUBLE 6:"; vfloat_zero _ANDALSO vdouble_one
PRINT "_ANDALSO FLOAT DOUBLE 7:"; vfloat_r1 _ANDALSO vdouble_r2
PRINT "_ANDALSO FLOAT DOUBLE 8:"; vfloat_r2 _ANDALSO vdouble_r1
PRINT "_ANDALSO FLOAT FLOAT 1:"; vfloat_min _ANDALSO vfloat_min
PRINT "_ANDALSO FLOAT FLOAT 2:"; vfloat_max _ANDALSO vfloat_max
PRINT "_ANDALSO FLOAT FLOAT 3:"; vfloat_min _ANDALSO vfloat_max
PRINT "_ANDALSO FLOAT FLOAT 4:"; vfloat_max _ANDALSO vfloat_min
PRINT "_ANDALSO FLOAT FLOAT 5:"; vfloat_m1 _ANDALSO vfloat_one
PRINT "_ANDALSO FLOAT FLOAT 6:"; vfloat_zero _ANDALSO vfloat_one
PRINT "_ANDALSO FLOAT FLOAT 7:"; vfloat_r1 _ANDALSO vfloat_r2
PRINT "_ANDALSO FLOAT FLOAT 8:"; vfloat_r2 _ANDALSO vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
