$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): OR on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "OR INTEGER INTEGER 1:"; vinteger_min OR vinteger_min
PRINT "OR INTEGER INTEGER 2:"; vinteger_max OR vinteger_max
PRINT "OR INTEGER INTEGER 3:"; vinteger_min OR vinteger_max
PRINT "OR INTEGER INTEGER 4:"; vinteger_max OR vinteger_min
PRINT "OR INTEGER INTEGER 5:"; vinteger_m1 OR vinteger_one
PRINT "OR INTEGER INTEGER 6:"; vinteger_zero OR vinteger_one
PRINT "OR INTEGER INTEGER 7:"; vinteger_r1 OR vinteger_r2
PRINT "OR INTEGER INTEGER 8:"; vinteger_r2 OR vinteger_r1
PRINT "OR INTEGER LONG 1:"; vinteger_min OR vlong_min
PRINT "OR INTEGER LONG 2:"; vinteger_max OR vlong_max
PRINT "OR INTEGER LONG 3:"; vinteger_min OR vlong_max
PRINT "OR INTEGER LONG 4:"; vinteger_max OR vlong_min
PRINT "OR INTEGER LONG 5:"; vinteger_m1 OR vlong_one
PRINT "OR INTEGER LONG 6:"; vinteger_zero OR vlong_one
PRINT "OR INTEGER LONG 7:"; vinteger_r1 OR vlong_r2
PRINT "OR INTEGER LONG 8:"; vinteger_r2 OR vlong_r1
PRINT "OR INTEGER INT64 1:"; vinteger_min OR vint64_min
PRINT "OR INTEGER INT64 2:"; vinteger_max OR vint64_max
PRINT "OR INTEGER INT64 3:"; vinteger_min OR vint64_max
PRINT "OR INTEGER INT64 4:"; vinteger_max OR vint64_min
PRINT "OR INTEGER INT64 5:"; vinteger_m1 OR vint64_one
PRINT "OR INTEGER INT64 6:"; vinteger_zero OR vint64_one
PRINT "OR INTEGER INT64 7:"; vinteger_r1 OR vint64_r2
PRINT "OR INTEGER INT64 8:"; vinteger_r2 OR vint64_r1
PRINT "OR INTEGER SINGLE 1:"; vinteger_min OR vsingle_min
PRINT "OR INTEGER SINGLE 2:"; vinteger_max OR vsingle_max
PRINT "OR INTEGER SINGLE 3:"; vinteger_min OR vsingle_max
PRINT "OR INTEGER SINGLE 4:"; vinteger_max OR vsingle_min
PRINT "OR INTEGER SINGLE 5:"; vinteger_m1 OR vsingle_one
PRINT "OR INTEGER SINGLE 6:"; vinteger_zero OR vsingle_one
PRINT "OR INTEGER SINGLE 7:"; vinteger_r1 OR vsingle_r2
PRINT "OR INTEGER SINGLE 8:"; vinteger_r2 OR vsingle_r1
PRINT "OR INTEGER DOUBLE 1:"; vinteger_min OR vdouble_min
PRINT "OR INTEGER DOUBLE 2:"; vinteger_max OR vdouble_max
PRINT "OR INTEGER DOUBLE 3:"; vinteger_min OR vdouble_max
PRINT "OR INTEGER DOUBLE 4:"; vinteger_max OR vdouble_min
PRINT "OR INTEGER DOUBLE 5:"; vinteger_m1 OR vdouble_one
PRINT "OR INTEGER DOUBLE 6:"; vinteger_zero OR vdouble_one
PRINT "OR INTEGER DOUBLE 7:"; vinteger_r1 OR vdouble_r2
PRINT "OR INTEGER DOUBLE 8:"; vinteger_r2 OR vdouble_r1
PRINT "OR INTEGER FLOAT 1:"; vinteger_min OR vfloat_min
PRINT "OR INTEGER FLOAT 2:"; vinteger_max OR vfloat_max
PRINT "OR INTEGER FLOAT 3:"; vinteger_min OR vfloat_max
PRINT "OR INTEGER FLOAT 4:"; vinteger_max OR vfloat_min
PRINT "OR INTEGER FLOAT 5:"; vinteger_m1 OR vfloat_one
PRINT "OR INTEGER FLOAT 6:"; vinteger_zero OR vfloat_one
PRINT "OR INTEGER FLOAT 7:"; vinteger_r1 OR vfloat_r2
PRINT "OR INTEGER FLOAT 8:"; vinteger_r2 OR vfloat_r1
PRINT "OR LONG INTEGER 1:"; vlong_min OR vinteger_min
PRINT "OR LONG INTEGER 2:"; vlong_max OR vinteger_max
PRINT "OR LONG INTEGER 3:"; vlong_min OR vinteger_max
PRINT "OR LONG INTEGER 4:"; vlong_max OR vinteger_min
PRINT "OR LONG INTEGER 5:"; vlong_m1 OR vinteger_one
PRINT "OR LONG INTEGER 6:"; vlong_zero OR vinteger_one
PRINT "OR LONG INTEGER 7:"; vlong_r1 OR vinteger_r2
PRINT "OR LONG INTEGER 8:"; vlong_r2 OR vinteger_r1
PRINT "OR LONG LONG 1:"; vlong_min OR vlong_min
PRINT "OR LONG LONG 2:"; vlong_max OR vlong_max
PRINT "OR LONG LONG 3:"; vlong_min OR vlong_max
PRINT "OR LONG LONG 4:"; vlong_max OR vlong_min
PRINT "OR LONG LONG 5:"; vlong_m1 OR vlong_one
PRINT "OR LONG LONG 6:"; vlong_zero OR vlong_one
PRINT "OR LONG LONG 7:"; vlong_r1 OR vlong_r2
PRINT "OR LONG LONG 8:"; vlong_r2 OR vlong_r1
PRINT "OR LONG INT64 1:"; vlong_min OR vint64_min
PRINT "OR LONG INT64 2:"; vlong_max OR vint64_max
PRINT "OR LONG INT64 3:"; vlong_min OR vint64_max
PRINT "OR LONG INT64 4:"; vlong_max OR vint64_min
PRINT "OR LONG INT64 5:"; vlong_m1 OR vint64_one
PRINT "OR LONG INT64 6:"; vlong_zero OR vint64_one
PRINT "OR LONG INT64 7:"; vlong_r1 OR vint64_r2
PRINT "OR LONG INT64 8:"; vlong_r2 OR vint64_r1
PRINT "OR LONG SINGLE 1:"; vlong_min OR vsingle_min
PRINT "OR LONG SINGLE 2:"; vlong_max OR vsingle_max
PRINT "OR LONG SINGLE 3:"; vlong_min OR vsingle_max
PRINT "OR LONG SINGLE 4:"; vlong_max OR vsingle_min
PRINT "OR LONG SINGLE 5:"; vlong_m1 OR vsingle_one
PRINT "OR LONG SINGLE 6:"; vlong_zero OR vsingle_one
PRINT "OR LONG SINGLE 7:"; vlong_r1 OR vsingle_r2
PRINT "OR LONG SINGLE 8:"; vlong_r2 OR vsingle_r1
PRINT "OR LONG DOUBLE 1:"; vlong_min OR vdouble_min
PRINT "OR LONG DOUBLE 2:"; vlong_max OR vdouble_max
PRINT "OR LONG DOUBLE 3:"; vlong_min OR vdouble_max
PRINT "OR LONG DOUBLE 4:"; vlong_max OR vdouble_min
PRINT "OR LONG DOUBLE 5:"; vlong_m1 OR vdouble_one
PRINT "OR LONG DOUBLE 6:"; vlong_zero OR vdouble_one
PRINT "OR LONG DOUBLE 7:"; vlong_r1 OR vdouble_r2
PRINT "OR LONG DOUBLE 8:"; vlong_r2 OR vdouble_r1
PRINT "OR LONG FLOAT 1:"; vlong_min OR vfloat_min
PRINT "OR LONG FLOAT 2:"; vlong_max OR vfloat_max
PRINT "OR LONG FLOAT 3:"; vlong_min OR vfloat_max
PRINT "OR LONG FLOAT 4:"; vlong_max OR vfloat_min
PRINT "OR LONG FLOAT 5:"; vlong_m1 OR vfloat_one
PRINT "OR LONG FLOAT 6:"; vlong_zero OR vfloat_one
PRINT "OR LONG FLOAT 7:"; vlong_r1 OR vfloat_r2
PRINT "OR LONG FLOAT 8:"; vlong_r2 OR vfloat_r1
PRINT "OR INT64 INTEGER 1:"; vint64_min OR vinteger_min
PRINT "OR INT64 INTEGER 2:"; vint64_max OR vinteger_max
PRINT "OR INT64 INTEGER 3:"; vint64_min OR vinteger_max
PRINT "OR INT64 INTEGER 4:"; vint64_max OR vinteger_min
PRINT "OR INT64 INTEGER 5:"; vint64_m1 OR vinteger_one
PRINT "OR INT64 INTEGER 6:"; vint64_zero OR vinteger_one
PRINT "OR INT64 INTEGER 7:"; vint64_r1 OR vinteger_r2
PRINT "OR INT64 INTEGER 8:"; vint64_r2 OR vinteger_r1
PRINT "OR INT64 LONG 1:"; vint64_min OR vlong_min
PRINT "OR INT64 LONG 2:"; vint64_max OR vlong_max
PRINT "OR INT64 LONG 3:"; vint64_min OR vlong_max
PRINT "OR INT64 LONG 4:"; vint64_max OR vlong_min
PRINT "OR INT64 LONG 5:"; vint64_m1 OR vlong_one
PRINT "OR INT64 LONG 6:"; vint64_zero OR vlong_one
PRINT "OR INT64 LONG 7:"; vint64_r1 OR vlong_r2
PRINT "OR INT64 LONG 8:"; vint64_r2 OR vlong_r1
PRINT "OR INT64 INT64 1:"; vint64_min OR vint64_min
PRINT "OR INT64 INT64 2:"; vint64_max OR vint64_max
PRINT "OR INT64 INT64 3:"; vint64_min OR vint64_max
PRINT "OR INT64 INT64 4:"; vint64_max OR vint64_min
PRINT "OR INT64 INT64 5:"; vint64_m1 OR vint64_one
PRINT "OR INT64 INT64 6:"; vint64_zero OR vint64_one
PRINT "OR INT64 INT64 7:"; vint64_r1 OR vint64_r2
PRINT "OR INT64 INT64 8:"; vint64_r2 OR vint64_r1
PRINT "OR INT64 SINGLE 1:"; vint64_min OR vsingle_min
PRINT "OR INT64 SINGLE 2:"; vint64_max OR vsingle_max
PRINT "OR INT64 SINGLE 3:"; vint64_min OR vsingle_max
PRINT "OR INT64 SINGLE 4:"; vint64_max OR vsingle_min
PRINT "OR INT64 SINGLE 5:"; vint64_m1 OR vsingle_one
PRINT "OR INT64 SINGLE 6:"; vint64_zero OR vsingle_one
PRINT "OR INT64 SINGLE 7:"; vint64_r1 OR vsingle_r2
PRINT "OR INT64 SINGLE 8:"; vint64_r2 OR vsingle_r1
PRINT "OR INT64 DOUBLE 1:"; vint64_min OR vdouble_min
PRINT "OR INT64 DOUBLE 2:"; vint64_max OR vdouble_max
PRINT "OR INT64 DOUBLE 3:"; vint64_min OR vdouble_max
PRINT "OR INT64 DOUBLE 4:"; vint64_max OR vdouble_min
PRINT "OR INT64 DOUBLE 5:"; vint64_m1 OR vdouble_one
PRINT "OR INT64 DOUBLE 6:"; vint64_zero OR vdouble_one
PRINT "OR INT64 DOUBLE 7:"; vint64_r1 OR vdouble_r2
PRINT "OR INT64 DOUBLE 8:"; vint64_r2 OR vdouble_r1
PRINT "OR INT64 FLOAT 1:"; vint64_min OR vfloat_min
PRINT "OR INT64 FLOAT 2:"; vint64_max OR vfloat_max
PRINT "OR INT64 FLOAT 3:"; vint64_min OR vfloat_max
PRINT "OR INT64 FLOAT 4:"; vint64_max OR vfloat_min
PRINT "OR INT64 FLOAT 5:"; vint64_m1 OR vfloat_one
PRINT "OR INT64 FLOAT 6:"; vint64_zero OR vfloat_one
PRINT "OR INT64 FLOAT 7:"; vint64_r1 OR vfloat_r2
PRINT "OR INT64 FLOAT 8:"; vint64_r2 OR vfloat_r1
PRINT "OR SINGLE INTEGER 1:"; vsingle_min OR vinteger_min
PRINT "OR SINGLE INTEGER 2:"; vsingle_max OR vinteger_max
PRINT "OR SINGLE INTEGER 3:"; vsingle_min OR vinteger_max
PRINT "OR SINGLE INTEGER 4:"; vsingle_max OR vinteger_min
PRINT "OR SINGLE INTEGER 5:"; vsingle_m1 OR vinteger_one
PRINT "OR SINGLE INTEGER 6:"; vsingle_zero OR vinteger_one
PRINT "OR SINGLE INTEGER 7:"; vsingle_r1 OR vinteger_r2
PRINT "OR SINGLE INTEGER 8:"; vsingle_r2 OR vinteger_r1
PRINT "OR SINGLE LONG 1:"; vsingle_min OR vlong_min
PRINT "OR SINGLE LONG 2:"; vsingle_max OR vlong_max
PRINT "OR SINGLE LONG 3:"; vsingle_min OR vlong_max
PRINT "OR SINGLE LONG 4:"; vsingle_max OR vlong_min
PRINT "OR SINGLE LONG 5:"; vsingle_m1 OR vlong_one
PRINT "OR SINGLE LONG 6:"; vsingle_zero OR vlong_one
PRINT "OR SINGLE LONG 7:"; vsingle_r1 OR vlong_r2
PRINT "OR SINGLE LONG 8:"; vsingle_r2 OR vlong_r1
PRINT "OR SINGLE INT64 1:"; vsingle_min OR vint64_min
PRINT "OR SINGLE INT64 2:"; vsingle_max OR vint64_max
PRINT "OR SINGLE INT64 3:"; vsingle_min OR vint64_max
PRINT "OR SINGLE INT64 4:"; vsingle_max OR vint64_min
PRINT "OR SINGLE INT64 5:"; vsingle_m1 OR vint64_one
PRINT "OR SINGLE INT64 6:"; vsingle_zero OR vint64_one
PRINT "OR SINGLE INT64 7:"; vsingle_r1 OR vint64_r2
PRINT "OR SINGLE INT64 8:"; vsingle_r2 OR vint64_r1
PRINT "OR SINGLE SINGLE 1:"; vsingle_min OR vsingle_min
PRINT "OR SINGLE SINGLE 2:"; vsingle_max OR vsingle_max
PRINT "OR SINGLE SINGLE 3:"; vsingle_min OR vsingle_max
PRINT "OR SINGLE SINGLE 4:"; vsingle_max OR vsingle_min
PRINT "OR SINGLE SINGLE 5:"; vsingle_m1 OR vsingle_one
PRINT "OR SINGLE SINGLE 6:"; vsingle_zero OR vsingle_one
PRINT "OR SINGLE SINGLE 7:"; vsingle_r1 OR vsingle_r2
PRINT "OR SINGLE SINGLE 8:"; vsingle_r2 OR vsingle_r1
PRINT "OR SINGLE DOUBLE 1:"; vsingle_min OR vdouble_min
PRINT "OR SINGLE DOUBLE 2:"; vsingle_max OR vdouble_max
PRINT "OR SINGLE DOUBLE 3:"; vsingle_min OR vdouble_max
PRINT "OR SINGLE DOUBLE 4:"; vsingle_max OR vdouble_min
PRINT "OR SINGLE DOUBLE 5:"; vsingle_m1 OR vdouble_one
PRINT "OR SINGLE DOUBLE 6:"; vsingle_zero OR vdouble_one
PRINT "OR SINGLE DOUBLE 7:"; vsingle_r1 OR vdouble_r2
PRINT "OR SINGLE DOUBLE 8:"; vsingle_r2 OR vdouble_r1
PRINT "OR SINGLE FLOAT 1:"; vsingle_min OR vfloat_min
PRINT "OR SINGLE FLOAT 2:"; vsingle_max OR vfloat_max
PRINT "OR SINGLE FLOAT 3:"; vsingle_min OR vfloat_max
PRINT "OR SINGLE FLOAT 4:"; vsingle_max OR vfloat_min
PRINT "OR SINGLE FLOAT 5:"; vsingle_m1 OR vfloat_one
PRINT "OR SINGLE FLOAT 6:"; vsingle_zero OR vfloat_one
PRINT "OR SINGLE FLOAT 7:"; vsingle_r1 OR vfloat_r2
PRINT "OR SINGLE FLOAT 8:"; vsingle_r2 OR vfloat_r1
PRINT "OR DOUBLE INTEGER 1:"; vdouble_min OR vinteger_min
PRINT "OR DOUBLE INTEGER 2:"; vdouble_max OR vinteger_max
PRINT "OR DOUBLE INTEGER 3:"; vdouble_min OR vinteger_max
PRINT "OR DOUBLE INTEGER 4:"; vdouble_max OR vinteger_min
PRINT "OR DOUBLE INTEGER 5:"; vdouble_m1 OR vinteger_one
PRINT "OR DOUBLE INTEGER 6:"; vdouble_zero OR vinteger_one
PRINT "OR DOUBLE INTEGER 7:"; vdouble_r1 OR vinteger_r2
PRINT "OR DOUBLE INTEGER 8:"; vdouble_r2 OR vinteger_r1
PRINT "OR DOUBLE LONG 1:"; vdouble_min OR vlong_min
PRINT "OR DOUBLE LONG 2:"; vdouble_max OR vlong_max
PRINT "OR DOUBLE LONG 3:"; vdouble_min OR vlong_max
PRINT "OR DOUBLE LONG 4:"; vdouble_max OR vlong_min
PRINT "OR DOUBLE LONG 5:"; vdouble_m1 OR vlong_one
PRINT "OR DOUBLE LONG 6:"; vdouble_zero OR vlong_one
PRINT "OR DOUBLE LONG 7:"; vdouble_r1 OR vlong_r2
PRINT "OR DOUBLE LONG 8:"; vdouble_r2 OR vlong_r1
PRINT "OR DOUBLE INT64 1:"; vdouble_min OR vint64_min
PRINT "OR DOUBLE INT64 2:"; vdouble_max OR vint64_max
PRINT "OR DOUBLE INT64 3:"; vdouble_min OR vint64_max
PRINT "OR DOUBLE INT64 4:"; vdouble_max OR vint64_min
PRINT "OR DOUBLE INT64 5:"; vdouble_m1 OR vint64_one
PRINT "OR DOUBLE INT64 6:"; vdouble_zero OR vint64_one
PRINT "OR DOUBLE INT64 7:"; vdouble_r1 OR vint64_r2
PRINT "OR DOUBLE INT64 8:"; vdouble_r2 OR vint64_r1
PRINT "OR DOUBLE SINGLE 1:"; vdouble_min OR vsingle_min
PRINT "OR DOUBLE SINGLE 2:"; vdouble_max OR vsingle_max
PRINT "OR DOUBLE SINGLE 3:"; vdouble_min OR vsingle_max
PRINT "OR DOUBLE SINGLE 4:"; vdouble_max OR vsingle_min
PRINT "OR DOUBLE SINGLE 5:"; vdouble_m1 OR vsingle_one
PRINT "OR DOUBLE SINGLE 6:"; vdouble_zero OR vsingle_one
PRINT "OR DOUBLE SINGLE 7:"; vdouble_r1 OR vsingle_r2
PRINT "OR DOUBLE SINGLE 8:"; vdouble_r2 OR vsingle_r1
PRINT "OR DOUBLE DOUBLE 1:"; vdouble_min OR vdouble_min
PRINT "OR DOUBLE DOUBLE 2:"; vdouble_max OR vdouble_max
PRINT "OR DOUBLE DOUBLE 3:"; vdouble_min OR vdouble_max
PRINT "OR DOUBLE DOUBLE 4:"; vdouble_max OR vdouble_min
PRINT "OR DOUBLE DOUBLE 5:"; vdouble_m1 OR vdouble_one
PRINT "OR DOUBLE DOUBLE 6:"; vdouble_zero OR vdouble_one
PRINT "OR DOUBLE DOUBLE 7:"; vdouble_r1 OR vdouble_r2
PRINT "OR DOUBLE DOUBLE 8:"; vdouble_r2 OR vdouble_r1
PRINT "OR DOUBLE FLOAT 1:"; vdouble_min OR vfloat_min
PRINT "OR DOUBLE FLOAT 2:"; vdouble_max OR vfloat_max
PRINT "OR DOUBLE FLOAT 3:"; vdouble_min OR vfloat_max
PRINT "OR DOUBLE FLOAT 4:"; vdouble_max OR vfloat_min
PRINT "OR DOUBLE FLOAT 5:"; vdouble_m1 OR vfloat_one
PRINT "OR DOUBLE FLOAT 6:"; vdouble_zero OR vfloat_one
PRINT "OR DOUBLE FLOAT 7:"; vdouble_r1 OR vfloat_r2
PRINT "OR DOUBLE FLOAT 8:"; vdouble_r2 OR vfloat_r1
PRINT "OR FLOAT INTEGER 1:"; vfloat_min OR vinteger_min
PRINT "OR FLOAT INTEGER 2:"; vfloat_max OR vinteger_max
PRINT "OR FLOAT INTEGER 3:"; vfloat_min OR vinteger_max
PRINT "OR FLOAT INTEGER 4:"; vfloat_max OR vinteger_min
PRINT "OR FLOAT INTEGER 5:"; vfloat_m1 OR vinteger_one
PRINT "OR FLOAT INTEGER 6:"; vfloat_zero OR vinteger_one
PRINT "OR FLOAT INTEGER 7:"; vfloat_r1 OR vinteger_r2
PRINT "OR FLOAT INTEGER 8:"; vfloat_r2 OR vinteger_r1
PRINT "OR FLOAT LONG 1:"; vfloat_min OR vlong_min
PRINT "OR FLOAT LONG 2:"; vfloat_max OR vlong_max
PRINT "OR FLOAT LONG 3:"; vfloat_min OR vlong_max
PRINT "OR FLOAT LONG 4:"; vfloat_max OR vlong_min
PRINT "OR FLOAT LONG 5:"; vfloat_m1 OR vlong_one
PRINT "OR FLOAT LONG 6:"; vfloat_zero OR vlong_one
PRINT "OR FLOAT LONG 7:"; vfloat_r1 OR vlong_r2
PRINT "OR FLOAT LONG 8:"; vfloat_r2 OR vlong_r1
PRINT "OR FLOAT INT64 1:"; vfloat_min OR vint64_min
PRINT "OR FLOAT INT64 2:"; vfloat_max OR vint64_max
PRINT "OR FLOAT INT64 3:"; vfloat_min OR vint64_max
PRINT "OR FLOAT INT64 4:"; vfloat_max OR vint64_min
PRINT "OR FLOAT INT64 5:"; vfloat_m1 OR vint64_one
PRINT "OR FLOAT INT64 6:"; vfloat_zero OR vint64_one
PRINT "OR FLOAT INT64 7:"; vfloat_r1 OR vint64_r2
PRINT "OR FLOAT INT64 8:"; vfloat_r2 OR vint64_r1
PRINT "OR FLOAT SINGLE 1:"; vfloat_min OR vsingle_min
PRINT "OR FLOAT SINGLE 2:"; vfloat_max OR vsingle_max
PRINT "OR FLOAT SINGLE 3:"; vfloat_min OR vsingle_max
PRINT "OR FLOAT SINGLE 4:"; vfloat_max OR vsingle_min
PRINT "OR FLOAT SINGLE 5:"; vfloat_m1 OR vsingle_one
PRINT "OR FLOAT SINGLE 6:"; vfloat_zero OR vsingle_one
PRINT "OR FLOAT SINGLE 7:"; vfloat_r1 OR vsingle_r2
PRINT "OR FLOAT SINGLE 8:"; vfloat_r2 OR vsingle_r1
PRINT "OR FLOAT DOUBLE 1:"; vfloat_min OR vdouble_min
PRINT "OR FLOAT DOUBLE 2:"; vfloat_max OR vdouble_max
PRINT "OR FLOAT DOUBLE 3:"; vfloat_min OR vdouble_max
PRINT "OR FLOAT DOUBLE 4:"; vfloat_max OR vdouble_min
PRINT "OR FLOAT DOUBLE 5:"; vfloat_m1 OR vdouble_one
PRINT "OR FLOAT DOUBLE 6:"; vfloat_zero OR vdouble_one
PRINT "OR FLOAT DOUBLE 7:"; vfloat_r1 OR vdouble_r2
PRINT "OR FLOAT DOUBLE 8:"; vfloat_r2 OR vdouble_r1
PRINT "OR FLOAT FLOAT 1:"; vfloat_min OR vfloat_min
PRINT "OR FLOAT FLOAT 2:"; vfloat_max OR vfloat_max
PRINT "OR FLOAT FLOAT 3:"; vfloat_min OR vfloat_max
PRINT "OR FLOAT FLOAT 4:"; vfloat_max OR vfloat_min
PRINT "OR FLOAT FLOAT 5:"; vfloat_m1 OR vfloat_one
PRINT "OR FLOAT FLOAT 6:"; vfloat_zero OR vfloat_one
PRINT "OR FLOAT FLOAT 7:"; vfloat_r1 OR vfloat_r2
PRINT "OR FLOAT FLOAT 8:"; vfloat_r2 OR vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
