$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): \ on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
' Left out: 12 value pairs whose divisor rounds to 0 (fatal in the old compiler, design D2).
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "\ INTEGER INTEGER 1:"; vinteger_min \ vinteger_min
PRINT "\ INTEGER INTEGER 2:"; vinteger_max \ vinteger_max
PRINT "\ INTEGER INTEGER 3:"; vinteger_min \ vinteger_max
PRINT "\ INTEGER INTEGER 4:"; vinteger_max \ vinteger_min
PRINT "\ INTEGER INTEGER 5:"; vinteger_m1 \ vinteger_one
PRINT "\ INTEGER INTEGER 6:"; vinteger_zero \ vinteger_one
PRINT "\ INTEGER INTEGER 7:"; vinteger_r1 \ vinteger_r2
PRINT "\ INTEGER INTEGER 8:"; vinteger_r2 \ vinteger_r1
PRINT "\ INTEGER LONG 1:"; vinteger_min \ vlong_min
PRINT "\ INTEGER LONG 2:"; vinteger_max \ vlong_max
PRINT "\ INTEGER LONG 3:"; vinteger_min \ vlong_max
PRINT "\ INTEGER LONG 4:"; vinteger_max \ vlong_min
PRINT "\ INTEGER LONG 5:"; vinteger_m1 \ vlong_one
PRINT "\ INTEGER LONG 6:"; vinteger_zero \ vlong_one
PRINT "\ INTEGER LONG 7:"; vinteger_r1 \ vlong_r2
PRINT "\ INTEGER LONG 8:"; vinteger_r2 \ vlong_r1
PRINT "\ INTEGER INT64 1:"; vinteger_min \ vint64_min
PRINT "\ INTEGER INT64 2:"; vinteger_max \ vint64_max
PRINT "\ INTEGER INT64 3:"; vinteger_min \ vint64_max
PRINT "\ INTEGER INT64 4:"; vinteger_max \ vint64_min
PRINT "\ INTEGER INT64 5:"; vinteger_m1 \ vint64_one
PRINT "\ INTEGER INT64 6:"; vinteger_zero \ vint64_one
PRINT "\ INTEGER INT64 7:"; vinteger_r1 \ vint64_r2
PRINT "\ INTEGER INT64 8:"; vinteger_r2 \ vint64_r1
PRINT "\ INTEGER SINGLE 1:"; vinteger_min \ vsingle_min
PRINT "\ INTEGER SINGLE 2:"; vinteger_max \ vsingle_max
PRINT "\ INTEGER SINGLE 3:"; vinteger_min \ vsingle_max
PRINT "\ INTEGER SINGLE 4:"; vinteger_max \ vsingle_min
PRINT "\ INTEGER SINGLE 5:"; vinteger_m1 \ vsingle_one
PRINT "\ INTEGER SINGLE 6:"; vinteger_zero \ vsingle_one
PRINT "\ INTEGER DOUBLE 1:"; vinteger_min \ vdouble_min
PRINT "\ INTEGER DOUBLE 2:"; vinteger_max \ vdouble_max
PRINT "\ INTEGER DOUBLE 3:"; vinteger_min \ vdouble_max
PRINT "\ INTEGER DOUBLE 4:"; vinteger_max \ vdouble_min
PRINT "\ INTEGER DOUBLE 5:"; vinteger_m1 \ vdouble_one
PRINT "\ INTEGER DOUBLE 6:"; vinteger_zero \ vdouble_one
PRINT "\ INTEGER DOUBLE 7:"; vinteger_r1 \ vdouble_r2
PRINT "\ INTEGER DOUBLE 8:"; vinteger_r2 \ vdouble_r1
PRINT "\ INTEGER FLOAT 1:"; vinteger_min \ vfloat_min
PRINT "\ INTEGER FLOAT 2:"; vinteger_max \ vfloat_max
PRINT "\ INTEGER FLOAT 3:"; vinteger_min \ vfloat_max
PRINT "\ INTEGER FLOAT 4:"; vinteger_max \ vfloat_min
PRINT "\ INTEGER FLOAT 5:"; vinteger_m1 \ vfloat_one
PRINT "\ INTEGER FLOAT 6:"; vinteger_zero \ vfloat_one
PRINT "\ INTEGER FLOAT 7:"; vinteger_r1 \ vfloat_r2
PRINT "\ INTEGER FLOAT 8:"; vinteger_r2 \ vfloat_r1
PRINT "\ LONG INTEGER 1:"; vlong_min \ vinteger_min
PRINT "\ LONG INTEGER 2:"; vlong_max \ vinteger_max
PRINT "\ LONG INTEGER 3:"; vlong_min \ vinteger_max
PRINT "\ LONG INTEGER 4:"; vlong_max \ vinteger_min
PRINT "\ LONG INTEGER 5:"; vlong_m1 \ vinteger_one
PRINT "\ LONG INTEGER 6:"; vlong_zero \ vinteger_one
PRINT "\ LONG INTEGER 7:"; vlong_r1 \ vinteger_r2
PRINT "\ LONG INTEGER 8:"; vlong_r2 \ vinteger_r1
PRINT "\ LONG LONG 1:"; vlong_min \ vlong_min
PRINT "\ LONG LONG 2:"; vlong_max \ vlong_max
PRINT "\ LONG LONG 3:"; vlong_min \ vlong_max
PRINT "\ LONG LONG 4:"; vlong_max \ vlong_min
PRINT "\ LONG LONG 5:"; vlong_m1 \ vlong_one
PRINT "\ LONG LONG 6:"; vlong_zero \ vlong_one
PRINT "\ LONG LONG 7:"; vlong_r1 \ vlong_r2
PRINT "\ LONG LONG 8:"; vlong_r2 \ vlong_r1
PRINT "\ LONG INT64 1:"; vlong_min \ vint64_min
PRINT "\ LONG INT64 2:"; vlong_max \ vint64_max
PRINT "\ LONG INT64 3:"; vlong_min \ vint64_max
PRINT "\ LONG INT64 4:"; vlong_max \ vint64_min
PRINT "\ LONG INT64 5:"; vlong_m1 \ vint64_one
PRINT "\ LONG INT64 6:"; vlong_zero \ vint64_one
PRINT "\ LONG INT64 7:"; vlong_r1 \ vint64_r2
PRINT "\ LONG INT64 8:"; vlong_r2 \ vint64_r1
PRINT "\ LONG SINGLE 1:"; vlong_min \ vsingle_min
PRINT "\ LONG SINGLE 2:"; vlong_max \ vsingle_max
PRINT "\ LONG SINGLE 3:"; vlong_min \ vsingle_max
PRINT "\ LONG SINGLE 4:"; vlong_max \ vsingle_min
PRINT "\ LONG SINGLE 5:"; vlong_m1 \ vsingle_one
PRINT "\ LONG SINGLE 6:"; vlong_zero \ vsingle_one
PRINT "\ LONG DOUBLE 1:"; vlong_min \ vdouble_min
PRINT "\ LONG DOUBLE 2:"; vlong_max \ vdouble_max
PRINT "\ LONG DOUBLE 3:"; vlong_min \ vdouble_max
PRINT "\ LONG DOUBLE 4:"; vlong_max \ vdouble_min
PRINT "\ LONG DOUBLE 5:"; vlong_m1 \ vdouble_one
PRINT "\ LONG DOUBLE 6:"; vlong_zero \ vdouble_one
PRINT "\ LONG DOUBLE 7:"; vlong_r1 \ vdouble_r2
PRINT "\ LONG DOUBLE 8:"; vlong_r2 \ vdouble_r1
PRINT "\ LONG FLOAT 1:"; vlong_min \ vfloat_min
PRINT "\ LONG FLOAT 2:"; vlong_max \ vfloat_max
PRINT "\ LONG FLOAT 3:"; vlong_min \ vfloat_max
PRINT "\ LONG FLOAT 4:"; vlong_max \ vfloat_min
PRINT "\ LONG FLOAT 5:"; vlong_m1 \ vfloat_one
PRINT "\ LONG FLOAT 6:"; vlong_zero \ vfloat_one
PRINT "\ LONG FLOAT 7:"; vlong_r1 \ vfloat_r2
PRINT "\ LONG FLOAT 8:"; vlong_r2 \ vfloat_r1
PRINT "\ INT64 INTEGER 1:"; vint64_min \ vinteger_min
PRINT "\ INT64 INTEGER 2:"; vint64_max \ vinteger_max
PRINT "\ INT64 INTEGER 3:"; vint64_min \ vinteger_max
PRINT "\ INT64 INTEGER 4:"; vint64_max \ vinteger_min
PRINT "\ INT64 INTEGER 5:"; vint64_m1 \ vinteger_one
PRINT "\ INT64 INTEGER 6:"; vint64_zero \ vinteger_one
PRINT "\ INT64 INTEGER 7:"; vint64_r1 \ vinteger_r2
PRINT "\ INT64 INTEGER 8:"; vint64_r2 \ vinteger_r1
PRINT "\ INT64 LONG 1:"; vint64_min \ vlong_min
PRINT "\ INT64 LONG 2:"; vint64_max \ vlong_max
PRINT "\ INT64 LONG 3:"; vint64_min \ vlong_max
PRINT "\ INT64 LONG 4:"; vint64_max \ vlong_min
PRINT "\ INT64 LONG 5:"; vint64_m1 \ vlong_one
PRINT "\ INT64 LONG 6:"; vint64_zero \ vlong_one
PRINT "\ INT64 LONG 7:"; vint64_r1 \ vlong_r2
PRINT "\ INT64 LONG 8:"; vint64_r2 \ vlong_r1
PRINT "\ INT64 INT64 1:"; vint64_min \ vint64_min
PRINT "\ INT64 INT64 2:"; vint64_max \ vint64_max
PRINT "\ INT64 INT64 3:"; vint64_min \ vint64_max
PRINT "\ INT64 INT64 4:"; vint64_max \ vint64_min
PRINT "\ INT64 INT64 5:"; vint64_m1 \ vint64_one
PRINT "\ INT64 INT64 6:"; vint64_zero \ vint64_one
PRINT "\ INT64 INT64 7:"; vint64_r1 \ vint64_r2
PRINT "\ INT64 INT64 8:"; vint64_r2 \ vint64_r1
PRINT "\ INT64 SINGLE 1:"; vint64_min \ vsingle_min
PRINT "\ INT64 SINGLE 2:"; vint64_max \ vsingle_max
PRINT "\ INT64 SINGLE 3:"; vint64_min \ vsingle_max
PRINT "\ INT64 SINGLE 4:"; vint64_max \ vsingle_min
PRINT "\ INT64 SINGLE 5:"; vint64_m1 \ vsingle_one
PRINT "\ INT64 SINGLE 6:"; vint64_zero \ vsingle_one
PRINT "\ INT64 DOUBLE 1:"; vint64_min \ vdouble_min
PRINT "\ INT64 DOUBLE 2:"; vint64_max \ vdouble_max
PRINT "\ INT64 DOUBLE 3:"; vint64_min \ vdouble_max
PRINT "\ INT64 DOUBLE 4:"; vint64_max \ vdouble_min
PRINT "\ INT64 DOUBLE 5:"; vint64_m1 \ vdouble_one
PRINT "\ INT64 DOUBLE 6:"; vint64_zero \ vdouble_one
PRINT "\ INT64 DOUBLE 7:"; vint64_r1 \ vdouble_r2
PRINT "\ INT64 DOUBLE 8:"; vint64_r2 \ vdouble_r1
PRINT "\ INT64 FLOAT 1:"; vint64_min \ vfloat_min
PRINT "\ INT64 FLOAT 2:"; vint64_max \ vfloat_max
PRINT "\ INT64 FLOAT 3:"; vint64_min \ vfloat_max
PRINT "\ INT64 FLOAT 4:"; vint64_max \ vfloat_min
PRINT "\ INT64 FLOAT 5:"; vint64_m1 \ vfloat_one
PRINT "\ INT64 FLOAT 6:"; vint64_zero \ vfloat_one
PRINT "\ INT64 FLOAT 7:"; vint64_r1 \ vfloat_r2
PRINT "\ INT64 FLOAT 8:"; vint64_r2 \ vfloat_r1
PRINT "\ SINGLE INTEGER 1:"; vsingle_min \ vinteger_min
PRINT "\ SINGLE INTEGER 2:"; vsingle_max \ vinteger_max
PRINT "\ SINGLE INTEGER 3:"; vsingle_min \ vinteger_max
PRINT "\ SINGLE INTEGER 4:"; vsingle_max \ vinteger_min
PRINT "\ SINGLE INTEGER 5:"; vsingle_m1 \ vinteger_one
PRINT "\ SINGLE INTEGER 6:"; vsingle_zero \ vinteger_one
PRINT "\ SINGLE INTEGER 7:"; vsingle_r1 \ vinteger_r2
PRINT "\ SINGLE INTEGER 8:"; vsingle_r2 \ vinteger_r1
PRINT "\ SINGLE LONG 1:"; vsingle_min \ vlong_min
PRINT "\ SINGLE LONG 2:"; vsingle_max \ vlong_max
PRINT "\ SINGLE LONG 3:"; vsingle_min \ vlong_max
PRINT "\ SINGLE LONG 4:"; vsingle_max \ vlong_min
PRINT "\ SINGLE LONG 5:"; vsingle_m1 \ vlong_one
PRINT "\ SINGLE LONG 6:"; vsingle_zero \ vlong_one
PRINT "\ SINGLE LONG 7:"; vsingle_r1 \ vlong_r2
PRINT "\ SINGLE LONG 8:"; vsingle_r2 \ vlong_r1
PRINT "\ SINGLE INT64 1:"; vsingle_min \ vint64_min
PRINT "\ SINGLE INT64 2:"; vsingle_max \ vint64_max
PRINT "\ SINGLE INT64 3:"; vsingle_min \ vint64_max
PRINT "\ SINGLE INT64 4:"; vsingle_max \ vint64_min
PRINT "\ SINGLE INT64 5:"; vsingle_m1 \ vint64_one
PRINT "\ SINGLE INT64 6:"; vsingle_zero \ vint64_one
PRINT "\ SINGLE INT64 7:"; vsingle_r1 \ vint64_r2
PRINT "\ SINGLE INT64 8:"; vsingle_r2 \ vint64_r1
PRINT "\ SINGLE SINGLE 1:"; vsingle_min \ vsingle_min
PRINT "\ SINGLE SINGLE 2:"; vsingle_max \ vsingle_max
PRINT "\ SINGLE SINGLE 3:"; vsingle_min \ vsingle_max
PRINT "\ SINGLE SINGLE 4:"; vsingle_max \ vsingle_min
PRINT "\ SINGLE SINGLE 5:"; vsingle_m1 \ vsingle_one
PRINT "\ SINGLE SINGLE 6:"; vsingle_zero \ vsingle_one
PRINT "\ SINGLE DOUBLE 1:"; vsingle_min \ vdouble_min
PRINT "\ SINGLE DOUBLE 2:"; vsingle_max \ vdouble_max
PRINT "\ SINGLE DOUBLE 3:"; vsingle_min \ vdouble_max
PRINT "\ SINGLE DOUBLE 4:"; vsingle_max \ vdouble_min
PRINT "\ SINGLE DOUBLE 5:"; vsingle_m1 \ vdouble_one
PRINT "\ SINGLE DOUBLE 6:"; vsingle_zero \ vdouble_one
PRINT "\ SINGLE DOUBLE 7:"; vsingle_r1 \ vdouble_r2
PRINT "\ SINGLE DOUBLE 8:"; vsingle_r2 \ vdouble_r1
PRINT "\ SINGLE FLOAT 1:"; vsingle_min \ vfloat_min
PRINT "\ SINGLE FLOAT 2:"; vsingle_max \ vfloat_max
PRINT "\ SINGLE FLOAT 3:"; vsingle_min \ vfloat_max
PRINT "\ SINGLE FLOAT 4:"; vsingle_max \ vfloat_min
PRINT "\ SINGLE FLOAT 5:"; vsingle_m1 \ vfloat_one
PRINT "\ SINGLE FLOAT 6:"; vsingle_zero \ vfloat_one
PRINT "\ SINGLE FLOAT 7:"; vsingle_r1 \ vfloat_r2
PRINT "\ SINGLE FLOAT 8:"; vsingle_r2 \ vfloat_r1
PRINT "\ DOUBLE INTEGER 1:"; vdouble_min \ vinteger_min
PRINT "\ DOUBLE INTEGER 2:"; vdouble_max \ vinteger_max
PRINT "\ DOUBLE INTEGER 3:"; vdouble_min \ vinteger_max
PRINT "\ DOUBLE INTEGER 4:"; vdouble_max \ vinteger_min
PRINT "\ DOUBLE INTEGER 5:"; vdouble_m1 \ vinteger_one
PRINT "\ DOUBLE INTEGER 6:"; vdouble_zero \ vinteger_one
PRINT "\ DOUBLE INTEGER 7:"; vdouble_r1 \ vinteger_r2
PRINT "\ DOUBLE INTEGER 8:"; vdouble_r2 \ vinteger_r1
PRINT "\ DOUBLE LONG 1:"; vdouble_min \ vlong_min
PRINT "\ DOUBLE LONG 2:"; vdouble_max \ vlong_max
PRINT "\ DOUBLE LONG 3:"; vdouble_min \ vlong_max
PRINT "\ DOUBLE LONG 4:"; vdouble_max \ vlong_min
PRINT "\ DOUBLE LONG 5:"; vdouble_m1 \ vlong_one
PRINT "\ DOUBLE LONG 6:"; vdouble_zero \ vlong_one
PRINT "\ DOUBLE LONG 7:"; vdouble_r1 \ vlong_r2
PRINT "\ DOUBLE LONG 8:"; vdouble_r2 \ vlong_r1
PRINT "\ DOUBLE INT64 1:"; vdouble_min \ vint64_min
PRINT "\ DOUBLE INT64 2:"; vdouble_max \ vint64_max
PRINT "\ DOUBLE INT64 3:"; vdouble_min \ vint64_max
PRINT "\ DOUBLE INT64 4:"; vdouble_max \ vint64_min
PRINT "\ DOUBLE INT64 5:"; vdouble_m1 \ vint64_one
PRINT "\ DOUBLE INT64 6:"; vdouble_zero \ vint64_one
PRINT "\ DOUBLE INT64 7:"; vdouble_r1 \ vint64_r2
PRINT "\ DOUBLE INT64 8:"; vdouble_r2 \ vint64_r1
PRINT "\ DOUBLE SINGLE 1:"; vdouble_min \ vsingle_min
PRINT "\ DOUBLE SINGLE 2:"; vdouble_max \ vsingle_max
PRINT "\ DOUBLE SINGLE 3:"; vdouble_min \ vsingle_max
PRINT "\ DOUBLE SINGLE 4:"; vdouble_max \ vsingle_min
PRINT "\ DOUBLE SINGLE 5:"; vdouble_m1 \ vsingle_one
PRINT "\ DOUBLE SINGLE 6:"; vdouble_zero \ vsingle_one
PRINT "\ DOUBLE DOUBLE 1:"; vdouble_min \ vdouble_min
PRINT "\ DOUBLE DOUBLE 2:"; vdouble_max \ vdouble_max
PRINT "\ DOUBLE DOUBLE 3:"; vdouble_min \ vdouble_max
PRINT "\ DOUBLE DOUBLE 4:"; vdouble_max \ vdouble_min
PRINT "\ DOUBLE DOUBLE 5:"; vdouble_m1 \ vdouble_one
PRINT "\ DOUBLE DOUBLE 6:"; vdouble_zero \ vdouble_one
PRINT "\ DOUBLE DOUBLE 7:"; vdouble_r1 \ vdouble_r2
PRINT "\ DOUBLE DOUBLE 8:"; vdouble_r2 \ vdouble_r1
PRINT "\ DOUBLE FLOAT 1:"; vdouble_min \ vfloat_min
PRINT "\ DOUBLE FLOAT 2:"; vdouble_max \ vfloat_max
PRINT "\ DOUBLE FLOAT 3:"; vdouble_min \ vfloat_max
PRINT "\ DOUBLE FLOAT 4:"; vdouble_max \ vfloat_min
PRINT "\ DOUBLE FLOAT 5:"; vdouble_m1 \ vfloat_one
PRINT "\ DOUBLE FLOAT 6:"; vdouble_zero \ vfloat_one
PRINT "\ DOUBLE FLOAT 7:"; vdouble_r1 \ vfloat_r2
PRINT "\ DOUBLE FLOAT 8:"; vdouble_r2 \ vfloat_r1
PRINT "\ FLOAT INTEGER 1:"; vfloat_min \ vinteger_min
PRINT "\ FLOAT INTEGER 2:"; vfloat_max \ vinteger_max
PRINT "\ FLOAT INTEGER 3:"; vfloat_min \ vinteger_max
PRINT "\ FLOAT INTEGER 4:"; vfloat_max \ vinteger_min
PRINT "\ FLOAT INTEGER 5:"; vfloat_m1 \ vinteger_one
PRINT "\ FLOAT INTEGER 6:"; vfloat_zero \ vinteger_one
PRINT "\ FLOAT INTEGER 7:"; vfloat_r1 \ vinteger_r2
PRINT "\ FLOAT INTEGER 8:"; vfloat_r2 \ vinteger_r1
PRINT "\ FLOAT LONG 1:"; vfloat_min \ vlong_min
PRINT "\ FLOAT LONG 2:"; vfloat_max \ vlong_max
PRINT "\ FLOAT LONG 3:"; vfloat_min \ vlong_max
PRINT "\ FLOAT LONG 4:"; vfloat_max \ vlong_min
PRINT "\ FLOAT LONG 5:"; vfloat_m1 \ vlong_one
PRINT "\ FLOAT LONG 6:"; vfloat_zero \ vlong_one
PRINT "\ FLOAT LONG 7:"; vfloat_r1 \ vlong_r2
PRINT "\ FLOAT LONG 8:"; vfloat_r2 \ vlong_r1
PRINT "\ FLOAT INT64 1:"; vfloat_min \ vint64_min
PRINT "\ FLOAT INT64 2:"; vfloat_max \ vint64_max
PRINT "\ FLOAT INT64 3:"; vfloat_min \ vint64_max
PRINT "\ FLOAT INT64 4:"; vfloat_max \ vint64_min
PRINT "\ FLOAT INT64 5:"; vfloat_m1 \ vint64_one
PRINT "\ FLOAT INT64 6:"; vfloat_zero \ vint64_one
PRINT "\ FLOAT INT64 7:"; vfloat_r1 \ vint64_r2
PRINT "\ FLOAT INT64 8:"; vfloat_r2 \ vint64_r1
PRINT "\ FLOAT SINGLE 1:"; vfloat_min \ vsingle_min
PRINT "\ FLOAT SINGLE 2:"; vfloat_max \ vsingle_max
PRINT "\ FLOAT SINGLE 3:"; vfloat_min \ vsingle_max
PRINT "\ FLOAT SINGLE 4:"; vfloat_max \ vsingle_min
PRINT "\ FLOAT SINGLE 5:"; vfloat_m1 \ vsingle_one
PRINT "\ FLOAT SINGLE 6:"; vfloat_zero \ vsingle_one
PRINT "\ FLOAT DOUBLE 1:"; vfloat_min \ vdouble_min
PRINT "\ FLOAT DOUBLE 2:"; vfloat_max \ vdouble_max
PRINT "\ FLOAT DOUBLE 3:"; vfloat_min \ vdouble_max
PRINT "\ FLOAT DOUBLE 4:"; vfloat_max \ vdouble_min
PRINT "\ FLOAT DOUBLE 5:"; vfloat_m1 \ vdouble_one
PRINT "\ FLOAT DOUBLE 6:"; vfloat_zero \ vdouble_one
PRINT "\ FLOAT DOUBLE 7:"; vfloat_r1 \ vdouble_r2
PRINT "\ FLOAT DOUBLE 8:"; vfloat_r2 \ vdouble_r1
PRINT "\ FLOAT FLOAT 1:"; vfloat_min \ vfloat_min
PRINT "\ FLOAT FLOAT 2:"; vfloat_max \ vfloat_max
PRINT "\ FLOAT FLOAT 3:"; vfloat_min \ vfloat_max
PRINT "\ FLOAT FLOAT 4:"; vfloat_max \ vfloat_min
PRINT "\ FLOAT FLOAT 5:"; vfloat_m1 \ vfloat_one
PRINT "\ FLOAT FLOAT 6:"; vfloat_zero \ vfloat_one
PRINT "\ FLOAT FLOAT 7:"; vfloat_r1 \ vfloat_r2
PRINT "\ FLOAT FLOAT 8:"; vfloat_r2 \ vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
