$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): EQV on every ordered pair of numeric types, operands in variables.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "EQV INTEGER INTEGER 1:"; vinteger_min EQV vinteger_min
PRINT "EQV INTEGER INTEGER 2:"; vinteger_max EQV vinteger_max
PRINT "EQV INTEGER INTEGER 3:"; vinteger_min EQV vinteger_max
PRINT "EQV INTEGER INTEGER 4:"; vinteger_max EQV vinteger_min
PRINT "EQV INTEGER INTEGER 5:"; vinteger_m1 EQV vinteger_one
PRINT "EQV INTEGER INTEGER 6:"; vinteger_zero EQV vinteger_one
PRINT "EQV INTEGER INTEGER 7:"; vinteger_r1 EQV vinteger_r2
PRINT "EQV INTEGER INTEGER 8:"; vinteger_r2 EQV vinteger_r1
PRINT "EQV INTEGER LONG 1:"; vinteger_min EQV vlong_min
PRINT "EQV INTEGER LONG 2:"; vinteger_max EQV vlong_max
PRINT "EQV INTEGER LONG 3:"; vinteger_min EQV vlong_max
PRINT "EQV INTEGER LONG 4:"; vinteger_max EQV vlong_min
PRINT "EQV INTEGER LONG 5:"; vinteger_m1 EQV vlong_one
PRINT "EQV INTEGER LONG 6:"; vinteger_zero EQV vlong_one
PRINT "EQV INTEGER LONG 7:"; vinteger_r1 EQV vlong_r2
PRINT "EQV INTEGER LONG 8:"; vinteger_r2 EQV vlong_r1
PRINT "EQV INTEGER INT64 1:"; vinteger_min EQV vint64_min
PRINT "EQV INTEGER INT64 2:"; vinteger_max EQV vint64_max
PRINT "EQV INTEGER INT64 3:"; vinteger_min EQV vint64_max
PRINT "EQV INTEGER INT64 4:"; vinteger_max EQV vint64_min
PRINT "EQV INTEGER INT64 5:"; vinteger_m1 EQV vint64_one
PRINT "EQV INTEGER INT64 6:"; vinteger_zero EQV vint64_one
PRINT "EQV INTEGER INT64 7:"; vinteger_r1 EQV vint64_r2
PRINT "EQV INTEGER INT64 8:"; vinteger_r2 EQV vint64_r1
PRINT "EQV INTEGER SINGLE 1:"; vinteger_min EQV vsingle_min
PRINT "EQV INTEGER SINGLE 2:"; vinteger_max EQV vsingle_max
PRINT "EQV INTEGER SINGLE 3:"; vinteger_min EQV vsingle_max
PRINT "EQV INTEGER SINGLE 4:"; vinteger_max EQV vsingle_min
PRINT "EQV INTEGER SINGLE 5:"; vinteger_m1 EQV vsingle_one
PRINT "EQV INTEGER SINGLE 6:"; vinteger_zero EQV vsingle_one
PRINT "EQV INTEGER SINGLE 7:"; vinteger_r1 EQV vsingle_r2
PRINT "EQV INTEGER SINGLE 8:"; vinteger_r2 EQV vsingle_r1
PRINT "EQV INTEGER DOUBLE 1:"; vinteger_min EQV vdouble_min
PRINT "EQV INTEGER DOUBLE 2:"; vinteger_max EQV vdouble_max
PRINT "EQV INTEGER DOUBLE 3:"; vinteger_min EQV vdouble_max
PRINT "EQV INTEGER DOUBLE 4:"; vinteger_max EQV vdouble_min
PRINT "EQV INTEGER DOUBLE 5:"; vinteger_m1 EQV vdouble_one
PRINT "EQV INTEGER DOUBLE 6:"; vinteger_zero EQV vdouble_one
PRINT "EQV INTEGER DOUBLE 7:"; vinteger_r1 EQV vdouble_r2
PRINT "EQV INTEGER DOUBLE 8:"; vinteger_r2 EQV vdouble_r1
PRINT "EQV INTEGER FLOAT 1:"; vinteger_min EQV vfloat_min
PRINT "EQV INTEGER FLOAT 2:"; vinteger_max EQV vfloat_max
PRINT "EQV INTEGER FLOAT 3:"; vinteger_min EQV vfloat_max
PRINT "EQV INTEGER FLOAT 4:"; vinteger_max EQV vfloat_min
PRINT "EQV INTEGER FLOAT 5:"; vinteger_m1 EQV vfloat_one
PRINT "EQV INTEGER FLOAT 6:"; vinteger_zero EQV vfloat_one
PRINT "EQV INTEGER FLOAT 7:"; vinteger_r1 EQV vfloat_r2
PRINT "EQV INTEGER FLOAT 8:"; vinteger_r2 EQV vfloat_r1
PRINT "EQV LONG INTEGER 1:"; vlong_min EQV vinteger_min
PRINT "EQV LONG INTEGER 2:"; vlong_max EQV vinteger_max
PRINT "EQV LONG INTEGER 3:"; vlong_min EQV vinteger_max
PRINT "EQV LONG INTEGER 4:"; vlong_max EQV vinteger_min
PRINT "EQV LONG INTEGER 5:"; vlong_m1 EQV vinteger_one
PRINT "EQV LONG INTEGER 6:"; vlong_zero EQV vinteger_one
PRINT "EQV LONG INTEGER 7:"; vlong_r1 EQV vinteger_r2
PRINT "EQV LONG INTEGER 8:"; vlong_r2 EQV vinteger_r1
PRINT "EQV LONG LONG 1:"; vlong_min EQV vlong_min
PRINT "EQV LONG LONG 2:"; vlong_max EQV vlong_max
PRINT "EQV LONG LONG 3:"; vlong_min EQV vlong_max
PRINT "EQV LONG LONG 4:"; vlong_max EQV vlong_min
PRINT "EQV LONG LONG 5:"; vlong_m1 EQV vlong_one
PRINT "EQV LONG LONG 6:"; vlong_zero EQV vlong_one
PRINT "EQV LONG LONG 7:"; vlong_r1 EQV vlong_r2
PRINT "EQV LONG LONG 8:"; vlong_r2 EQV vlong_r1
PRINT "EQV LONG INT64 1:"; vlong_min EQV vint64_min
PRINT "EQV LONG INT64 2:"; vlong_max EQV vint64_max
PRINT "EQV LONG INT64 3:"; vlong_min EQV vint64_max
PRINT "EQV LONG INT64 4:"; vlong_max EQV vint64_min
PRINT "EQV LONG INT64 5:"; vlong_m1 EQV vint64_one
PRINT "EQV LONG INT64 6:"; vlong_zero EQV vint64_one
PRINT "EQV LONG INT64 7:"; vlong_r1 EQV vint64_r2
PRINT "EQV LONG INT64 8:"; vlong_r2 EQV vint64_r1
PRINT "EQV LONG SINGLE 1:"; vlong_min EQV vsingle_min
PRINT "EQV LONG SINGLE 2:"; vlong_max EQV vsingle_max
PRINT "EQV LONG SINGLE 3:"; vlong_min EQV vsingle_max
PRINT "EQV LONG SINGLE 4:"; vlong_max EQV vsingle_min
PRINT "EQV LONG SINGLE 5:"; vlong_m1 EQV vsingle_one
PRINT "EQV LONG SINGLE 6:"; vlong_zero EQV vsingle_one
PRINT "EQV LONG SINGLE 7:"; vlong_r1 EQV vsingle_r2
PRINT "EQV LONG SINGLE 8:"; vlong_r2 EQV vsingle_r1
PRINT "EQV LONG DOUBLE 1:"; vlong_min EQV vdouble_min
PRINT "EQV LONG DOUBLE 2:"; vlong_max EQV vdouble_max
PRINT "EQV LONG DOUBLE 3:"; vlong_min EQV vdouble_max
PRINT "EQV LONG DOUBLE 4:"; vlong_max EQV vdouble_min
PRINT "EQV LONG DOUBLE 5:"; vlong_m1 EQV vdouble_one
PRINT "EQV LONG DOUBLE 6:"; vlong_zero EQV vdouble_one
PRINT "EQV LONG DOUBLE 7:"; vlong_r1 EQV vdouble_r2
PRINT "EQV LONG DOUBLE 8:"; vlong_r2 EQV vdouble_r1
PRINT "EQV LONG FLOAT 1:"; vlong_min EQV vfloat_min
PRINT "EQV LONG FLOAT 2:"; vlong_max EQV vfloat_max
PRINT "EQV LONG FLOAT 3:"; vlong_min EQV vfloat_max
PRINT "EQV LONG FLOAT 4:"; vlong_max EQV vfloat_min
PRINT "EQV LONG FLOAT 5:"; vlong_m1 EQV vfloat_one
PRINT "EQV LONG FLOAT 6:"; vlong_zero EQV vfloat_one
PRINT "EQV LONG FLOAT 7:"; vlong_r1 EQV vfloat_r2
PRINT "EQV LONG FLOAT 8:"; vlong_r2 EQV vfloat_r1
PRINT "EQV INT64 INTEGER 1:"; vint64_min EQV vinteger_min
PRINT "EQV INT64 INTEGER 2:"; vint64_max EQV vinteger_max
PRINT "EQV INT64 INTEGER 3:"; vint64_min EQV vinteger_max
PRINT "EQV INT64 INTEGER 4:"; vint64_max EQV vinteger_min
PRINT "EQV INT64 INTEGER 5:"; vint64_m1 EQV vinteger_one
PRINT "EQV INT64 INTEGER 6:"; vint64_zero EQV vinteger_one
PRINT "EQV INT64 INTEGER 7:"; vint64_r1 EQV vinteger_r2
PRINT "EQV INT64 INTEGER 8:"; vint64_r2 EQV vinteger_r1
PRINT "EQV INT64 LONG 1:"; vint64_min EQV vlong_min
PRINT "EQV INT64 LONG 2:"; vint64_max EQV vlong_max
PRINT "EQV INT64 LONG 3:"; vint64_min EQV vlong_max
PRINT "EQV INT64 LONG 4:"; vint64_max EQV vlong_min
PRINT "EQV INT64 LONG 5:"; vint64_m1 EQV vlong_one
PRINT "EQV INT64 LONG 6:"; vint64_zero EQV vlong_one
PRINT "EQV INT64 LONG 7:"; vint64_r1 EQV vlong_r2
PRINT "EQV INT64 LONG 8:"; vint64_r2 EQV vlong_r1
PRINT "EQV INT64 INT64 1:"; vint64_min EQV vint64_min
PRINT "EQV INT64 INT64 2:"; vint64_max EQV vint64_max
PRINT "EQV INT64 INT64 3:"; vint64_min EQV vint64_max
PRINT "EQV INT64 INT64 4:"; vint64_max EQV vint64_min
PRINT "EQV INT64 INT64 5:"; vint64_m1 EQV vint64_one
PRINT "EQV INT64 INT64 6:"; vint64_zero EQV vint64_one
PRINT "EQV INT64 INT64 7:"; vint64_r1 EQV vint64_r2
PRINT "EQV INT64 INT64 8:"; vint64_r2 EQV vint64_r1
PRINT "EQV INT64 SINGLE 1:"; vint64_min EQV vsingle_min
PRINT "EQV INT64 SINGLE 2:"; vint64_max EQV vsingle_max
PRINT "EQV INT64 SINGLE 3:"; vint64_min EQV vsingle_max
PRINT "EQV INT64 SINGLE 4:"; vint64_max EQV vsingle_min
PRINT "EQV INT64 SINGLE 5:"; vint64_m1 EQV vsingle_one
PRINT "EQV INT64 SINGLE 6:"; vint64_zero EQV vsingle_one
PRINT "EQV INT64 SINGLE 7:"; vint64_r1 EQV vsingle_r2
PRINT "EQV INT64 SINGLE 8:"; vint64_r2 EQV vsingle_r1
PRINT "EQV INT64 DOUBLE 1:"; vint64_min EQV vdouble_min
PRINT "EQV INT64 DOUBLE 2:"; vint64_max EQV vdouble_max
PRINT "EQV INT64 DOUBLE 3:"; vint64_min EQV vdouble_max
PRINT "EQV INT64 DOUBLE 4:"; vint64_max EQV vdouble_min
PRINT "EQV INT64 DOUBLE 5:"; vint64_m1 EQV vdouble_one
PRINT "EQV INT64 DOUBLE 6:"; vint64_zero EQV vdouble_one
PRINT "EQV INT64 DOUBLE 7:"; vint64_r1 EQV vdouble_r2
PRINT "EQV INT64 DOUBLE 8:"; vint64_r2 EQV vdouble_r1
PRINT "EQV INT64 FLOAT 1:"; vint64_min EQV vfloat_min
PRINT "EQV INT64 FLOAT 2:"; vint64_max EQV vfloat_max
PRINT "EQV INT64 FLOAT 3:"; vint64_min EQV vfloat_max
PRINT "EQV INT64 FLOAT 4:"; vint64_max EQV vfloat_min
PRINT "EQV INT64 FLOAT 5:"; vint64_m1 EQV vfloat_one
PRINT "EQV INT64 FLOAT 6:"; vint64_zero EQV vfloat_one
PRINT "EQV INT64 FLOAT 7:"; vint64_r1 EQV vfloat_r2
PRINT "EQV INT64 FLOAT 8:"; vint64_r2 EQV vfloat_r1
PRINT "EQV SINGLE INTEGER 1:"; vsingle_min EQV vinteger_min
PRINT "EQV SINGLE INTEGER 2:"; vsingle_max EQV vinteger_max
PRINT "EQV SINGLE INTEGER 3:"; vsingle_min EQV vinteger_max
PRINT "EQV SINGLE INTEGER 4:"; vsingle_max EQV vinteger_min
PRINT "EQV SINGLE INTEGER 5:"; vsingle_m1 EQV vinteger_one
PRINT "EQV SINGLE INTEGER 6:"; vsingle_zero EQV vinteger_one
PRINT "EQV SINGLE INTEGER 7:"; vsingle_r1 EQV vinteger_r2
PRINT "EQV SINGLE INTEGER 8:"; vsingle_r2 EQV vinteger_r1
PRINT "EQV SINGLE LONG 1:"; vsingle_min EQV vlong_min
PRINT "EQV SINGLE LONG 2:"; vsingle_max EQV vlong_max
PRINT "EQV SINGLE LONG 3:"; vsingle_min EQV vlong_max
PRINT "EQV SINGLE LONG 4:"; vsingle_max EQV vlong_min
PRINT "EQV SINGLE LONG 5:"; vsingle_m1 EQV vlong_one
PRINT "EQV SINGLE LONG 6:"; vsingle_zero EQV vlong_one
PRINT "EQV SINGLE LONG 7:"; vsingle_r1 EQV vlong_r2
PRINT "EQV SINGLE LONG 8:"; vsingle_r2 EQV vlong_r1
PRINT "EQV SINGLE INT64 1:"; vsingle_min EQV vint64_min
PRINT "EQV SINGLE INT64 2:"; vsingle_max EQV vint64_max
PRINT "EQV SINGLE INT64 3:"; vsingle_min EQV vint64_max
PRINT "EQV SINGLE INT64 4:"; vsingle_max EQV vint64_min
PRINT "EQV SINGLE INT64 5:"; vsingle_m1 EQV vint64_one
PRINT "EQV SINGLE INT64 6:"; vsingle_zero EQV vint64_one
PRINT "EQV SINGLE INT64 7:"; vsingle_r1 EQV vint64_r2
PRINT "EQV SINGLE INT64 8:"; vsingle_r2 EQV vint64_r1
PRINT "EQV SINGLE SINGLE 1:"; vsingle_min EQV vsingle_min
PRINT "EQV SINGLE SINGLE 2:"; vsingle_max EQV vsingle_max
PRINT "EQV SINGLE SINGLE 3:"; vsingle_min EQV vsingle_max
PRINT "EQV SINGLE SINGLE 4:"; vsingle_max EQV vsingle_min
PRINT "EQV SINGLE SINGLE 5:"; vsingle_m1 EQV vsingle_one
PRINT "EQV SINGLE SINGLE 6:"; vsingle_zero EQV vsingle_one
PRINT "EQV SINGLE SINGLE 7:"; vsingle_r1 EQV vsingle_r2
PRINT "EQV SINGLE SINGLE 8:"; vsingle_r2 EQV vsingle_r1
PRINT "EQV SINGLE DOUBLE 1:"; vsingle_min EQV vdouble_min
PRINT "EQV SINGLE DOUBLE 2:"; vsingle_max EQV vdouble_max
PRINT "EQV SINGLE DOUBLE 3:"; vsingle_min EQV vdouble_max
PRINT "EQV SINGLE DOUBLE 4:"; vsingle_max EQV vdouble_min
PRINT "EQV SINGLE DOUBLE 5:"; vsingle_m1 EQV vdouble_one
PRINT "EQV SINGLE DOUBLE 6:"; vsingle_zero EQV vdouble_one
PRINT "EQV SINGLE DOUBLE 7:"; vsingle_r1 EQV vdouble_r2
PRINT "EQV SINGLE DOUBLE 8:"; vsingle_r2 EQV vdouble_r1
PRINT "EQV SINGLE FLOAT 1:"; vsingle_min EQV vfloat_min
PRINT "EQV SINGLE FLOAT 2:"; vsingle_max EQV vfloat_max
PRINT "EQV SINGLE FLOAT 3:"; vsingle_min EQV vfloat_max
PRINT "EQV SINGLE FLOAT 4:"; vsingle_max EQV vfloat_min
PRINT "EQV SINGLE FLOAT 5:"; vsingle_m1 EQV vfloat_one
PRINT "EQV SINGLE FLOAT 6:"; vsingle_zero EQV vfloat_one
PRINT "EQV SINGLE FLOAT 7:"; vsingle_r1 EQV vfloat_r2
PRINT "EQV SINGLE FLOAT 8:"; vsingle_r2 EQV vfloat_r1
PRINT "EQV DOUBLE INTEGER 1:"; vdouble_min EQV vinteger_min
PRINT "EQV DOUBLE INTEGER 2:"; vdouble_max EQV vinteger_max
PRINT "EQV DOUBLE INTEGER 3:"; vdouble_min EQV vinteger_max
PRINT "EQV DOUBLE INTEGER 4:"; vdouble_max EQV vinteger_min
PRINT "EQV DOUBLE INTEGER 5:"; vdouble_m1 EQV vinteger_one
PRINT "EQV DOUBLE INTEGER 6:"; vdouble_zero EQV vinteger_one
PRINT "EQV DOUBLE INTEGER 7:"; vdouble_r1 EQV vinteger_r2
PRINT "EQV DOUBLE INTEGER 8:"; vdouble_r2 EQV vinteger_r1
PRINT "EQV DOUBLE LONG 1:"; vdouble_min EQV vlong_min
PRINT "EQV DOUBLE LONG 2:"; vdouble_max EQV vlong_max
PRINT "EQV DOUBLE LONG 3:"; vdouble_min EQV vlong_max
PRINT "EQV DOUBLE LONG 4:"; vdouble_max EQV vlong_min
PRINT "EQV DOUBLE LONG 5:"; vdouble_m1 EQV vlong_one
PRINT "EQV DOUBLE LONG 6:"; vdouble_zero EQV vlong_one
PRINT "EQV DOUBLE LONG 7:"; vdouble_r1 EQV vlong_r2
PRINT "EQV DOUBLE LONG 8:"; vdouble_r2 EQV vlong_r1
PRINT "EQV DOUBLE INT64 1:"; vdouble_min EQV vint64_min
PRINT "EQV DOUBLE INT64 2:"; vdouble_max EQV vint64_max
PRINT "EQV DOUBLE INT64 3:"; vdouble_min EQV vint64_max
PRINT "EQV DOUBLE INT64 4:"; vdouble_max EQV vint64_min
PRINT "EQV DOUBLE INT64 5:"; vdouble_m1 EQV vint64_one
PRINT "EQV DOUBLE INT64 6:"; vdouble_zero EQV vint64_one
PRINT "EQV DOUBLE INT64 7:"; vdouble_r1 EQV vint64_r2
PRINT "EQV DOUBLE INT64 8:"; vdouble_r2 EQV vint64_r1
PRINT "EQV DOUBLE SINGLE 1:"; vdouble_min EQV vsingle_min
PRINT "EQV DOUBLE SINGLE 2:"; vdouble_max EQV vsingle_max
PRINT "EQV DOUBLE SINGLE 3:"; vdouble_min EQV vsingle_max
PRINT "EQV DOUBLE SINGLE 4:"; vdouble_max EQV vsingle_min
PRINT "EQV DOUBLE SINGLE 5:"; vdouble_m1 EQV vsingle_one
PRINT "EQV DOUBLE SINGLE 6:"; vdouble_zero EQV vsingle_one
PRINT "EQV DOUBLE SINGLE 7:"; vdouble_r1 EQV vsingle_r2
PRINT "EQV DOUBLE SINGLE 8:"; vdouble_r2 EQV vsingle_r1
PRINT "EQV DOUBLE DOUBLE 1:"; vdouble_min EQV vdouble_min
PRINT "EQV DOUBLE DOUBLE 2:"; vdouble_max EQV vdouble_max
PRINT "EQV DOUBLE DOUBLE 3:"; vdouble_min EQV vdouble_max
PRINT "EQV DOUBLE DOUBLE 4:"; vdouble_max EQV vdouble_min
PRINT "EQV DOUBLE DOUBLE 5:"; vdouble_m1 EQV vdouble_one
PRINT "EQV DOUBLE DOUBLE 6:"; vdouble_zero EQV vdouble_one
PRINT "EQV DOUBLE DOUBLE 7:"; vdouble_r1 EQV vdouble_r2
PRINT "EQV DOUBLE DOUBLE 8:"; vdouble_r2 EQV vdouble_r1
PRINT "EQV DOUBLE FLOAT 1:"; vdouble_min EQV vfloat_min
PRINT "EQV DOUBLE FLOAT 2:"; vdouble_max EQV vfloat_max
PRINT "EQV DOUBLE FLOAT 3:"; vdouble_min EQV vfloat_max
PRINT "EQV DOUBLE FLOAT 4:"; vdouble_max EQV vfloat_min
PRINT "EQV DOUBLE FLOAT 5:"; vdouble_m1 EQV vfloat_one
PRINT "EQV DOUBLE FLOAT 6:"; vdouble_zero EQV vfloat_one
PRINT "EQV DOUBLE FLOAT 7:"; vdouble_r1 EQV vfloat_r2
PRINT "EQV DOUBLE FLOAT 8:"; vdouble_r2 EQV vfloat_r1
PRINT "EQV FLOAT INTEGER 1:"; vfloat_min EQV vinteger_min
PRINT "EQV FLOAT INTEGER 2:"; vfloat_max EQV vinteger_max
PRINT "EQV FLOAT INTEGER 3:"; vfloat_min EQV vinteger_max
PRINT "EQV FLOAT INTEGER 4:"; vfloat_max EQV vinteger_min
PRINT "EQV FLOAT INTEGER 5:"; vfloat_m1 EQV vinteger_one
PRINT "EQV FLOAT INTEGER 6:"; vfloat_zero EQV vinteger_one
PRINT "EQV FLOAT INTEGER 7:"; vfloat_r1 EQV vinteger_r2
PRINT "EQV FLOAT INTEGER 8:"; vfloat_r2 EQV vinteger_r1
PRINT "EQV FLOAT LONG 1:"; vfloat_min EQV vlong_min
PRINT "EQV FLOAT LONG 2:"; vfloat_max EQV vlong_max
PRINT "EQV FLOAT LONG 3:"; vfloat_min EQV vlong_max
PRINT "EQV FLOAT LONG 4:"; vfloat_max EQV vlong_min
PRINT "EQV FLOAT LONG 5:"; vfloat_m1 EQV vlong_one
PRINT "EQV FLOAT LONG 6:"; vfloat_zero EQV vlong_one
PRINT "EQV FLOAT LONG 7:"; vfloat_r1 EQV vlong_r2
PRINT "EQV FLOAT LONG 8:"; vfloat_r2 EQV vlong_r1
PRINT "EQV FLOAT INT64 1:"; vfloat_min EQV vint64_min
PRINT "EQV FLOAT INT64 2:"; vfloat_max EQV vint64_max
PRINT "EQV FLOAT INT64 3:"; vfloat_min EQV vint64_max
PRINT "EQV FLOAT INT64 4:"; vfloat_max EQV vint64_min
PRINT "EQV FLOAT INT64 5:"; vfloat_m1 EQV vint64_one
PRINT "EQV FLOAT INT64 6:"; vfloat_zero EQV vint64_one
PRINT "EQV FLOAT INT64 7:"; vfloat_r1 EQV vint64_r2
PRINT "EQV FLOAT INT64 8:"; vfloat_r2 EQV vint64_r1
PRINT "EQV FLOAT SINGLE 1:"; vfloat_min EQV vsingle_min
PRINT "EQV FLOAT SINGLE 2:"; vfloat_max EQV vsingle_max
PRINT "EQV FLOAT SINGLE 3:"; vfloat_min EQV vsingle_max
PRINT "EQV FLOAT SINGLE 4:"; vfloat_max EQV vsingle_min
PRINT "EQV FLOAT SINGLE 5:"; vfloat_m1 EQV vsingle_one
PRINT "EQV FLOAT SINGLE 6:"; vfloat_zero EQV vsingle_one
PRINT "EQV FLOAT SINGLE 7:"; vfloat_r1 EQV vsingle_r2
PRINT "EQV FLOAT SINGLE 8:"; vfloat_r2 EQV vsingle_r1
PRINT "EQV FLOAT DOUBLE 1:"; vfloat_min EQV vdouble_min
PRINT "EQV FLOAT DOUBLE 2:"; vfloat_max EQV vdouble_max
PRINT "EQV FLOAT DOUBLE 3:"; vfloat_min EQV vdouble_max
PRINT "EQV FLOAT DOUBLE 4:"; vfloat_max EQV vdouble_min
PRINT "EQV FLOAT DOUBLE 5:"; vfloat_m1 EQV vdouble_one
PRINT "EQV FLOAT DOUBLE 6:"; vfloat_zero EQV vdouble_one
PRINT "EQV FLOAT DOUBLE 7:"; vfloat_r1 EQV vdouble_r2
PRINT "EQV FLOAT DOUBLE 8:"; vfloat_r2 EQV vdouble_r1
PRINT "EQV FLOAT FLOAT 1:"; vfloat_min EQV vfloat_min
PRINT "EQV FLOAT FLOAT 2:"; vfloat_max EQV vfloat_max
PRINT "EQV FLOAT FLOAT 3:"; vfloat_min EQV vfloat_max
PRINT "EQV FLOAT FLOAT 4:"; vfloat_max EQV vfloat_min
PRINT "EQV FLOAT FLOAT 5:"; vfloat_m1 EQV vfloat_one
PRINT "EQV FLOAT FLOAT 6:"; vfloat_zero EQV vfloat_one
PRINT "EQV FLOAT FLOAT 7:"; vfloat_r1 EQV vfloat_r2
PRINT "EQV FLOAT FLOAT 8:"; vfloat_r2 EQV vfloat_r1
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
