$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): PRINT and STR$ of every numeric type's values, from variables and as literals.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "PRINT INTEGER min:"; vinteger_min
PRINT "STR$ INTEGER min:"; STR$(vinteger_min)
PRINT "PRINT INTEGER max:"; vinteger_max
PRINT "STR$ INTEGER max:"; STR$(vinteger_max)
PRINT "PRINT INTEGER m1:"; vinteger_m1
PRINT "STR$ INTEGER m1:"; STR$(vinteger_m1)
PRINT "PRINT INTEGER zero:"; vinteger_zero
PRINT "STR$ INTEGER zero:"; STR$(vinteger_zero)
PRINT "PRINT INTEGER one:"; vinteger_one
PRINT "STR$ INTEGER one:"; STR$(vinteger_one)
PRINT "PRINT INTEGER r1:"; vinteger_r1
PRINT "STR$ INTEGER r1:"; STR$(vinteger_r1)
PRINT "PRINT INTEGER r2:"; vinteger_r2
PRINT "STR$ INTEGER r2:"; STR$(vinteger_r2)
PRINT "PRINT LONG min:"; vlong_min
PRINT "STR$ LONG min:"; STR$(vlong_min)
PRINT "PRINT LONG max:"; vlong_max
PRINT "STR$ LONG max:"; STR$(vlong_max)
PRINT "PRINT LONG m1:"; vlong_m1
PRINT "STR$ LONG m1:"; STR$(vlong_m1)
PRINT "PRINT LONG zero:"; vlong_zero
PRINT "STR$ LONG zero:"; STR$(vlong_zero)
PRINT "PRINT LONG one:"; vlong_one
PRINT "STR$ LONG one:"; STR$(vlong_one)
PRINT "PRINT LONG r1:"; vlong_r1
PRINT "STR$ LONG r1:"; STR$(vlong_r1)
PRINT "PRINT LONG r2:"; vlong_r2
PRINT "STR$ LONG r2:"; STR$(vlong_r2)
PRINT "PRINT INT64 min:"; vint64_min
PRINT "STR$ INT64 min:"; STR$(vint64_min)
PRINT "PRINT INT64 max:"; vint64_max
PRINT "STR$ INT64 max:"; STR$(vint64_max)
PRINT "PRINT INT64 m1:"; vint64_m1
PRINT "STR$ INT64 m1:"; STR$(vint64_m1)
PRINT "PRINT INT64 zero:"; vint64_zero
PRINT "STR$ INT64 zero:"; STR$(vint64_zero)
PRINT "PRINT INT64 one:"; vint64_one
PRINT "STR$ INT64 one:"; STR$(vint64_one)
PRINT "PRINT INT64 r1:"; vint64_r1
PRINT "STR$ INT64 r1:"; STR$(vint64_r1)
PRINT "PRINT INT64 r2:"; vint64_r2
PRINT "STR$ INT64 r2:"; STR$(vint64_r2)
PRINT "PRINT SINGLE min:"; vsingle_min
PRINT "STR$ SINGLE min:"; STR$(vsingle_min)
PRINT "PRINT SINGLE max:"; vsingle_max
PRINT "STR$ SINGLE max:"; STR$(vsingle_max)
PRINT "PRINT SINGLE m1:"; vsingle_m1
PRINT "STR$ SINGLE m1:"; STR$(vsingle_m1)
PRINT "PRINT SINGLE zero:"; vsingle_zero
PRINT "STR$ SINGLE zero:"; STR$(vsingle_zero)
PRINT "PRINT SINGLE one:"; vsingle_one
PRINT "STR$ SINGLE one:"; STR$(vsingle_one)
PRINT "PRINT SINGLE r1:"; vsingle_r1
PRINT "STR$ SINGLE r1:"; STR$(vsingle_r1)
PRINT "PRINT SINGLE r2:"; vsingle_r2
PRINT "STR$ SINGLE r2:"; STR$(vsingle_r2)
PRINT "PRINT DOUBLE min:"; vdouble_min
PRINT "STR$ DOUBLE min:"; STR$(vdouble_min)
PRINT "PRINT DOUBLE max:"; vdouble_max
PRINT "STR$ DOUBLE max:"; STR$(vdouble_max)
PRINT "PRINT DOUBLE m1:"; vdouble_m1
PRINT "STR$ DOUBLE m1:"; STR$(vdouble_m1)
PRINT "PRINT DOUBLE zero:"; vdouble_zero
PRINT "STR$ DOUBLE zero:"; STR$(vdouble_zero)
PRINT "PRINT DOUBLE one:"; vdouble_one
PRINT "STR$ DOUBLE one:"; STR$(vdouble_one)
PRINT "PRINT DOUBLE r1:"; vdouble_r1
PRINT "STR$ DOUBLE r1:"; STR$(vdouble_r1)
PRINT "PRINT DOUBLE r2:"; vdouble_r2
PRINT "STR$ DOUBLE r2:"; STR$(vdouble_r2)
PRINT "PRINT FLOAT min:"; vfloat_min
PRINT "STR$ FLOAT min:"; STR$(vfloat_min)
PRINT "PRINT FLOAT max:"; vfloat_max
PRINT "STR$ FLOAT max:"; STR$(vfloat_max)
PRINT "PRINT FLOAT m1:"; vfloat_m1
PRINT "STR$ FLOAT m1:"; STR$(vfloat_m1)
PRINT "PRINT FLOAT zero:"; vfloat_zero
PRINT "STR$ FLOAT zero:"; STR$(vfloat_zero)
PRINT "PRINT FLOAT one:"; vfloat_one
PRINT "STR$ FLOAT one:"; STR$(vfloat_one)
PRINT "PRINT FLOAT r1:"; vfloat_r1
PRINT "STR$ FLOAT r1:"; STR$(vfloat_r1)
PRINT "PRINT FLOAT r2:"; vfloat_r2
PRINT "STR$ FLOAT r2:"; STR$(vfloat_r2)
PRINT "PRINT literal INTEGER min:"; -32768%
PRINT "STR$ literal INTEGER min:"; STR$(-32768%)
PRINT "PRINT literal INTEGER max:"; 32767%
PRINT "STR$ literal INTEGER max:"; STR$(32767%)
PRINT "PRINT literal INTEGER m1:"; -1%
PRINT "STR$ literal INTEGER m1:"; STR$(-1%)
PRINT "PRINT literal INTEGER zero:"; 0%
PRINT "STR$ literal INTEGER zero:"; STR$(0%)
PRINT "PRINT literal INTEGER one:"; 1%
PRINT "STR$ literal INTEGER one:"; STR$(1%)
PRINT "PRINT literal INTEGER r1:"; -2895%
PRINT "STR$ literal INTEGER r1:"; STR$(-2895%)
PRINT "PRINT literal INTEGER r2:"; 5580%
PRINT "STR$ literal INTEGER r2:"; STR$(5580%)
PRINT "PRINT literal INTEGER below:"; -32769%
PRINT "STR$ literal INTEGER below:"; STR$(-32769%)
PRINT "PRINT literal INTEGER above:"; 32768%
PRINT "STR$ literal INTEGER above:"; STR$(32768%)
PRINT "PRINT literal LONG min:"; -2147483648&
PRINT "STR$ literal LONG min:"; STR$(-2147483648&)
PRINT "PRINT literal LONG max:"; 2147483647&
PRINT "STR$ literal LONG max:"; STR$(2147483647&)
PRINT "PRINT literal LONG m1:"; -1&
PRINT "STR$ literal LONG m1:"; STR$(-1&)
PRINT "PRINT literal LONG zero:"; 0&
PRINT "STR$ literal LONG zero:"; STR$(0&)
PRINT "PRINT literal LONG one:"; 1&
PRINT "STR$ literal LONG one:"; STR$(1&)
PRINT "PRINT literal LONG r1:"; -559627433&
PRINT "STR$ literal LONG r1:"; STR$(-559627433&)
PRINT "PRINT literal LONG r2:"; -709606431&
PRINT "STR$ literal LONG r2:"; STR$(-709606431&)
PRINT "PRINT literal LONG below:"; -2147483649&
PRINT "STR$ literal LONG below:"; STR$(-2147483649&)
PRINT "PRINT literal LONG above:"; 2147483648&
PRINT "STR$ literal LONG above:"; STR$(2147483648&)
PRINT "PRINT literal INT64 min:"; (-9223372036854775807&& - 1)
PRINT "STR$ literal INT64 min:"; STR$((-9223372036854775807&& - 1))
PRINT "PRINT literal INT64 max:"; 9223372036854775807&&
PRINT "STR$ literal INT64 max:"; STR$(9223372036854775807&&)
PRINT "PRINT literal INT64 m1:"; -1&&
PRINT "STR$ literal INT64 m1:"; STR$(-1&&)
PRINT "PRINT literal INT64 zero:"; 0&&
PRINT "STR$ literal INT64 zero:"; STR$(0&&)
PRINT "PRINT literal INT64 one:"; 1&&
PRINT "STR$ literal INT64 one:"; STR$(1&&)
PRINT "PRINT literal INT64 r1:"; 5819978767338316436&&
PRINT "STR$ literal INT64 r1:"; STR$(5819978767338316436&&)
PRINT "PRINT literal INT64 r2:"; 7445081360591965601&&
PRINT "STR$ literal INT64 r2:"; STR$(7445081360591965601&&)
PRINT "PRINT literal SINGLE min:"; -3.402823E+38
PRINT "STR$ literal SINGLE min:"; STR$(-3.402823E+38)
PRINT "PRINT literal SINGLE max:"; 3.402823E+38
PRINT "STR$ literal SINGLE max:"; STR$(3.402823E+38)
PRINT "PRINT literal SINGLE m1:"; -1!
PRINT "STR$ literal SINGLE m1:"; STR$(-1!)
PRINT "PRINT literal SINGLE zero:"; 0!
PRINT "STR$ literal SINGLE zero:"; STR$(0!)
PRINT "PRINT literal SINGLE one:"; 1!
PRINT "STR$ literal SINGLE one:"; STR$(1!)
PRINT "PRINT literal SINGLE r1:"; 0.2!
PRINT "STR$ literal SINGLE r1:"; STR$(0.2!)
PRINT "PRINT literal SINGLE r2:"; -0.2253!
PRINT "STR$ literal SINGLE r2:"; STR$(-0.2253!)
PRINT "PRINT literal DOUBLE min:"; -1.797693134862315D+308
PRINT "STR$ literal DOUBLE min:"; STR$(-1.797693134862315D+308)
PRINT "PRINT literal DOUBLE max:"; 1.797693134862315D+308
PRINT "STR$ literal DOUBLE max:"; STR$(1.797693134862315D+308)
PRINT "PRINT literal DOUBLE m1:"; -1#
PRINT "STR$ literal DOUBLE m1:"; STR$(-1#)
PRINT "PRINT literal DOUBLE zero:"; 0#
PRINT "STR$ literal DOUBLE zero:"; STR$(0#)
PRINT "PRINT literal DOUBLE one:"; 1#
PRINT "STR$ literal DOUBLE one:"; STR$(1#)
PRINT "PRINT literal DOUBLE r1:"; -166203811.12578#
PRINT "STR$ literal DOUBLE r1:"; STR$(-166203811.12578#)
PRINT "PRINT literal DOUBLE r2:"; -12534.17#
PRINT "STR$ literal DOUBLE r2:"; STR$(-12534.17#)
PRINT "PRINT literal FLOAT min:"; -1.797693134862315F+308
PRINT "STR$ literal FLOAT min:"; STR$(-1.797693134862315F+308)
PRINT "PRINT literal FLOAT max:"; 1.797693134862315F+308
PRINT "STR$ literal FLOAT max:"; STR$(1.797693134862315F+308)
PRINT "PRINT literal FLOAT m1:"; -1##
PRINT "STR$ literal FLOAT m1:"; STR$(-1##)
PRINT "PRINT literal FLOAT zero:"; 0##
PRINT "STR$ literal FLOAT zero:"; STR$(0##)
PRINT "PRINT literal FLOAT one:"; 1##
PRINT "STR$ literal FLOAT one:"; STR$(1##)
PRINT "PRINT literal FLOAT r1:"; -0.90##
PRINT "STR$ literal FLOAT r1:"; STR$(-0.90##)
PRINT "PRINT literal FLOAT r2:"; 478.10157##
PRINT "STR$ literal FLOAT r2:"; STR$(478.10157##)
PRINT "PRINT literal FLOAT below:"; -1.18973149535723176F+4932
PRINT "STR$ literal FLOAT below:"; STR$(-1.18973149535723176F+4932)
PRINT "PRINT literal FLOAT above:"; 1.18973149535723176F+4932
PRINT "STR$ literal FLOAT above:"; STR$(1.18973149535723176F+4932)
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
