$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): every numeric type's values stored into DOUBLE.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
DIM t AS DOUBLE
PRINT "= DOUBLE INTEGER min:";
t = vinteger_min
PRINT t
PRINT "= DOUBLE INTEGER max:";
t = vinteger_max
PRINT t
PRINT "= DOUBLE INTEGER m1:";
t = vinteger_m1
PRINT t
PRINT "= DOUBLE INTEGER zero:";
t = vinteger_zero
PRINT t
PRINT "= DOUBLE INTEGER one:";
t = vinteger_one
PRINT t
PRINT "= DOUBLE INTEGER r1:";
t = vinteger_r1
PRINT t
PRINT "= DOUBLE INTEGER r2:";
t = vinteger_r2
PRINT t
PRINT "= DOUBLE LONG min:";
t = vlong_min
PRINT t
PRINT "= DOUBLE LONG max:";
t = vlong_max
PRINT t
PRINT "= DOUBLE LONG m1:";
t = vlong_m1
PRINT t
PRINT "= DOUBLE LONG zero:";
t = vlong_zero
PRINT t
PRINT "= DOUBLE LONG one:";
t = vlong_one
PRINT t
PRINT "= DOUBLE LONG r1:";
t = vlong_r1
PRINT t
PRINT "= DOUBLE LONG r2:";
t = vlong_r2
PRINT t
PRINT "= DOUBLE INT64 min:";
t = vint64_min
PRINT t
PRINT "= DOUBLE INT64 max:";
t = vint64_max
PRINT t
PRINT "= DOUBLE INT64 m1:";
t = vint64_m1
PRINT t
PRINT "= DOUBLE INT64 zero:";
t = vint64_zero
PRINT t
PRINT "= DOUBLE INT64 one:";
t = vint64_one
PRINT t
PRINT "= DOUBLE INT64 r1:";
t = vint64_r1
PRINT t
PRINT "= DOUBLE INT64 r2:";
t = vint64_r2
PRINT t
PRINT "= DOUBLE SINGLE min:";
t = vsingle_min
PRINT t
PRINT "= DOUBLE SINGLE max:";
t = vsingle_max
PRINT t
PRINT "= DOUBLE SINGLE m1:";
t = vsingle_m1
PRINT t
PRINT "= DOUBLE SINGLE zero:";
t = vsingle_zero
PRINT t
PRINT "= DOUBLE SINGLE one:";
t = vsingle_one
PRINT t
PRINT "= DOUBLE SINGLE r1:";
t = vsingle_r1
PRINT t
PRINT "= DOUBLE SINGLE r2:";
t = vsingle_r2
PRINT t
PRINT "= DOUBLE DOUBLE min:";
t = vdouble_min
PRINT t
PRINT "= DOUBLE DOUBLE max:";
t = vdouble_max
PRINT t
PRINT "= DOUBLE DOUBLE m1:";
t = vdouble_m1
PRINT t
PRINT "= DOUBLE DOUBLE zero:";
t = vdouble_zero
PRINT t
PRINT "= DOUBLE DOUBLE one:";
t = vdouble_one
PRINT t
PRINT "= DOUBLE DOUBLE r1:";
t = vdouble_r1
PRINT t
PRINT "= DOUBLE DOUBLE r2:";
t = vdouble_r2
PRINT t
PRINT "= DOUBLE FLOAT min:";
t = vfloat_min
PRINT t
PRINT "= DOUBLE FLOAT max:";
t = vfloat_max
PRINT t
PRINT "= DOUBLE FLOAT m1:";
t = vfloat_m1
PRINT t
PRINT "= DOUBLE FLOAT zero:";
t = vfloat_zero
PRINT t
PRINT "= DOUBLE FLOAT one:";
t = vfloat_one
PRINT t
PRINT "= DOUBLE FLOAT r1:";
t = vfloat_r1
PRINT t
PRINT "= DOUBLE FLOAT r2:";
t = vfloat_r2
PRINT t
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
