$CONSOLE:ONLY
' Group old6: the program for the six numeric types INTEGER, LONG, _INTEGER64, SINGLE, DOUBLE and _FLOAT only.
' Differential program (m2-numeric-types, design D2): -, NOT and _NEGATE on every numeric type's values.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
ON ERROR GOTO h
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "- INTEGER min:"; -vinteger_min
PRINT "- INTEGER max:"; -vinteger_max
PRINT "- INTEGER m1:"; -vinteger_m1
PRINT "- INTEGER zero:"; -vinteger_zero
PRINT "- INTEGER one:"; -vinteger_one
PRINT "- INTEGER r1:"; -vinteger_r1
PRINT "- INTEGER r2:"; -vinteger_r2
PRINT "- LONG min:"; -vlong_min
PRINT "- LONG max:"; -vlong_max
PRINT "- LONG m1:"; -vlong_m1
PRINT "- LONG zero:"; -vlong_zero
PRINT "- LONG one:"; -vlong_one
PRINT "- LONG r1:"; -vlong_r1
PRINT "- LONG r2:"; -vlong_r2
PRINT "- INT64 min:"; -vint64_min
PRINT "- INT64 max:"; -vint64_max
PRINT "- INT64 m1:"; -vint64_m1
PRINT "- INT64 zero:"; -vint64_zero
PRINT "- INT64 one:"; -vint64_one
PRINT "- INT64 r1:"; -vint64_r1
PRINT "- INT64 r2:"; -vint64_r2
PRINT "- SINGLE min:"; -vsingle_min
PRINT "- SINGLE max:"; -vsingle_max
PRINT "- SINGLE m1:"; -vsingle_m1
PRINT "- SINGLE zero:"; -vsingle_zero
PRINT "- SINGLE one:"; -vsingle_one
PRINT "- SINGLE r1:"; -vsingle_r1
PRINT "- SINGLE r2:"; -vsingle_r2
PRINT "- DOUBLE min:"; -vdouble_min
PRINT "- DOUBLE max:"; -vdouble_max
PRINT "- DOUBLE m1:"; -vdouble_m1
PRINT "- DOUBLE zero:"; -vdouble_zero
PRINT "- DOUBLE one:"; -vdouble_one
PRINT "- DOUBLE r1:"; -vdouble_r1
PRINT "- DOUBLE r2:"; -vdouble_r2
PRINT "- FLOAT min:"; -vfloat_min
PRINT "- FLOAT max:"; -vfloat_max
PRINT "- FLOAT m1:"; -vfloat_m1
PRINT "- FLOAT zero:"; -vfloat_zero
PRINT "- FLOAT one:"; -vfloat_one
PRINT "- FLOAT r1:"; -vfloat_r1
PRINT "- FLOAT r2:"; -vfloat_r2
PRINT "NOT INTEGER min:"; NOT vinteger_min
PRINT "NOT INTEGER max:"; NOT vinteger_max
PRINT "NOT INTEGER m1:"; NOT vinteger_m1
PRINT "NOT INTEGER zero:"; NOT vinteger_zero
PRINT "NOT INTEGER one:"; NOT vinteger_one
PRINT "NOT INTEGER r1:"; NOT vinteger_r1
PRINT "NOT INTEGER r2:"; NOT vinteger_r2
PRINT "NOT LONG min:"; NOT vlong_min
PRINT "NOT LONG max:"; NOT vlong_max
PRINT "NOT LONG m1:"; NOT vlong_m1
PRINT "NOT LONG zero:"; NOT vlong_zero
PRINT "NOT LONG one:"; NOT vlong_one
PRINT "NOT LONG r1:"; NOT vlong_r1
PRINT "NOT LONG r2:"; NOT vlong_r2
PRINT "NOT INT64 min:"; NOT vint64_min
PRINT "NOT INT64 max:"; NOT vint64_max
PRINT "NOT INT64 m1:"; NOT vint64_m1
PRINT "NOT INT64 zero:"; NOT vint64_zero
PRINT "NOT INT64 one:"; NOT vint64_one
PRINT "NOT INT64 r1:"; NOT vint64_r1
PRINT "NOT INT64 r2:"; NOT vint64_r2
PRINT "NOT SINGLE min:"; NOT vsingle_min
PRINT "NOT SINGLE max:"; NOT vsingle_max
PRINT "NOT SINGLE m1:"; NOT vsingle_m1
PRINT "NOT SINGLE zero:"; NOT vsingle_zero
PRINT "NOT SINGLE one:"; NOT vsingle_one
PRINT "NOT SINGLE r1:"; NOT vsingle_r1
PRINT "NOT SINGLE r2:"; NOT vsingle_r2
PRINT "NOT DOUBLE min:"; NOT vdouble_min
PRINT "NOT DOUBLE max:"; NOT vdouble_max
PRINT "NOT DOUBLE m1:"; NOT vdouble_m1
PRINT "NOT DOUBLE zero:"; NOT vdouble_zero
PRINT "NOT DOUBLE one:"; NOT vdouble_one
PRINT "NOT DOUBLE r1:"; NOT vdouble_r1
PRINT "NOT DOUBLE r2:"; NOT vdouble_r2
PRINT "NOT FLOAT min:"; NOT vfloat_min
PRINT "NOT FLOAT max:"; NOT vfloat_max
PRINT "NOT FLOAT m1:"; NOT vfloat_m1
PRINT "NOT FLOAT zero:"; NOT vfloat_zero
PRINT "NOT FLOAT one:"; NOT vfloat_one
PRINT "NOT FLOAT r1:"; NOT vfloat_r1
PRINT "NOT FLOAT r2:"; NOT vfloat_r2
PRINT "_NEGATE INTEGER min:"; _NEGATE vinteger_min
PRINT "_NEGATE INTEGER max:"; _NEGATE vinteger_max
PRINT "_NEGATE INTEGER m1:"; _NEGATE vinteger_m1
PRINT "_NEGATE INTEGER zero:"; _NEGATE vinteger_zero
PRINT "_NEGATE INTEGER one:"; _NEGATE vinteger_one
PRINT "_NEGATE INTEGER r1:"; _NEGATE vinteger_r1
PRINT "_NEGATE INTEGER r2:"; _NEGATE vinteger_r2
PRINT "_NEGATE LONG min:"; _NEGATE vlong_min
PRINT "_NEGATE LONG max:"; _NEGATE vlong_max
PRINT "_NEGATE LONG m1:"; _NEGATE vlong_m1
PRINT "_NEGATE LONG zero:"; _NEGATE vlong_zero
PRINT "_NEGATE LONG one:"; _NEGATE vlong_one
PRINT "_NEGATE LONG r1:"; _NEGATE vlong_r1
PRINT "_NEGATE LONG r2:"; _NEGATE vlong_r2
PRINT "_NEGATE INT64 min:"; _NEGATE vint64_min
PRINT "_NEGATE INT64 max:"; _NEGATE vint64_max
PRINT "_NEGATE INT64 m1:"; _NEGATE vint64_m1
PRINT "_NEGATE INT64 zero:"; _NEGATE vint64_zero
PRINT "_NEGATE INT64 one:"; _NEGATE vint64_one
PRINT "_NEGATE INT64 r1:"; _NEGATE vint64_r1
PRINT "_NEGATE INT64 r2:"; _NEGATE vint64_r2
PRINT "_NEGATE SINGLE min:"; _NEGATE vsingle_min
PRINT "_NEGATE SINGLE max:"; _NEGATE vsingle_max
PRINT "_NEGATE SINGLE m1:"; _NEGATE vsingle_m1
PRINT "_NEGATE SINGLE zero:"; _NEGATE vsingle_zero
PRINT "_NEGATE SINGLE one:"; _NEGATE vsingle_one
PRINT "_NEGATE SINGLE r1:"; _NEGATE vsingle_r1
PRINT "_NEGATE SINGLE r2:"; _NEGATE vsingle_r2
PRINT "_NEGATE DOUBLE min:"; _NEGATE vdouble_min
PRINT "_NEGATE DOUBLE max:"; _NEGATE vdouble_max
PRINT "_NEGATE DOUBLE m1:"; _NEGATE vdouble_m1
PRINT "_NEGATE DOUBLE zero:"; _NEGATE vdouble_zero
PRINT "_NEGATE DOUBLE one:"; _NEGATE vdouble_one
PRINT "_NEGATE DOUBLE r1:"; _NEGATE vdouble_r1
PRINT "_NEGATE DOUBLE r2:"; _NEGATE vdouble_r2
PRINT "_NEGATE FLOAT min:"; _NEGATE vfloat_min
PRINT "_NEGATE FLOAT max:"; _NEGATE vfloat_max
PRINT "_NEGATE FLOAT m1:"; _NEGATE vfloat_m1
PRINT "_NEGATE FLOAT zero:"; _NEGATE vfloat_zero
PRINT "_NEGATE FLOAT one:"; _NEGATE vfloat_one
PRINT "_NEGATE FLOAT r1:"; _NEGATE vfloat_r1
PRINT "_NEGATE FLOAT r2:"; _NEGATE vfloat_r2
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
