$CONSOLE:ONLY
' Differential program (m2-numeric-types, design D2): every numeric type's values stored into _UNSIGNED _OFFSET.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
' Each _BIT * 40 has a _BIT * 32 pad DIMmed just before it, which the old compiler's overlap hits
' instead (DIVERGENCES.md D-009).
ON ERROR GOTO h
DIM vbyte_min AS _BYTE
DIM vbyte_max AS _BYTE
DIM vbyte_m1 AS _BYTE
DIM vbyte_zero AS _BYTE
DIM vbyte_one AS _BYTE
DIM vbyte_r1 AS _BYTE
DIM vbyte_r2 AS _BYTE
DIM vubyte_min AS _UNSIGNED _BYTE
DIM vubyte_max AS _UNSIGNED _BYTE
DIM vubyte_m1 AS _UNSIGNED _BYTE
DIM vubyte_zero AS _UNSIGNED _BYTE
DIM vubyte_one AS _UNSIGNED _BYTE
DIM vubyte_r1 AS _UNSIGNED _BYTE
DIM vubyte_r2 AS _UNSIGNED _BYTE
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vuinteger_min AS _UNSIGNED INTEGER
DIM vuinteger_max AS _UNSIGNED INTEGER
DIM vuinteger_m1 AS _UNSIGNED INTEGER
DIM vuinteger_zero AS _UNSIGNED INTEGER
DIM vuinteger_one AS _UNSIGNED INTEGER
DIM vuinteger_r1 AS _UNSIGNED INTEGER
DIM vuinteger_r2 AS _UNSIGNED INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vulong_min AS _UNSIGNED LONG
DIM vulong_max AS _UNSIGNED LONG
DIM vulong_m1 AS _UNSIGNED LONG
DIM vulong_zero AS _UNSIGNED LONG
DIM vulong_one AS _UNSIGNED LONG
DIM vulong_r1 AS _UNSIGNED LONG
DIM vulong_r2 AS _UNSIGNED LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vuint64_min AS _UNSIGNED _INTEGER64
DIM vuint64_max AS _UNSIGNED _INTEGER64
DIM vuint64_m1 AS _UNSIGNED _INTEGER64
DIM vuint64_zero AS _UNSIGNED _INTEGER64
DIM vuint64_one AS _UNSIGNED _INTEGER64
DIM vuint64_r1 AS _UNSIGNED _INTEGER64
DIM vuint64_r2 AS _UNSIGNED _INTEGER64
DIM voffset_min AS _OFFSET
DIM voffset_max AS _OFFSET
DIM voffset_m1 AS _OFFSET
DIM voffset_zero AS _OFFSET
DIM voffset_one AS _OFFSET
DIM voffset_r1 AS _OFFSET
DIM voffset_r2 AS _OFFSET
DIM vuoffset_min AS _UNSIGNED _OFFSET
DIM vuoffset_max AS _UNSIGNED _OFFSET
DIM vuoffset_m1 AS _UNSIGNED _OFFSET
DIM vuoffset_zero AS _UNSIGNED _OFFSET
DIM vuoffset_one AS _UNSIGNED _OFFSET
DIM vuoffset_r1 AS _UNSIGNED _OFFSET
DIM vuoffset_r2 AS _UNSIGNED _OFFSET
DIM vbit_min AS _BIT
DIM vbit_max AS _BIT
DIM vbit_m1 AS _BIT
DIM vbit_zero AS _BIT
DIM vbit_one AS _BIT
DIM vbit_r1 AS _BIT
DIM vbit_r2 AS _BIT
DIM vubit7_min AS _UNSIGNED _BIT * 7
DIM vubit7_max AS _UNSIGNED _BIT * 7
DIM vubit7_m1 AS _UNSIGNED _BIT * 7
DIM vubit7_zero AS _UNSIGNED _BIT * 7
DIM vubit7_one AS _UNSIGNED _BIT * 7
DIM vubit7_r1 AS _UNSIGNED _BIT * 7
DIM vubit7_r2 AS _UNSIGNED _BIT * 7
DIM vbit24_min AS _BIT * 24
DIM vbit24_max AS _BIT * 24
DIM vbit24_m1 AS _BIT * 24
DIM vbit24_zero AS _BIT * 24
DIM vbit24_one AS _BIT * 24
DIM vbit24_r1 AS _BIT * 24
DIM vbit24_r2 AS _BIT * 24
DIM pad_vubit40_min AS _BIT * 32
DIM vubit40_min AS _UNSIGNED _BIT * 40
DIM pad_vubit40_max AS _BIT * 32
DIM vubit40_max AS _UNSIGNED _BIT * 40
DIM pad_vubit40_m1 AS _BIT * 32
DIM vubit40_m1 AS _UNSIGNED _BIT * 40
DIM pad_vubit40_zero AS _BIT * 32
DIM vubit40_zero AS _UNSIGNED _BIT * 40
DIM pad_vubit40_one AS _BIT * 32
DIM vubit40_one AS _UNSIGNED _BIT * 40
DIM pad_vubit40_r1 AS _BIT * 32
DIM vubit40_r1 AS _UNSIGNED _BIT * 40
DIM pad_vubit40_r2 AS _BIT * 32
DIM vubit40_r2 AS _UNSIGNED _BIT * 40
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vbyte_min = -128%%
vbyte_max = 127%%
vbyte_m1 = -1%%
vbyte_zero = 0%%
vbyte_one = 1%%
vbyte_r1 = 103%%
vbyte_r2 = -56%%
vubyte_min = 0~%%
vubyte_max = 255~%%
vubyte_m1 = 255~%%
vubyte_zero = 0~%%
vubyte_one = 1~%%
vubyte_r1 = 32~%%
vubyte_r2 = 20~%%
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vuinteger_min = 0~%
vuinteger_max = 65535~%
vuinteger_m1 = 65535~%
vuinteger_zero = 0~%
vuinteger_one = 1~%
vuinteger_r1 = 36936~%
vuinteger_r2 = 38734~%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vulong_min = 0~&
vulong_max = 4294967295~&
vulong_m1 = 4294967295~&
vulong_zero = 0~&
vulong_one = 1~&
vulong_r1 = 3095748532~&
vulong_r2 = 2247239029~&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vuint64_min = 0~&&
vuint64_max = 18446744073709551615~&&
vuint64_m1 = 18446744073709551615~&&
vuint64_zero = 0~&&
vuint64_one = 1~&&
vuint64_r1 = 14721352250261409079~&&
vuint64_r2 = 1695248715451867090~&&
voffset_min = (-9223372036854775807&& - 1)
voffset_max = 9223372036854775807&&
voffset_m1 = -1&&
voffset_zero = 0&&
voffset_one = 1&&
voffset_r1 = 1887714948171717615&&
voffset_r2 = -4592622012093347915&&
vuoffset_min = 0~&&
vuoffset_max = 18446744073709551615~&&
vuoffset_m1 = 18446744073709551615~&&
vuoffset_zero = 0~&&
vuoffset_one = 1~&&
vuoffset_r1 = 15919602987562150171~&&
vuoffset_r2 = 16266618817563032314~&&
vbit_min = -1`
vbit_max = 0`
vbit_m1 = -1`
vbit_zero = 0`
vbit_one = 0`
vbit_r1 = 0`
vbit_r2 = -1`
vubit7_min = 0~`7
vubit7_max = 127~`7
vubit7_m1 = 127~`7
vubit7_zero = 0~`7
vubit7_one = 1~`7
vubit7_r1 = 25~`7
vubit7_r2 = 74~`7
vbit24_min = -8388608`24
vbit24_max = 8388607`24
vbit24_m1 = -1`24
vbit24_zero = 0`24
vbit24_one = 1`24
vbit24_r1 = 3148653`24
vbit24_r2 = -2716775`24
vubit40_min = 0~`40
vubit40_max = 1099511627775~`40
vubit40_m1 = 1099511627775~`40
vubit40_zero = 0~`40
vubit40_one = 1~`40
vubit40_r1 = 464297847704~`40
vubit40_r2 = 488476189167~`40
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
DIM t AS _UNSIGNED _OFFSET
PRINT "= UOFFSET BYTE min:";
t = vbyte_min
PRINT t
PRINT "= UOFFSET BYTE max:";
t = vbyte_max
PRINT t
PRINT "= UOFFSET BYTE m1:";
t = vbyte_m1
PRINT t
PRINT "= UOFFSET BYTE zero:";
t = vbyte_zero
PRINT t
PRINT "= UOFFSET BYTE one:";
t = vbyte_one
PRINT t
PRINT "= UOFFSET BYTE r1:";
t = vbyte_r1
PRINT t
PRINT "= UOFFSET BYTE r2:";
t = vbyte_r2
PRINT t
PRINT "= UOFFSET UBYTE min:";
t = vubyte_min
PRINT t
PRINT "= UOFFSET UBYTE max:";
t = vubyte_max
PRINT t
PRINT "= UOFFSET UBYTE m1:";
t = vubyte_m1
PRINT t
PRINT "= UOFFSET UBYTE zero:";
t = vubyte_zero
PRINT t
PRINT "= UOFFSET UBYTE one:";
t = vubyte_one
PRINT t
PRINT "= UOFFSET UBYTE r1:";
t = vubyte_r1
PRINT t
PRINT "= UOFFSET UBYTE r2:";
t = vubyte_r2
PRINT t
PRINT "= UOFFSET INTEGER min:";
t = vinteger_min
PRINT t
PRINT "= UOFFSET INTEGER max:";
t = vinteger_max
PRINT t
PRINT "= UOFFSET INTEGER m1:";
t = vinteger_m1
PRINT t
PRINT "= UOFFSET INTEGER zero:";
t = vinteger_zero
PRINT t
PRINT "= UOFFSET INTEGER one:";
t = vinteger_one
PRINT t
PRINT "= UOFFSET INTEGER r1:";
t = vinteger_r1
PRINT t
PRINT "= UOFFSET INTEGER r2:";
t = vinteger_r2
PRINT t
PRINT "= UOFFSET UINTEGER min:";
t = vuinteger_min
PRINT t
PRINT "= UOFFSET UINTEGER max:";
t = vuinteger_max
PRINT t
PRINT "= UOFFSET UINTEGER m1:";
t = vuinteger_m1
PRINT t
PRINT "= UOFFSET UINTEGER zero:";
t = vuinteger_zero
PRINT t
PRINT "= UOFFSET UINTEGER one:";
t = vuinteger_one
PRINT t
PRINT "= UOFFSET UINTEGER r1:";
t = vuinteger_r1
PRINT t
PRINT "= UOFFSET UINTEGER r2:";
t = vuinteger_r2
PRINT t
PRINT "= UOFFSET LONG min:";
t = vlong_min
PRINT t
PRINT "= UOFFSET LONG max:";
t = vlong_max
PRINT t
PRINT "= UOFFSET LONG m1:";
t = vlong_m1
PRINT t
PRINT "= UOFFSET LONG zero:";
t = vlong_zero
PRINT t
PRINT "= UOFFSET LONG one:";
t = vlong_one
PRINT t
PRINT "= UOFFSET LONG r1:";
t = vlong_r1
PRINT t
PRINT "= UOFFSET LONG r2:";
t = vlong_r2
PRINT t
PRINT "= UOFFSET ULONG min:";
t = vulong_min
PRINT t
PRINT "= UOFFSET ULONG max:";
t = vulong_max
PRINT t
PRINT "= UOFFSET ULONG m1:";
t = vulong_m1
PRINT t
PRINT "= UOFFSET ULONG zero:";
t = vulong_zero
PRINT t
PRINT "= UOFFSET ULONG one:";
t = vulong_one
PRINT t
PRINT "= UOFFSET ULONG r1:";
t = vulong_r1
PRINT t
PRINT "= UOFFSET ULONG r2:";
t = vulong_r2
PRINT t
PRINT "= UOFFSET INT64 min:";
t = vint64_min
PRINT t
PRINT "= UOFFSET INT64 max:";
t = vint64_max
PRINT t
PRINT "= UOFFSET INT64 m1:";
t = vint64_m1
PRINT t
PRINT "= UOFFSET INT64 zero:";
t = vint64_zero
PRINT t
PRINT "= UOFFSET INT64 one:";
t = vint64_one
PRINT t
PRINT "= UOFFSET INT64 r1:";
t = vint64_r1
PRINT t
PRINT "= UOFFSET INT64 r2:";
t = vint64_r2
PRINT t
PRINT "= UOFFSET UINT64 min:";
t = vuint64_min
PRINT t
PRINT "= UOFFSET UINT64 max:";
t = vuint64_max
PRINT t
PRINT "= UOFFSET UINT64 m1:";
t = vuint64_m1
PRINT t
PRINT "= UOFFSET UINT64 zero:";
t = vuint64_zero
PRINT t
PRINT "= UOFFSET UINT64 one:";
t = vuint64_one
PRINT t
PRINT "= UOFFSET UINT64 r1:";
t = vuint64_r1
PRINT t
PRINT "= UOFFSET UINT64 r2:";
t = vuint64_r2
PRINT t
PRINT "= UOFFSET OFFSET min:";
t = voffset_min
PRINT t
PRINT "= UOFFSET OFFSET max:";
t = voffset_max
PRINT t
PRINT "= UOFFSET OFFSET m1:";
t = voffset_m1
PRINT t
PRINT "= UOFFSET OFFSET zero:";
t = voffset_zero
PRINT t
PRINT "= UOFFSET OFFSET one:";
t = voffset_one
PRINT t
PRINT "= UOFFSET OFFSET r1:";
t = voffset_r1
PRINT t
PRINT "= UOFFSET OFFSET r2:";
t = voffset_r2
PRINT t
PRINT "= UOFFSET UOFFSET min:";
t = vuoffset_min
PRINT t
PRINT "= UOFFSET UOFFSET max:";
t = vuoffset_max
PRINT t
PRINT "= UOFFSET UOFFSET m1:";
t = vuoffset_m1
PRINT t
PRINT "= UOFFSET UOFFSET zero:";
t = vuoffset_zero
PRINT t
PRINT "= UOFFSET UOFFSET one:";
t = vuoffset_one
PRINT t
PRINT "= UOFFSET UOFFSET r1:";
t = vuoffset_r1
PRINT t
PRINT "= UOFFSET UOFFSET r2:";
t = vuoffset_r2
PRINT t
PRINT "= UOFFSET BIT min:";
t = vbit_min
PRINT t
PRINT "= UOFFSET BIT max:";
t = vbit_max
PRINT t
PRINT "= UOFFSET BIT m1:";
t = vbit_m1
PRINT t
PRINT "= UOFFSET BIT zero:";
t = vbit_zero
PRINT t
PRINT "= UOFFSET BIT one:";
t = vbit_one
PRINT t
PRINT "= UOFFSET BIT r1:";
t = vbit_r1
PRINT t
PRINT "= UOFFSET BIT r2:";
t = vbit_r2
PRINT t
PRINT "= UOFFSET UBIT7 min:";
t = vubit7_min
PRINT t
PRINT "= UOFFSET UBIT7 max:";
t = vubit7_max
PRINT t
PRINT "= UOFFSET UBIT7 m1:";
t = vubit7_m1
PRINT t
PRINT "= UOFFSET UBIT7 zero:";
t = vubit7_zero
PRINT t
PRINT "= UOFFSET UBIT7 one:";
t = vubit7_one
PRINT t
PRINT "= UOFFSET UBIT7 r1:";
t = vubit7_r1
PRINT t
PRINT "= UOFFSET UBIT7 r2:";
t = vubit7_r2
PRINT t
PRINT "= UOFFSET BIT24 min:";
t = vbit24_min
PRINT t
PRINT "= UOFFSET BIT24 max:";
t = vbit24_max
PRINT t
PRINT "= UOFFSET BIT24 m1:";
t = vbit24_m1
PRINT t
PRINT "= UOFFSET BIT24 zero:";
t = vbit24_zero
PRINT t
PRINT "= UOFFSET BIT24 one:";
t = vbit24_one
PRINT t
PRINT "= UOFFSET BIT24 r1:";
t = vbit24_r1
PRINT t
PRINT "= UOFFSET BIT24 r2:";
t = vbit24_r2
PRINT t
PRINT "= UOFFSET UBIT40 min:";
t = vubit40_min
PRINT t
PRINT "= UOFFSET UBIT40 max:";
t = vubit40_max
PRINT t
PRINT "= UOFFSET UBIT40 m1:";
t = vubit40_m1
PRINT t
PRINT "= UOFFSET UBIT40 zero:";
t = vubit40_zero
PRINT t
PRINT "= UOFFSET UBIT40 one:";
t = vubit40_one
PRINT t
PRINT "= UOFFSET UBIT40 r1:";
t = vubit40_r1
PRINT t
PRINT "= UOFFSET UBIT40 r2:";
t = vubit40_r2
PRINT t
PRINT "= UOFFSET SINGLE min:";
t = vsingle_min
PRINT t
PRINT "= UOFFSET SINGLE max:";
t = vsingle_max
PRINT t
PRINT "= UOFFSET SINGLE m1:";
t = vsingle_m1
PRINT t
PRINT "= UOFFSET SINGLE zero:";
t = vsingle_zero
PRINT t
PRINT "= UOFFSET SINGLE one:";
t = vsingle_one
PRINT t
PRINT "= UOFFSET SINGLE r1:";
t = vsingle_r1
PRINT t
PRINT "= UOFFSET SINGLE r2:";
t = vsingle_r2
PRINT t
PRINT "= UOFFSET DOUBLE min:";
t = vdouble_min
PRINT t
PRINT "= UOFFSET DOUBLE max:";
t = vdouble_max
PRINT t
PRINT "= UOFFSET DOUBLE m1:";
t = vdouble_m1
PRINT t
PRINT "= UOFFSET DOUBLE zero:";
t = vdouble_zero
PRINT t
PRINT "= UOFFSET DOUBLE one:";
t = vdouble_one
PRINT t
PRINT "= UOFFSET DOUBLE r1:";
t = vdouble_r1
PRINT t
PRINT "= UOFFSET DOUBLE r2:";
t = vdouble_r2
PRINT t
PRINT "= UOFFSET FLOAT min:";
t = vfloat_min
PRINT t
PRINT "= UOFFSET FLOAT max:";
t = vfloat_max
PRINT t
PRINT "= UOFFSET FLOAT m1:";
t = vfloat_m1
PRINT t
PRINT "= UOFFSET FLOAT zero:";
t = vfloat_zero
PRINT t
PRINT "= UOFFSET FLOAT one:";
t = vfloat_one
PRINT t
PRINT "= UOFFSET FLOAT r1:";
t = vfloat_r1
PRINT t
PRINT "= UOFFSET FLOAT r2:";
t = vfloat_r2
PRINT t
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
