$CONSOLE:ONLY
' Differential program (m2-numeric-types, design D2): -, NOT and _NEGATE on every numeric type's values.
' Generated by crates/difftest (cargo run -p qb64rust-difftest -- gen): do not edit. The expected output
' is recorded with qb64pe.exe (tests/differential/README.md). A runtime error prints ERR and resumes next.
' Each _BIT * 40 has a _BIT * 32 pad DIMmed just before it, which the old compiler's overlap hits
' instead (DIVERGENCES.md D-009).
ON ERROR GOTO h
DIM vbyte_min AS _BYTE
DIM vbyte_max AS _BYTE
DIM vbyte_m1 AS _BYTE
DIM vbyte_zero AS _BYTE
DIM vbyte_one AS _BYTE
DIM vbyte_r1 AS _BYTE
DIM vbyte_r2 AS _BYTE
DIM vubyte_min AS _UNSIGNED _BYTE
DIM vubyte_max AS _UNSIGNED _BYTE
DIM vubyte_m1 AS _UNSIGNED _BYTE
DIM vubyte_zero AS _UNSIGNED _BYTE
DIM vubyte_one AS _UNSIGNED _BYTE
DIM vubyte_r1 AS _UNSIGNED _BYTE
DIM vubyte_r2 AS _UNSIGNED _BYTE
DIM vinteger_min AS INTEGER
DIM vinteger_max AS INTEGER
DIM vinteger_m1 AS INTEGER
DIM vinteger_zero AS INTEGER
DIM vinteger_one AS INTEGER
DIM vinteger_r1 AS INTEGER
DIM vinteger_r2 AS INTEGER
DIM vuinteger_min AS _UNSIGNED INTEGER
DIM vuinteger_max AS _UNSIGNED INTEGER
DIM vuinteger_m1 AS _UNSIGNED INTEGER
DIM vuinteger_zero AS _UNSIGNED INTEGER
DIM vuinteger_one AS _UNSIGNED INTEGER
DIM vuinteger_r1 AS _UNSIGNED INTEGER
DIM vuinteger_r2 AS _UNSIGNED INTEGER
DIM vlong_min AS LONG
DIM vlong_max AS LONG
DIM vlong_m1 AS LONG
DIM vlong_zero AS LONG
DIM vlong_one AS LONG
DIM vlong_r1 AS LONG
DIM vlong_r2 AS LONG
DIM vulong_min AS _UNSIGNED LONG
DIM vulong_max AS _UNSIGNED LONG
DIM vulong_m1 AS _UNSIGNED LONG
DIM vulong_zero AS _UNSIGNED LONG
DIM vulong_one AS _UNSIGNED LONG
DIM vulong_r1 AS _UNSIGNED LONG
DIM vulong_r2 AS _UNSIGNED LONG
DIM vint64_min AS _INTEGER64
DIM vint64_max AS _INTEGER64
DIM vint64_m1 AS _INTEGER64
DIM vint64_zero AS _INTEGER64
DIM vint64_one AS _INTEGER64
DIM vint64_r1 AS _INTEGER64
DIM vint64_r2 AS _INTEGER64
DIM vuint64_min AS _UNSIGNED _INTEGER64
DIM vuint64_max AS _UNSIGNED _INTEGER64
DIM vuint64_m1 AS _UNSIGNED _INTEGER64
DIM vuint64_zero AS _UNSIGNED _INTEGER64
DIM vuint64_one AS _UNSIGNED _INTEGER64
DIM vuint64_r1 AS _UNSIGNED _INTEGER64
DIM vuint64_r2 AS _UNSIGNED _INTEGER64
DIM voffset_min AS _OFFSET
DIM voffset_max AS _OFFSET
DIM voffset_m1 AS _OFFSET
DIM voffset_zero AS _OFFSET
DIM voffset_one AS _OFFSET
DIM voffset_r1 AS _OFFSET
DIM voffset_r2 AS _OFFSET
DIM vuoffset_min AS _UNSIGNED _OFFSET
DIM vuoffset_max AS _UNSIGNED _OFFSET
DIM vuoffset_m1 AS _UNSIGNED _OFFSET
DIM vuoffset_zero AS _UNSIGNED _OFFSET
DIM vuoffset_one AS _UNSIGNED _OFFSET
DIM vuoffset_r1 AS _UNSIGNED _OFFSET
DIM vuoffset_r2 AS _UNSIGNED _OFFSET
DIM vbit_min AS _BIT
DIM vbit_max AS _BIT
DIM vbit_m1 AS _BIT
DIM vbit_zero AS _BIT
DIM vbit_one AS _BIT
DIM vbit_r1 AS _BIT
DIM vbit_r2 AS _BIT
DIM vubit7_min AS _UNSIGNED _BIT * 7
DIM vubit7_max AS _UNSIGNED _BIT * 7
DIM vubit7_m1 AS _UNSIGNED _BIT * 7
DIM vubit7_zero AS _UNSIGNED _BIT * 7
DIM vubit7_one AS _UNSIGNED _BIT * 7
DIM vubit7_r1 AS _UNSIGNED _BIT * 7
DIM vubit7_r2 AS _UNSIGNED _BIT * 7
DIM vbit24_min AS _BIT * 24
DIM vbit24_max AS _BIT * 24
DIM vbit24_m1 AS _BIT * 24
DIM vbit24_zero AS _BIT * 24
DIM vbit24_one AS _BIT * 24
DIM vbit24_r1 AS _BIT * 24
DIM vbit24_r2 AS _BIT * 24
DIM pad_vubit40_min AS _BIT * 32
DIM vubit40_min AS _UNSIGNED _BIT * 40
DIM pad_vubit40_max AS _BIT * 32
DIM vubit40_max AS _UNSIGNED _BIT * 40
DIM pad_vubit40_m1 AS _BIT * 32
DIM vubit40_m1 AS _UNSIGNED _BIT * 40
DIM pad_vubit40_zero AS _BIT * 32
DIM vubit40_zero AS _UNSIGNED _BIT * 40
DIM pad_vubit40_one AS _BIT * 32
DIM vubit40_one AS _UNSIGNED _BIT * 40
DIM pad_vubit40_r1 AS _BIT * 32
DIM vubit40_r1 AS _UNSIGNED _BIT * 40
DIM pad_vubit40_r2 AS _BIT * 32
DIM vubit40_r2 AS _UNSIGNED _BIT * 40
DIM vsingle_min AS SINGLE
DIM vsingle_max AS SINGLE
DIM vsingle_m1 AS SINGLE
DIM vsingle_zero AS SINGLE
DIM vsingle_one AS SINGLE
DIM vsingle_r1 AS SINGLE
DIM vsingle_r2 AS SINGLE
DIM vdouble_min AS DOUBLE
DIM vdouble_max AS DOUBLE
DIM vdouble_m1 AS DOUBLE
DIM vdouble_zero AS DOUBLE
DIM vdouble_one AS DOUBLE
DIM vdouble_r1 AS DOUBLE
DIM vdouble_r2 AS DOUBLE
DIM vfloat_min AS _FLOAT
DIM vfloat_max AS _FLOAT
DIM vfloat_m1 AS _FLOAT
DIM vfloat_zero AS _FLOAT
DIM vfloat_one AS _FLOAT
DIM vfloat_r1 AS _FLOAT
DIM vfloat_r2 AS _FLOAT
vbyte_min = -128%%
vbyte_max = 127%%
vbyte_m1 = -1%%
vbyte_zero = 0%%
vbyte_one = 1%%
vbyte_r1 = 103%%
vbyte_r2 = -56%%
vubyte_min = 0~%%
vubyte_max = 255~%%
vubyte_m1 = 255~%%
vubyte_zero = 0~%%
vubyte_one = 1~%%
vubyte_r1 = 32~%%
vubyte_r2 = 20~%%
vinteger_min = -32768%
vinteger_max = 32767%
vinteger_m1 = -1%
vinteger_zero = 0%
vinteger_one = 1%
vinteger_r1 = -2895%
vinteger_r2 = 5580%
vuinteger_min = 0~%
vuinteger_max = 65535~%
vuinteger_m1 = 65535~%
vuinteger_zero = 0~%
vuinteger_one = 1~%
vuinteger_r1 = 36936~%
vuinteger_r2 = 38734~%
vlong_min = -2147483648&
vlong_max = 2147483647&
vlong_m1 = -1&
vlong_zero = 0&
vlong_one = 1&
vlong_r1 = -559627433&
vlong_r2 = -709606431&
vulong_min = 0~&
vulong_max = 4294967295~&
vulong_m1 = 4294967295~&
vulong_zero = 0~&
vulong_one = 1~&
vulong_r1 = 3095748532~&
vulong_r2 = 2247239029~&
vint64_min = (-9223372036854775807&& - 1)
vint64_max = 9223372036854775807&&
vint64_m1 = -1&&
vint64_zero = 0&&
vint64_one = 1&&
vint64_r1 = 5819978767338316436&&
vint64_r2 = 7445081360591965601&&
vuint64_min = 0~&&
vuint64_max = 18446744073709551615~&&
vuint64_m1 = 18446744073709551615~&&
vuint64_zero = 0~&&
vuint64_one = 1~&&
vuint64_r1 = 14721352250261409079~&&
vuint64_r2 = 1695248715451867090~&&
voffset_min = (-9223372036854775807&& - 1)
voffset_max = 9223372036854775807&&
voffset_m1 = -1&&
voffset_zero = 0&&
voffset_one = 1&&
voffset_r1 = 1887714948171717615&&
voffset_r2 = -4592622012093347915&&
vuoffset_min = 0~&&
vuoffset_max = 18446744073709551615~&&
vuoffset_m1 = 18446744073709551615~&&
vuoffset_zero = 0~&&
vuoffset_one = 1~&&
vuoffset_r1 = 15919602987562150171~&&
vuoffset_r2 = 16266618817563032314~&&
vbit_min = -1`
vbit_max = 0`
vbit_m1 = -1`
vbit_zero = 0`
vbit_one = 0`
vbit_r1 = 0`
vbit_r2 = -1`
vubit7_min = 0~`7
vubit7_max = 127~`7
vubit7_m1 = 127~`7
vubit7_zero = 0~`7
vubit7_one = 1~`7
vubit7_r1 = 25~`7
vubit7_r2 = 74~`7
vbit24_min = -8388608`24
vbit24_max = 8388607`24
vbit24_m1 = -1`24
vbit24_zero = 0`24
vbit24_one = 1`24
vbit24_r1 = 3148653`24
vbit24_r2 = -2716775`24
vubit40_min = 0~`40
vubit40_max = 1099511627775~`40
vubit40_m1 = 1099511627775~`40
vubit40_zero = 0~`40
vubit40_one = 1~`40
vubit40_r1 = 464297847704~`40
vubit40_r2 = 488476189167~`40
vsingle_min = -3.402823E+38
vsingle_max = 3.402823E+38
vsingle_m1 = -1!
vsingle_zero = 0!
vsingle_one = 1!
vsingle_r1 = 0.2!
vsingle_r2 = -0.2253!
vdouble_min = -1.797693134862315D+308
vdouble_max = 1.797693134862315D+308
vdouble_m1 = -1#
vdouble_zero = 0#
vdouble_one = 1#
vdouble_r1 = -166203811.12578#
vdouble_r2 = -12534.17#
vfloat_min = -1.797693134862315F+308
vfloat_max = 1.797693134862315F+308
vfloat_m1 = -1##
vfloat_zero = 0##
vfloat_one = 1##
vfloat_r1 = -0.90##
vfloat_r2 = 478.10157##
PRINT "- BYTE min:"; -vbyte_min
PRINT "- BYTE max:"; -vbyte_max
PRINT "- BYTE m1:"; -vbyte_m1
PRINT "- BYTE zero:"; -vbyte_zero
PRINT "- BYTE one:"; -vbyte_one
PRINT "- BYTE r1:"; -vbyte_r1
PRINT "- BYTE r2:"; -vbyte_r2
PRINT "- UBYTE min:"; -vubyte_min
PRINT "- UBYTE max:"; -vubyte_max
PRINT "- UBYTE m1:"; -vubyte_m1
PRINT "- UBYTE zero:"; -vubyte_zero
PRINT "- UBYTE one:"; -vubyte_one
PRINT "- UBYTE r1:"; -vubyte_r1
PRINT "- UBYTE r2:"; -vubyte_r2
PRINT "- INTEGER min:"; -vinteger_min
PRINT "- INTEGER max:"; -vinteger_max
PRINT "- INTEGER m1:"; -vinteger_m1
PRINT "- INTEGER zero:"; -vinteger_zero
PRINT "- INTEGER one:"; -vinteger_one
PRINT "- INTEGER r1:"; -vinteger_r1
PRINT "- INTEGER r2:"; -vinteger_r2
PRINT "- UINTEGER min:"; -vuinteger_min
PRINT "- UINTEGER max:"; -vuinteger_max
PRINT "- UINTEGER m1:"; -vuinteger_m1
PRINT "- UINTEGER zero:"; -vuinteger_zero
PRINT "- UINTEGER one:"; -vuinteger_one
PRINT "- UINTEGER r1:"; -vuinteger_r1
PRINT "- UINTEGER r2:"; -vuinteger_r2
PRINT "- LONG min:"; -vlong_min
PRINT "- LONG max:"; -vlong_max
PRINT "- LONG m1:"; -vlong_m1
PRINT "- LONG zero:"; -vlong_zero
PRINT "- LONG one:"; -vlong_one
PRINT "- LONG r1:"; -vlong_r1
PRINT "- LONG r2:"; -vlong_r2
PRINT "- ULONG min:"; -vulong_min
PRINT "- ULONG max:"; -vulong_max
PRINT "- ULONG m1:"; -vulong_m1
PRINT "- ULONG zero:"; -vulong_zero
PRINT "- ULONG one:"; -vulong_one
PRINT "- ULONG r1:"; -vulong_r1
PRINT "- ULONG r2:"; -vulong_r2
PRINT "- INT64 min:"; -vint64_min
PRINT "- INT64 max:"; -vint64_max
PRINT "- INT64 m1:"; -vint64_m1
PRINT "- INT64 zero:"; -vint64_zero
PRINT "- INT64 one:"; -vint64_one
PRINT "- INT64 r1:"; -vint64_r1
PRINT "- INT64 r2:"; -vint64_r2
PRINT "- UINT64 min:"; -vuint64_min
PRINT "- UINT64 max:"; -vuint64_max
PRINT "- UINT64 m1:"; -vuint64_m1
PRINT "- UINT64 zero:"; -vuint64_zero
PRINT "- UINT64 one:"; -vuint64_one
PRINT "- UINT64 r1:"; -vuint64_r1
PRINT "- UINT64 r2:"; -vuint64_r2
PRINT "- OFFSET min:"; -voffset_min
PRINT "- OFFSET max:"; -voffset_max
PRINT "- OFFSET m1:"; -voffset_m1
PRINT "- OFFSET zero:"; -voffset_zero
PRINT "- OFFSET one:"; -voffset_one
PRINT "- OFFSET r1:"; -voffset_r1
PRINT "- OFFSET r2:"; -voffset_r2
PRINT "- UOFFSET min:"; -vuoffset_min
PRINT "- UOFFSET max:"; -vuoffset_max
PRINT "- UOFFSET m1:"; -vuoffset_m1
PRINT "- UOFFSET zero:"; -vuoffset_zero
PRINT "- UOFFSET one:"; -vuoffset_one
PRINT "- UOFFSET r1:"; -vuoffset_r1
PRINT "- UOFFSET r2:"; -vuoffset_r2
PRINT "- BIT min:"; -vbit_min
PRINT "- BIT max:"; -vbit_max
PRINT "- BIT m1:"; -vbit_m1
PRINT "- BIT zero:"; -vbit_zero
PRINT "- BIT one:"; -vbit_one
PRINT "- BIT r1:"; -vbit_r1
PRINT "- BIT r2:"; -vbit_r2
PRINT "- UBIT7 min:"; -vubit7_min
PRINT "- UBIT7 max:"; -vubit7_max
PRINT "- UBIT7 m1:"; -vubit7_m1
PRINT "- UBIT7 zero:"; -vubit7_zero
PRINT "- UBIT7 one:"; -vubit7_one
PRINT "- UBIT7 r1:"; -vubit7_r1
PRINT "- UBIT7 r2:"; -vubit7_r2
PRINT "- BIT24 min:"; -vbit24_min
PRINT "- BIT24 max:"; -vbit24_max
PRINT "- BIT24 m1:"; -vbit24_m1
PRINT "- BIT24 zero:"; -vbit24_zero
PRINT "- BIT24 one:"; -vbit24_one
PRINT "- BIT24 r1:"; -vbit24_r1
PRINT "- BIT24 r2:"; -vbit24_r2
PRINT "- UBIT40 min:"; -vubit40_min
PRINT "- UBIT40 max:"; -vubit40_max
PRINT "- UBIT40 m1:"; -vubit40_m1
PRINT "- UBIT40 zero:"; -vubit40_zero
PRINT "- UBIT40 one:"; -vubit40_one
PRINT "- UBIT40 r1:"; -vubit40_r1
PRINT "- UBIT40 r2:"; -vubit40_r2
PRINT "- SINGLE min:"; -vsingle_min
PRINT "- SINGLE max:"; -vsingle_max
PRINT "- SINGLE m1:"; -vsingle_m1
PRINT "- SINGLE zero:"; -vsingle_zero
PRINT "- SINGLE one:"; -vsingle_one
PRINT "- SINGLE r1:"; -vsingle_r1
PRINT "- SINGLE r2:"; -vsingle_r2
PRINT "- DOUBLE min:"; -vdouble_min
PRINT "- DOUBLE max:"; -vdouble_max
PRINT "- DOUBLE m1:"; -vdouble_m1
PRINT "- DOUBLE zero:"; -vdouble_zero
PRINT "- DOUBLE one:"; -vdouble_one
PRINT "- DOUBLE r1:"; -vdouble_r1
PRINT "- DOUBLE r2:"; -vdouble_r2
PRINT "- FLOAT min:"; -vfloat_min
PRINT "- FLOAT max:"; -vfloat_max
PRINT "- FLOAT m1:"; -vfloat_m1
PRINT "- FLOAT zero:"; -vfloat_zero
PRINT "- FLOAT one:"; -vfloat_one
PRINT "- FLOAT r1:"; -vfloat_r1
PRINT "- FLOAT r2:"; -vfloat_r2
PRINT "NOT BYTE min:"; NOT vbyte_min
PRINT "NOT BYTE max:"; NOT vbyte_max
PRINT "NOT BYTE m1:"; NOT vbyte_m1
PRINT "NOT BYTE zero:"; NOT vbyte_zero
PRINT "NOT BYTE one:"; NOT vbyte_one
PRINT "NOT BYTE r1:"; NOT vbyte_r1
PRINT "NOT BYTE r2:"; NOT vbyte_r2
PRINT "NOT UBYTE min:"; NOT vubyte_min
PRINT "NOT UBYTE max:"; NOT vubyte_max
PRINT "NOT UBYTE m1:"; NOT vubyte_m1
PRINT "NOT UBYTE zero:"; NOT vubyte_zero
PRINT "NOT UBYTE one:"; NOT vubyte_one
PRINT "NOT UBYTE r1:"; NOT vubyte_r1
PRINT "NOT UBYTE r2:"; NOT vubyte_r2
PRINT "NOT INTEGER min:"; NOT vinteger_min
PRINT "NOT INTEGER max:"; NOT vinteger_max
PRINT "NOT INTEGER m1:"; NOT vinteger_m1
PRINT "NOT INTEGER zero:"; NOT vinteger_zero
PRINT "NOT INTEGER one:"; NOT vinteger_one
PRINT "NOT INTEGER r1:"; NOT vinteger_r1
PRINT "NOT INTEGER r2:"; NOT vinteger_r2
PRINT "NOT UINTEGER min:"; NOT vuinteger_min
PRINT "NOT UINTEGER max:"; NOT vuinteger_max
PRINT "NOT UINTEGER m1:"; NOT vuinteger_m1
PRINT "NOT UINTEGER zero:"; NOT vuinteger_zero
PRINT "NOT UINTEGER one:"; NOT vuinteger_one
PRINT "NOT UINTEGER r1:"; NOT vuinteger_r1
PRINT "NOT UINTEGER r2:"; NOT vuinteger_r2
PRINT "NOT LONG min:"; NOT vlong_min
PRINT "NOT LONG max:"; NOT vlong_max
PRINT "NOT LONG m1:"; NOT vlong_m1
PRINT "NOT LONG zero:"; NOT vlong_zero
PRINT "NOT LONG one:"; NOT vlong_one
PRINT "NOT LONG r1:"; NOT vlong_r1
PRINT "NOT LONG r2:"; NOT vlong_r2
PRINT "NOT ULONG min:"; NOT vulong_min
PRINT "NOT ULONG max:"; NOT vulong_max
PRINT "NOT ULONG m1:"; NOT vulong_m1
PRINT "NOT ULONG zero:"; NOT vulong_zero
PRINT "NOT ULONG one:"; NOT vulong_one
PRINT "NOT ULONG r1:"; NOT vulong_r1
PRINT "NOT ULONG r2:"; NOT vulong_r2
PRINT "NOT INT64 min:"; NOT vint64_min
PRINT "NOT INT64 max:"; NOT vint64_max
PRINT "NOT INT64 m1:"; NOT vint64_m1
PRINT "NOT INT64 zero:"; NOT vint64_zero
PRINT "NOT INT64 one:"; NOT vint64_one
PRINT "NOT INT64 r1:"; NOT vint64_r1
PRINT "NOT INT64 r2:"; NOT vint64_r2
PRINT "NOT UINT64 min:"; NOT vuint64_min
PRINT "NOT UINT64 max:"; NOT vuint64_max
PRINT "NOT UINT64 m1:"; NOT vuint64_m1
PRINT "NOT UINT64 zero:"; NOT vuint64_zero
PRINT "NOT UINT64 one:"; NOT vuint64_one
PRINT "NOT UINT64 r1:"; NOT vuint64_r1
PRINT "NOT UINT64 r2:"; NOT vuint64_r2
PRINT "NOT OFFSET min:"; NOT voffset_min
PRINT "NOT OFFSET max:"; NOT voffset_max
PRINT "NOT OFFSET m1:"; NOT voffset_m1
PRINT "NOT OFFSET zero:"; NOT voffset_zero
PRINT "NOT OFFSET one:"; NOT voffset_one
PRINT "NOT OFFSET r1:"; NOT voffset_r1
PRINT "NOT OFFSET r2:"; NOT voffset_r2
PRINT "NOT UOFFSET min:"; NOT vuoffset_min
PRINT "NOT UOFFSET max:"; NOT vuoffset_max
PRINT "NOT UOFFSET m1:"; NOT vuoffset_m1
PRINT "NOT UOFFSET zero:"; NOT vuoffset_zero
PRINT "NOT UOFFSET one:"; NOT vuoffset_one
PRINT "NOT UOFFSET r1:"; NOT vuoffset_r1
PRINT "NOT UOFFSET r2:"; NOT vuoffset_r2
PRINT "NOT BIT min:"; NOT vbit_min
PRINT "NOT BIT max:"; NOT vbit_max
PRINT "NOT BIT m1:"; NOT vbit_m1
PRINT "NOT BIT zero:"; NOT vbit_zero
PRINT "NOT BIT one:"; NOT vbit_one
PRINT "NOT BIT r1:"; NOT vbit_r1
PRINT "NOT BIT r2:"; NOT vbit_r2
PRINT "NOT UBIT7 min:"; NOT vubit7_min
PRINT "NOT UBIT7 max:"; NOT vubit7_max
PRINT "NOT UBIT7 m1:"; NOT vubit7_m1
PRINT "NOT UBIT7 zero:"; NOT vubit7_zero
PRINT "NOT UBIT7 one:"; NOT vubit7_one
PRINT "NOT UBIT7 r1:"; NOT vubit7_r1
PRINT "NOT UBIT7 r2:"; NOT vubit7_r2
PRINT "NOT BIT24 min:"; NOT vbit24_min
PRINT "NOT BIT24 max:"; NOT vbit24_max
PRINT "NOT BIT24 m1:"; NOT vbit24_m1
PRINT "NOT BIT24 zero:"; NOT vbit24_zero
PRINT "NOT BIT24 one:"; NOT vbit24_one
PRINT "NOT BIT24 r1:"; NOT vbit24_r1
PRINT "NOT BIT24 r2:"; NOT vbit24_r2
PRINT "NOT UBIT40 min:"; NOT vubit40_min
PRINT "NOT UBIT40 max:"; NOT vubit40_max
PRINT "NOT UBIT40 m1:"; NOT vubit40_m1
PRINT "NOT UBIT40 zero:"; NOT vubit40_zero
PRINT "NOT UBIT40 one:"; NOT vubit40_one
PRINT "NOT UBIT40 r1:"; NOT vubit40_r1
PRINT "NOT UBIT40 r2:"; NOT vubit40_r2
PRINT "NOT SINGLE min:"; NOT vsingle_min
PRINT "NOT SINGLE max:"; NOT vsingle_max
PRINT "NOT SINGLE m1:"; NOT vsingle_m1
PRINT "NOT SINGLE zero:"; NOT vsingle_zero
PRINT "NOT SINGLE one:"; NOT vsingle_one
PRINT "NOT SINGLE r1:"; NOT vsingle_r1
PRINT "NOT SINGLE r2:"; NOT vsingle_r2
PRINT "NOT DOUBLE min:"; NOT vdouble_min
PRINT "NOT DOUBLE max:"; NOT vdouble_max
PRINT "NOT DOUBLE m1:"; NOT vdouble_m1
PRINT "NOT DOUBLE zero:"; NOT vdouble_zero
PRINT "NOT DOUBLE one:"; NOT vdouble_one
PRINT "NOT DOUBLE r1:"; NOT vdouble_r1
PRINT "NOT DOUBLE r2:"; NOT vdouble_r2
PRINT "NOT FLOAT min:"; NOT vfloat_min
PRINT "NOT FLOAT max:"; NOT vfloat_max
PRINT "NOT FLOAT m1:"; NOT vfloat_m1
PRINT "NOT FLOAT zero:"; NOT vfloat_zero
PRINT "NOT FLOAT one:"; NOT vfloat_one
PRINT "NOT FLOAT r1:"; NOT vfloat_r1
PRINT "NOT FLOAT r2:"; NOT vfloat_r2
PRINT "_NEGATE BYTE min:"; _NEGATE vbyte_min
PRINT "_NEGATE BYTE max:"; _NEGATE vbyte_max
PRINT "_NEGATE BYTE m1:"; _NEGATE vbyte_m1
PRINT "_NEGATE BYTE zero:"; _NEGATE vbyte_zero
PRINT "_NEGATE BYTE one:"; _NEGATE vbyte_one
PRINT "_NEGATE BYTE r1:"; _NEGATE vbyte_r1
PRINT "_NEGATE BYTE r2:"; _NEGATE vbyte_r2
PRINT "_NEGATE UBYTE min:"; _NEGATE vubyte_min
PRINT "_NEGATE UBYTE max:"; _NEGATE vubyte_max
PRINT "_NEGATE UBYTE m1:"; _NEGATE vubyte_m1
PRINT "_NEGATE UBYTE zero:"; _NEGATE vubyte_zero
PRINT "_NEGATE UBYTE one:"; _NEGATE vubyte_one
PRINT "_NEGATE UBYTE r1:"; _NEGATE vubyte_r1
PRINT "_NEGATE UBYTE r2:"; _NEGATE vubyte_r2
PRINT "_NEGATE INTEGER min:"; _NEGATE vinteger_min
PRINT "_NEGATE INTEGER max:"; _NEGATE vinteger_max
PRINT "_NEGATE INTEGER m1:"; _NEGATE vinteger_m1
PRINT "_NEGATE INTEGER zero:"; _NEGATE vinteger_zero
PRINT "_NEGATE INTEGER one:"; _NEGATE vinteger_one
PRINT "_NEGATE INTEGER r1:"; _NEGATE vinteger_r1
PRINT "_NEGATE INTEGER r2:"; _NEGATE vinteger_r2
PRINT "_NEGATE UINTEGER min:"; _NEGATE vuinteger_min
PRINT "_NEGATE UINTEGER max:"; _NEGATE vuinteger_max
PRINT "_NEGATE UINTEGER m1:"; _NEGATE vuinteger_m1
PRINT "_NEGATE UINTEGER zero:"; _NEGATE vuinteger_zero
PRINT "_NEGATE UINTEGER one:"; _NEGATE vuinteger_one
PRINT "_NEGATE UINTEGER r1:"; _NEGATE vuinteger_r1
PRINT "_NEGATE UINTEGER r2:"; _NEGATE vuinteger_r2
PRINT "_NEGATE LONG min:"; _NEGATE vlong_min
PRINT "_NEGATE LONG max:"; _NEGATE vlong_max
PRINT "_NEGATE LONG m1:"; _NEGATE vlong_m1
PRINT "_NEGATE LONG zero:"; _NEGATE vlong_zero
PRINT "_NEGATE LONG one:"; _NEGATE vlong_one
PRINT "_NEGATE LONG r1:"; _NEGATE vlong_r1
PRINT "_NEGATE LONG r2:"; _NEGATE vlong_r2
PRINT "_NEGATE ULONG min:"; _NEGATE vulong_min
PRINT "_NEGATE ULONG max:"; _NEGATE vulong_max
PRINT "_NEGATE ULONG m1:"; _NEGATE vulong_m1
PRINT "_NEGATE ULONG zero:"; _NEGATE vulong_zero
PRINT "_NEGATE ULONG one:"; _NEGATE vulong_one
PRINT "_NEGATE ULONG r1:"; _NEGATE vulong_r1
PRINT "_NEGATE ULONG r2:"; _NEGATE vulong_r2
PRINT "_NEGATE INT64 min:"; _NEGATE vint64_min
PRINT "_NEGATE INT64 max:"; _NEGATE vint64_max
PRINT "_NEGATE INT64 m1:"; _NEGATE vint64_m1
PRINT "_NEGATE INT64 zero:"; _NEGATE vint64_zero
PRINT "_NEGATE INT64 one:"; _NEGATE vint64_one
PRINT "_NEGATE INT64 r1:"; _NEGATE vint64_r1
PRINT "_NEGATE INT64 r2:"; _NEGATE vint64_r2
PRINT "_NEGATE UINT64 min:"; _NEGATE vuint64_min
PRINT "_NEGATE UINT64 max:"; _NEGATE vuint64_max
PRINT "_NEGATE UINT64 m1:"; _NEGATE vuint64_m1
PRINT "_NEGATE UINT64 zero:"; _NEGATE vuint64_zero
PRINT "_NEGATE UINT64 one:"; _NEGATE vuint64_one
PRINT "_NEGATE UINT64 r1:"; _NEGATE vuint64_r1
PRINT "_NEGATE UINT64 r2:"; _NEGATE vuint64_r2
PRINT "_NEGATE OFFSET min:"; _NEGATE voffset_min
PRINT "_NEGATE OFFSET max:"; _NEGATE voffset_max
PRINT "_NEGATE OFFSET m1:"; _NEGATE voffset_m1
PRINT "_NEGATE OFFSET zero:"; _NEGATE voffset_zero
PRINT "_NEGATE OFFSET one:"; _NEGATE voffset_one
PRINT "_NEGATE OFFSET r1:"; _NEGATE voffset_r1
PRINT "_NEGATE OFFSET r2:"; _NEGATE voffset_r2
PRINT "_NEGATE UOFFSET min:"; _NEGATE vuoffset_min
PRINT "_NEGATE UOFFSET max:"; _NEGATE vuoffset_max
PRINT "_NEGATE UOFFSET m1:"; _NEGATE vuoffset_m1
PRINT "_NEGATE UOFFSET zero:"; _NEGATE vuoffset_zero
PRINT "_NEGATE UOFFSET one:"; _NEGATE vuoffset_one
PRINT "_NEGATE UOFFSET r1:"; _NEGATE vuoffset_r1
PRINT "_NEGATE UOFFSET r2:"; _NEGATE vuoffset_r2
PRINT "_NEGATE BIT min:"; _NEGATE vbit_min
PRINT "_NEGATE BIT max:"; _NEGATE vbit_max
PRINT "_NEGATE BIT m1:"; _NEGATE vbit_m1
PRINT "_NEGATE BIT zero:"; _NEGATE vbit_zero
PRINT "_NEGATE BIT one:"; _NEGATE vbit_one
PRINT "_NEGATE BIT r1:"; _NEGATE vbit_r1
PRINT "_NEGATE BIT r2:"; _NEGATE vbit_r2
PRINT "_NEGATE UBIT7 min:"; _NEGATE vubit7_min
PRINT "_NEGATE UBIT7 max:"; _NEGATE vubit7_max
PRINT "_NEGATE UBIT7 m1:"; _NEGATE vubit7_m1
PRINT "_NEGATE UBIT7 zero:"; _NEGATE vubit7_zero
PRINT "_NEGATE UBIT7 one:"; _NEGATE vubit7_one
PRINT "_NEGATE UBIT7 r1:"; _NEGATE vubit7_r1
PRINT "_NEGATE UBIT7 r2:"; _NEGATE vubit7_r2
PRINT "_NEGATE BIT24 min:"; _NEGATE vbit24_min
PRINT "_NEGATE BIT24 max:"; _NEGATE vbit24_max
PRINT "_NEGATE BIT24 m1:"; _NEGATE vbit24_m1
PRINT "_NEGATE BIT24 zero:"; _NEGATE vbit24_zero
PRINT "_NEGATE BIT24 one:"; _NEGATE vbit24_one
PRINT "_NEGATE BIT24 r1:"; _NEGATE vbit24_r1
PRINT "_NEGATE BIT24 r2:"; _NEGATE vbit24_r2
PRINT "_NEGATE UBIT40 min:"; _NEGATE vubit40_min
PRINT "_NEGATE UBIT40 max:"; _NEGATE vubit40_max
PRINT "_NEGATE UBIT40 m1:"; _NEGATE vubit40_m1
PRINT "_NEGATE UBIT40 zero:"; _NEGATE vubit40_zero
PRINT "_NEGATE UBIT40 one:"; _NEGATE vubit40_one
PRINT "_NEGATE UBIT40 r1:"; _NEGATE vubit40_r1
PRINT "_NEGATE UBIT40 r2:"; _NEGATE vubit40_r2
PRINT "_NEGATE SINGLE min:"; _NEGATE vsingle_min
PRINT "_NEGATE SINGLE max:"; _NEGATE vsingle_max
PRINT "_NEGATE SINGLE m1:"; _NEGATE vsingle_m1
PRINT "_NEGATE SINGLE zero:"; _NEGATE vsingle_zero
PRINT "_NEGATE SINGLE one:"; _NEGATE vsingle_one
PRINT "_NEGATE SINGLE r1:"; _NEGATE vsingle_r1
PRINT "_NEGATE SINGLE r2:"; _NEGATE vsingle_r2
PRINT "_NEGATE DOUBLE min:"; _NEGATE vdouble_min
PRINT "_NEGATE DOUBLE max:"; _NEGATE vdouble_max
PRINT "_NEGATE DOUBLE m1:"; _NEGATE vdouble_m1
PRINT "_NEGATE DOUBLE zero:"; _NEGATE vdouble_zero
PRINT "_NEGATE DOUBLE one:"; _NEGATE vdouble_one
PRINT "_NEGATE DOUBLE r1:"; _NEGATE vdouble_r1
PRINT "_NEGATE DOUBLE r2:"; _NEGATE vdouble_r2
PRINT "_NEGATE FLOAT min:"; _NEGATE vfloat_min
PRINT "_NEGATE FLOAT max:"; _NEGATE vfloat_max
PRINT "_NEGATE FLOAT m1:"; _NEGATE vfloat_m1
PRINT "_NEGATE FLOAT zero:"; _NEGATE vfloat_zero
PRINT "_NEGATE FLOAT one:"; _NEGATE vfloat_one
PRINT "_NEGATE FLOAT r1:"; _NEGATE vfloat_r1
PRINT "_NEGATE FLOAT r2:"; _NEGATE vfloat_r2
SYSTEM
h:
PRINT " error"; ERR
RESUME NEXT
