// Writes the language server's single-byte encoding tables (crates/lsp/src/encoding_tables.rs) and the CP437
// fixture of its tests, from iconv-lite: the library the extension and VS Code itself use to read and write a
// document in these encodings, so the server sees the same bytes as the file on disk (design D3 of
// m2-language-server).
//
// Run from the repository root after `npm ci` in vscode/:  node tools/encodings/gen_tables.js
"use strict";

const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "..", "..");
const iconvDir = path.join(repo, "vscode", "node_modules", "iconv-lite");
const iconv = require(iconvDir);
const iconvVersion = require(path.join(iconvDir, "package.json")).version;

// VS Code's encoding ids (`files.encoding`) of the single-byte encodings QB64 programs are written in: the DOS code
// pages first, then the Windows and ISO ones a program edited on Windows or Linux may be in.
const ENCODINGS = [
  "cp437",
  "cp850",
  "cp852",
  "cp865",
  "cp866",
  "windows1250",
  "windows1251",
  "windows1252",
  "iso88591",
  "iso885915",
];

function decodeAll(enc) {
  const units = [];
  for (let b = 0; b < 256; b++) {
    const s = iconv.decode(Buffer.from([b]), enc);
    if (s.length !== 1) {
      throw new Error(`${enc}: byte ${b} decodes to ${s.length} UTF-16 units`);
    }
    units.push(s.charCodeAt(0));
  }
  return units;
}

const hex = (n) => "0x" + n.toString(16).toUpperCase().padStart(4, "0");

let out = "";
out += "//! Generated by `tools/encodings/gen_tables.js` from iconv-lite " + iconvVersion + "; do not edit.\n";
out += "//! Each table gives the character (a UTF-16 unit; every one is in the Basic Multilingual Plane) of each byte.\n";
out += "\n";
out += "pub(crate) const TABLES: &[(&str, [u16; 256])] = &[\n";
for (const enc of ENCODINGS) {
  const units = decodeAll(enc);
  out += `    (\n        "${enc}",\n        [\n`;
  for (let i = 0; i < 256; i += 8) {
    out += "            " + units.slice(i, i + 8).map(hex).join(", ") + ",\n";
  }
  out += "        ],\n    ),\n";
}
out += "];\n";
fs.writeFileSync(path.join(repo, "crates", "lsp", "src", "encoding_tables.rs"), out);

// Every byte 0-255 as the extension reads a CP437 file holding them, written as UTF-8: the server's table must
// encode this text back to the 256 bytes. `.bin`: control bytes are the point (tools/repo_check skips them).
const fixture = path.join(repo, "crates", "lsp", "tests", "fixtures", "cp437_all_bytes_utf8.bin");
fs.mkdirSync(path.dirname(fixture), { recursive: true });
const all = Buffer.alloc(256);
for (let b = 0; b < 256; b++) all[b] = b;
fs.writeFileSync(fixture, Buffer.from(iconv.decode(all, "cp437"), "utf8"));
// And what iconv writes for characters CP437 cannot hold: `?` for each UTF-16 unit, so two for a character
// outside the Basic Multilingual Plane.
const unencodable = iconv.encode("Aé€\u{1F600}B", "cp437");
fs.writeFileSync(fixture.replace("all_bytes_utf8.bin", "unencodable.bin"), unencodable);
console.log("wrote", ENCODINGS.length, "tables; unencodable test bytes:", Array.from(unencodable));
