$CONSOLE:ONLY
DIM b AS _BYTE, ub AS _UNSIGNED _BYTE, i AS INTEGER, ui AS _UNSIGNED INTEGER, l AS LONG, ul AS _UNSIGNED LONG
DIM q AS _INTEGER64, uq AS _UNSIGNED _INTEGER64, sg AS SINGLE, db AS DOUBLE, fl AS _FLOAT, o AS _OFFSET
DIM s AS STRING, fx AS STRING * 4, a(3) AS LONG, sa(3) AS STRING, fa(3) AS STRING * 4, k AS LONG, da(3) AS DOUBLE
TYPE rec
    n AS LONG
    f AS STRING * 4
    d AS DOUBLE
END TYPE
DIM r AS rec, ra(3) AS rec
LINE INPUT ; s
SYSTEM
